#!/usr/bin/env python3
"""Generates fespalier's dashboards from the one spec, scripts/telemetry/dashboards.toml.

Writes, under cli/templates/telemetry/:
  openobserve/dashboards/<id>.json   OpenObserve v8 dashboards (SQL over the traces and logs streams)
  grafana/dashboards/<id>.json       Grafana dashboards (PromQL over the collector's span metrics)
  openobserve/fields.json            the columns the importer creates before the first span arrives
  collector/config.yaml              only the span_metrics dimension list between the BEGIN/END lines

`--check` writes nothing and exits 1 when a file on disk differs from what would be written. The
output has no timestamps, so regenerating is byte-stable. `just telemetry-dashboards` runs this.

A panel (or table column) whose `requires` names an attribute that the conventions
(scripts/telemetry/conventions_v1.txt) do not have is left out.
"""

import argparse
import json
import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPEC = ROOT / "scripts/telemetry/dashboards.toml"
CONVENTIONS = ROOT / "scripts/telemetry/conventions_v1.txt"
OUT = ROOT / "cli/templates/telemetry"

STALE = "stale: run `just telemetry-dashboards` and commit the result"

BEGIN = "      # BEGIN generated by build_dashboards.py"
END = "      # END generated"

# Columns OpenObserve gives every span or log record, or that come from OTLP rather than from
# fespalier's conventions. The queries may name them; the importer creates the Utf8 ones.
TRACE_COLUMNS = ["service_name", "operation_name", "span_status", "status_message", "trace_id"]
LOG_COLUMNS = ["service_name", "severity", "exception_type", "exception_message", "event_name", "body"]
BUILTIN_SQL = {"_timestamp", "duration"} | set(TRACE_COLUMNS) | set(LOG_COLUMNS)
METRICS = {
    "fespalier_calls",
    "fespalier_duration_bucket",
    "fespalier_app_errors",
    "fespalier_app_crashes",
}
SPAN_METRICS = {"fespalier_calls", "fespalier_duration_bucket"}
LABEL = re.compile(r"\b(fespalier_[a-z_]+|error_type)\b")


class Conventions:
    """The names a query may use, read from the names file."""

    def __init__(self, text):
        self.attrs = {}  # key -> list of values ([] when free-form)
        self.resources = []
        self.events = []
        self.event_attrs = set()
        for number, line in enumerate(text.splitlines(), 1):
            line = line.split("#", 1)[0].strip()
            if not line:
                continue
            kind, _, rest = line.partition(" ")
            if kind == "attr":
                key, _, values = rest.partition(" = ")
                self.attrs[key.strip()] = values.split()
            elif kind == "resource":
                self.resources.append(rest.strip())
            elif kind == "event":
                self.events.append(rest.strip())
            elif kind == "event_attr":
                self.event_attrs.add(rest.strip())
            else:
                raise SystemExit(f"{CONVENTIONS}:{number}: unknown declaration {line!r}")
        self.columns = {}  # OpenObserve column / Prometheus label -> key
        for key in self.attrs:
            column = key.replace(".", "_")
            if column in self.columns:
                raise SystemExit(f"two conventions collapse to the column {column}")
            self.columns[column] = key

    @property
    def values(self):
        return {value for values in self.attrs.values() for value in values} | {"true", "false"}

    def span_attrs(self):
        """The attribute keys that become span columns (event attributes do not)."""
        return [key for key in self.attrs if key not in self.event_attrs]


def load_conventions(path=CONVENTIONS):
    return Conventions(Path(path).read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------------------- spec


def expand(text, macros):
    """Expands {name} and {sel:ops}, nested ones too."""

    def sel(match):
        ops = match.group(1)
        if ops is None:
            return 'service_name="$service"'
        operator = "=~" if "|" in ops else "="
        return f'fespalier_operation{operator}"{ops}", service_name="$service"'

    for _ in range(8):
        before = text
        text = re.sub(r"\{sel(?::([^}]*))?\}", sel, text)
        text = re.sub(
            r"\{(" + "|".join(map(re.escape, macros)) + r")\}", lambda m: macros[m.group(1)], text
        )
        if text == before:
            break
    else:
        raise SystemExit(f"macros do not settle in {text!r}")
    return re.sub(r"\{ +", "{", re.sub(r" +\}", "}", text))


def kept(item, conventions):
    return all(r in conventions.attrs for r in item.get("requires", []))


def prepare(spec, conventions):
    """The spec with macros expanded and the panels and columns without their attributes gone."""
    macros = spec.get("macros", {})
    dashboards = []
    for dash in spec["dashboard"]:
        panels = []
        for panel in dash["panels"]:
            if not kept(panel, conventions):
                continue
            panel = dict(panel)
            panel["columns"] = [dict(c) for c in panel["columns"] if kept(c, conventions)]
            promql = [dict(p) for p in panel.get("promql", []) if kept(p, conventions)]
            extra = "".join(f", {c['select']}" for c in panel["columns"] if "select" in c)
            sql = panel["sql"].replace("{extra_columns}", extra)
            panel["sql"] = expand(sql, macros)
            for target in promql:
                target["expr"] = expand(target["expr"], macros)
            panel["promql"] = promql
            panel.setdefault("stream_type", "traces")
            panel.setdefault("width", "quarter" if panel["type"] == "stat" else "half")
            panel.setdefault("grafana", True)
            for c in panel["columns"]:
                c.setdefault("axis", "y")
            panels.append(panel)
        dashboards.append({**dash, "panels": panels})
    return dashboards


# ----------------------------------------------------------------------------------- OpenObserve

OO_TYPES = {"stat": "metric", "timeseries": "line", "bars": "bar", "table": "table"}
OO_WIDTH = {"quarter": 48, "half": 96, "full": 192}
OO_HEIGHT = {"stat": 8}
GF_WIDTH = {"quarter": 6, "half": 12, "full": 24}
GF_HEIGHT = {"stat": 4}


def flow(panels, widths, heights, total, default_height):
    """Left to right, wrapping at `total`; a row is as high as its tallest panel."""
    placed, x, y, row_height = [], 0, 0, 0
    for panel in panels:
        w = widths[panel["width"]]
        h = heights.get(panel["type"], default_height)
        if x + w > total:
            x, y, row_height = 0, y + row_height, 0
        placed.append({"x": x, "y": y, "w": w, "h": h})
        x += w
        row_height = max(row_height, h)
    return placed


def axis_item(column):
    return {"label": column["name"], "alias": column["name"], "column": column["name"], "color": None}


def oo_panel(panel, number, layout):
    columns = panel["columns"]
    unit = "milliseconds" if panel.get("unit") == "ms" else None
    kind = OO_TYPES[panel["type"]]
    fields = {
        "stream": "default",
        "stream_type": panel["stream_type"],
        "x": [axis_item(c) for c in columns if c["axis"] == "x"],
        "y": [axis_item(c) for c in columns if c["axis"] == "y"],
        "z": [],
        "breakdown": [axis_item(c) for c in columns if c["axis"] == "breakdown"],
        "filter": {"filterType": "group", "logicalOperator": "AND", "conditions": []},
    }
    return {
        "id": f"panel_{panel['id']}",
        "type": kind,
        "title": panel["title"],
        "description": "",
        "config": {
            "show_legends": kind in ("line", "bar"),
            "legends_position": None,
            "unit": unit,
            "decimals": 1 if unit else 0,
        },
        "queryType": "sql",
        "queries": [
            {
                "query": panel["sql"],
                "vrlFunctionQuery": "",
                "customQuery": True,
                "fields": fields,
                "config": {"promql_legend": ""},
            }
        ],
        "layout": {**layout, "i": number},
    }


def openobserve_dashboard(dash):
    panels = dash["panels"]
    layouts = flow(panels, OO_WIDTH, OO_HEIGHT, 192, 16)
    return {
        "version": 8,
        "title": f"fespalier · {dash['title']}",
        "description": dash["description"],
        "role": "",
        "owner": "",
        "tabs": [
            {
                "tabId": "default",
                "name": "Overview",
                "panels": [
                    oo_panel(p, n, layouts[n - 1]) for n, p in enumerate(panels, 1)
                ],
            }
        ],
        "variables": {
            "list": [
                {
                    "type": "query_values",
                    "name": "service",
                    "label": "App",
                    "query_data": {
                        "stream_type": "traces",
                        "stream": "default",
                        "field": "service_name",
                        "max_record_size": 20,
                    },
                    "value": None,
                    "options": [],
                    "multiSelect": False,
                }
            ],
            "showDynamicFilters": False,
        },
        "defaultDatetimeDuration": {"type": "relative", "relativeTimePeriod": "1h"},
    }


# --------------------------------------------------------------------------------------- Grafana

DS = {"type": "prometheus", "uid": "fespalier-openobserve"}
REF_IDS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def table_columns(panel):
    """The Grafana table's value columns, in target order: (target, column name)."""
    names = [c["name"] for c in panel["columns"] if c["axis"] == "y" and not c.get("oo_only")]
    names_iter = iter(names)
    result = []
    for target in panel["promql"]:
        result.append((target, target["name"] if target.get("extra") else next(names_iter)))
    return result


def grafana_panel(panel, number, grid):
    kind = panel["type"]
    category_bars = kind == "bars" and not any(c.get("time") for c in panel["columns"])
    tabular = kind == "table" or category_bars
    gf_type = {"stat": "stat", "timeseries": "timeseries", "bars": "timeseries", "table": "table"}[kind]
    if category_bars:
        gf_type = "barchart"
    defaults = {
        "unit": "ms" if panel.get("unit") == "ms" else "short",
        "color": {"mode": "fixed", "fixedColor": "text"},
        "thresholds": {"mode": "absolute", "steps": [{"color": "text", "value": None}]},
    }
    options = {}
    if kind == "stat":
        options = {
            "colorMode": "none",
            "graphMode": "none",
            "textMode": "value",
            "reduceOptions": {"calcs": ["lastNotNull"], "fields": "", "values": False},
        }
    elif kind == "bars" and not category_bars:
        defaults["custom"] = {
            "drawStyle": "bars",
            "fillOpacity": 80,
            "stacking": {"mode": "normal", "group": "A"},
        }
    elif category_bars:
        defaults["color"] = {"mode": "palette-classic"}
        defaults["thresholds"] = {"mode": "absolute", "steps": [{"color": "text", "value": None}]}
    targets = []
    for index, target in enumerate(panel["promql"]):
        item = {
            "refId": REF_IDS[index],
            "datasource": DS,
            "expr": target["expr"],
            "legendFormat": target.get("legend", "__auto"),
        }
        if kind == "stat":
            item.update({"instant": True, "range": False})
        elif tabular:
            item.update({"instant": True, "range": False, "format": "table"})
        else:
            item.update({"instant": False, "range": True})
        targets.append(item)
    out = {
        "id": number,
        "type": gf_type,
        "title": panel["title"],
        "description": "",
        "datasource": DS,
        "gridPos": {**grid, "h": grid["h"]},
        "targets": targets,
        "fieldConfig": {"defaults": defaults, "overrides": []},
        "options": options,
    }
    if tabular:
        values = {
            f"Value #{REF_IDS[i]}": name for i, (_, name) in enumerate(table_columns(panel))
        }
        rename = {**panel.get("rename", {}), **values}
        labels = {v: k for k, v in panel.get("rename", {}).items()}
        order = []
        for column in panel["columns"]:
            if column["axis"] == "x" and not column.get("oo_only") and column["name"] in labels:
                order.append(labels[column["name"]])
        order += list(values)
        out["transformations"] = [
            {"id": "merge", "options": {}},
            {
                "id": "organize",
                "options": {
                    "excludeByName": {"Time": True},
                    "indexByName": {name: i for i, name in enumerate(order)},
                    "renameByName": rename,
                },
            },
        ]
        ms = [name for name in values.values() if name.endswith("_ms")]
        out["fieldConfig"]["overrides"] = [
            {
                "matcher": {"id": "byName", "options": name},
                "properties": [{"id": "unit", "value": "ms"}],
            }
            for name in ms
        ]
        if category_bars:
            x = next(c["name"] for c in panel["columns"] if c["axis"] == "x")
            out["options"] = {
                "xField": x,
                "orientation": "auto",
                "legend": {"showLegend": False},
                "stacking": "none",
                "showValue": "auto",
            }
    if panel.get("links"):
        out["links"] = [{**link, "targetBlank": True} for link in panel["links"]]
    return out


def grafana_dashboard(dash):
    panels = [p for p in dash["panels"] if p["grafana"]]
    grids = flow(panels, GF_WIDTH, GF_HEIGHT, 24, 9)
    return {
        "uid": f"fespalier-{dash['id']}",
        "title": f"fespalier · {dash['title']}",
        "description": dash["description"],
        "tags": ["fespalier"],
        "editable": False,
        "schemaVersion": 41,
        "time": {"from": "now-1h", "to": "now"},
        "refresh": "30s",
        "templating": {
            "list": [
                {
                    "name": "service",
                    "label": "App",
                    "type": "query",
                    "datasource": DS,
                    "query": {
                        "query": "label_values(fespalier_calls, service_name)",
                        "refId": "service",
                    },
                    "refresh": 2,
                    "includeAll": False,
                    "current": {},
                }
            ]
        },
        "panels": [grafana_panel(p, n, grids[n - 1]) for n, p in enumerate(panels, 1)],
    }


# -------------------------------------------------------------------------------------- outputs


def dump(obj):
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def dimensions(dashboards, conventions):
    """The span attributes the Grafana queries use as labels, in the conventions' order."""
    used = set()
    for dash in dashboards:
        for panel in dash["panels"]:
            if not panel["grafana"]:
                continue
            for target in panel["promql"]:
                expr = target["expr"]
                if not any(metric in expr for metric in SPAN_METRICS):
                    continue
                used |= {m for m in LABEL.findall(expr) if m not in METRICS}
    unknown = sorted(c for c in used if c not in conventions.columns)
    if unknown:
        raise SystemExit(f"labels that are not in the conventions: {unknown}")
    keys = [conventions.columns[c] for c in used]
    order = {key: i for i, key in enumerate(conventions.attrs)}
    return sorted(keys, key=order.get)


def fields_json(conventions):
    traces = [k.replace(".", "_") for k in conventions.span_attrs()]
    for name in TRACE_COLUMNS:
        if name not in traces:
            traces.append(name)
    return {"traces": traces, "logs": list(LOG_COLUMNS)}


def collector_text(current, keys):
    lines = current.splitlines()
    try:
        start = lines.index(BEGIN)
        stop = lines.index(END)
    except ValueError:
        raise SystemExit(f"collector/config.yaml lacks the lines {BEGIN!r} and {END!r}") from None
    block = [f"      - name: {key}" for key in keys]
    return "\n".join(lines[: start + 1] + block + lines[stop:]) + "\n"


def build(spec_path=SPEC, conventions=None, out=OUT):
    """Maps each output path (relative to the repo) to its text."""
    conventions = conventions or load_conventions()
    with open(spec_path, "rb") as handle:
        spec = tomllib.load(handle)
    dashboards = prepare(spec, conventions)
    files = {}
    for dash in dashboards:
        files[out / "openobserve/dashboards" / f"{dash['id']}.json"] = dump(
            openobserve_dashboard(dash)
        )
        files[out / "grafana/dashboards" / f"{dash['id']}.json"] = dump(grafana_dashboard(dash))
    files[out / "openobserve/fields.json"] = dump(fields_json(conventions))
    config = out / "collector/config.yaml"
    files[config] = collector_text(
        config.read_text(encoding="utf-8"), dimensions(dashboards, conventions)
    )
    return files, dashboards


def stale_files(files, out=OUT):
    """The files on disk that differ from `files`, and dashboards that no longer belong."""
    stale = [
        path
        for path, text in sorted(files.items())
        if not path.exists() or path.read_text(encoding="utf-8") != text
    ]
    for kind in ("openobserve/dashboards", "grafana/dashboards"):
        stale += [p for p in sorted((out / kind).glob("*.json")) if p not in files]
    return stale


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="write nothing; fail when stale")
    args = parser.parse_args(argv)
    files, _ = build()
    stale = stale_files(files)
    if args.check:
        if stale:
            print(STALE, file=sys.stderr)
            for path in stale:
                print(f"  {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        return 0
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    for path in stale:
        if path not in files:
            path.unlink()
            print(f"removed {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
