// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /            HomeRoute      (tabs)/(home)/page.dart  (observe)
//   /orders      OrdersRoute    (tabs)/orders/page.dart  (observe)
//   /orders/:id  OrderRoute     (tabs)/orders/$id/page.dart  (data, action, observe)
//   /settings    SettingsRoute  (tabs)/settings/page.dart  (guard, observe, deferred)
//   /login       LoginRoute     login/page.dart  (observe)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/observe.dart' as _i0;
import 'app/not_found.dart' as _i1;
import 'app/(tabs)/layout.dart' as _i2;
import 'app/(tabs)/(home)/page.dart' as _i3;
import 'app/(tabs)/orders/page.dart' as _i4;
import 'app/(tabs)/orders/\$id/data.dart' as _i5;
import 'app/(tabs)/orders/\$id/action.dart' as _i6;
import 'app/(tabs)/orders/\$id/page.dart' as _i7;
import 'app/(tabs)/orders/\$id/observe.dart' as _i8;
import 'app/(tabs)/settings/page.dart' deferred as _i9;
import 'app/(tabs)/settings/guard.dart' as _i10;
import 'app/login/page.dart' as _i11;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    final router = GoRouter(
      initialLocation: initialLocation,
      observers: observers,
      restorationScopeId: restorationScopeId,
      navigatorKey: rootNavigatorKey,
      routes: routes,
      errorBuilder: (context, state) => notFound(state.uri),
    );
    attach(router);
    return router;
  }

  /// Lets DevTools, the observe.dart hooks and telemetry follow [router]: [router] calls it, and an app that mounts the
  /// tree in a GoRouter of its own calls it once with that router.
  static void attach(GoRouter router) {
    if (kFespalierDevTools) devToolsAttach(router);
    observeAttach(router, _observeAt);
    telemetryAttach(router, base: () => _base);
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    DeferredLibrary.register(deferred);
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl, providers: _devToolsProviders);
    return [
      StatefulShellRoute.indexedStack(
        pageBuilder: (context, state, navigationShell) => namedPage('/', () => layoutPage(
          context,
          state,
          'layout:(tabs)/',
          _i2.TabsLayout(navigationShell: navigationShell),
        )),
        branches: [
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/'),
                builder: (context, state) => const _i3.HomePage(),
              ),
            ],
            restorationScopeId: 'tab:(tabs)/(home)',
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/orders'),
                builder: (context, state) => const _i4.OrdersPage(),
                routes: [
                  GoRoute(
                    path: ':id',
                    builder: (context, state) => buildWithParams(
                      () => _params4(state),
                      (v) => DataView(
                        watch: (ref) => watchData(ref, 'd4', _data4(v.id)),
                        refresh: (ref) => ref.invalidate(_data4(v.id)),
                        data: (d) => _i7.OrderPage(id: v.id, data: d),
                        loading: () => const DefaultLoading(),
                        error: (e, st, retry) => DefaultError(error: e, retry: retry),
                        keepPrevious: true,
                      ),
                      () => notFound(state.uri),
                    ),
                  ),
                ],
              ),
            ],
            restorationScopeId: 'tab:(tabs)/orders',
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/settings'),
                redirect: (context, state) => traceGuard(state, 'g5@5', refGuard(context, 'g5@5', (ref) => _i10.guard(ref)), telemetry: const TelemetrySite('(tabs)/settings/guard.dart', route: '/settings')),
                builder: (context, state) => DeferredView(
                  library: _lib5,
                  page: () => _i9.SettingsPage(),
                  loading: () => const DefaultLoading(),
                  error: (e, st, retry) => DefaultError(error: e, retry: retry),
                ),
              ),
            ],
            restorationScopeId: 'tab:(tabs)/settings',
          ),
        ],
        restorationScopeId: 'layout:(tabs)/',
      ),
      GoRoute(
        path: joinLocation(at, '/login'),
        builder: (context, state) => const _i11.LoginPage(),
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i1.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), const {}, const []), observe: (s, m) {
      return [
      RouteHooks('observe.dart', onEnter: (ref) => _i0.onEnter(ref, route: m.route), onLeave: (ref) => _i0.onLeave(ref, route: m.route)),
      ];
    }),
    RouteMatcher(['orders'], (s) => UrlMatch(s.uri, const OrdersRoute(), const {}, const []), observe: (s, m) {
      return [
      RouteHooks('observe.dart', onEnter: (ref) => _i0.onEnter(ref, route: m.route), onLeave: (ref) => _i0.onLeave(ref, route: m.route)),
      ];
    }),
    RouteMatcher(['settings'], (s) => UrlMatch(s.uri, const SettingsRoute(), const {}, const []), observe: (s, m) {
      return [
      RouteHooks('observe.dart', onEnter: (ref) => _i0.onEnter(ref, route: m.route), onLeave: (ref) => _i0.onLeave(ref, route: m.route)),
      ];
    }),
    RouteMatcher(['login'], (s) => UrlMatch(s.uri, const LoginRoute(), const {}, const []), observe: (s, m) {
      return [
      RouteHooks('observe.dart', onEnter: (ref) => _i0.onEnter(ref, route: m.route), onLeave: (ref) => _i0.onLeave(ref, route: m.route)),
      ];
    }),
    RouteMatcher(['orders', ':id'], (s) {
      final p = _params4(s);
      return UrlMatch(s.uri, OrderRoute(id: p.id), {'id': p.id}, [_data4(p.id)]);
    }, observe: (s, m) {
      final o4 = _observe4(s);
      return [
      RouteHooks('observe.dart', onEnter: (ref) => _i0.onEnter(ref, route: m.route), onLeave: (ref) => _i0.onLeave(ref, route: m.route)),
      RouteHooks('(tabs)/orders/\$id/observe.dart', onEnter: (ref) => _i8.onEnter(ref, id: o4.id), onLeave: (ref) => _i8.onLeave(ref, id: o4.id), onFocus: (ref) => _i8.onFocus(ref, id: o4.id)),
      ];
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The observe.dart hooks of the page at [uri], outermost first.
  static List<RouteHooks> _observeAt(Uri uri) => observeRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, and its code when it is a deferred route:
  /// `matchUrl(uri)?.route.preload(ref)`. One handle keeps the data alive until it is closed (or
  /// `keepFor` passes); code, once loaded, stays. A location that matches no route gets a closed
  /// handle. It never navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => matchUrl(uri)?.route.preload(ref, keepFor: keepFor) ?? ref.prefetchAll(const [], keepFor: keepFor);

  /// The code of each deferred route (`const deferred = true;` in a route.dart, or `deferred: true`
  /// in pubspec.yaml): its page.dart, imported `deferred as` and loaded the first time the page is
  /// built, or ahead of time by `preload`, a `RouteLink` or [loadDeferred].
  static final List<DeferredLibrary> deferred = [_lib5];

  /// Loads the code of every deferred route now, and completes when it is all there: once the app
  /// is idle on the web, or before `runApp` elsewhere. A widget test that pumps its own router calls
  /// `await tester.runAsync(AppRoutes.loadDeferred)` first (`pumpRouter` does it for you).
  static Future<void> loadDeferred() => DeferredLibrary.loadAll(deferred);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '(tabs)/(home)',
      groups: ['(tabs)', '(home)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 0, '(home)')],
    ),
    RouteInfo(
      type: OrdersRoute,
      path: '/orders',
      folder: '(tabs)/orders',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 1, 'orders')],
    ),
    RouteInfo(
      type: OrderRoute,
      path: '/orders/:id',
      folder: '(tabs)/orders/\$id',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      segments: [RouteParam('id', 'int')],
      tabs: [RouteTab('(tabs)', 1, 'orders')],
      dataKeys: ['id'],
    ),
    RouteInfo(
      type: SettingsRoute,
      path: '/settings',
      folder: '(tabs)/settings',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 2, 'settings')],
      deferred: true,
    ),
    RouteInfo(
      type: LoginRoute,
      path: '/login',
      folder: 'login',
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → (tabs)/(home)/page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) => routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) => maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);
}

/// `/orders` → (tabs)/orders/page.dart
final class OrdersRoute extends TypedLocation {
  const OrdersRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/orders');

  /// The OrdersRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrdersRoute of(BuildContext context) => routeOf<OrdersRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrdersRoute? maybeOf(BuildContext context) => maybeRouteOf<OrdersRoute>(context, AppRoutes.matchUrl);
}

/// `/orders/:id` → (tabs)/orders/$id/page.dart
final class OrderRoute extends TypedLocation {
  const OrderRoute({required this.id});

  final int id;

  /// (tabs)/orders/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data4;

  @override
  String get location => joinLocation(AppRoutes.base, '/orders/$id');

  /// The OrderRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrderRoute of(BuildContext context) => routeOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrderRoute? maybeOf(BuildContext context) => maybeRouteOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  OrderRoute Function({int id}) get copyWith => _copyWith;

  OrderRoute _copyWith({Object? id = _keep}) =>
      OrderRoute(id: _kept<int>(id, this.id));

  /// Watches (tabs)/orders/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int id}) => ref.watch(data(id));

  /// Reads (tabs)/orders/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int id}) => ref.readData(data(id));

  /// Starts loading (tabs)/orders/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs (tabs)/orders/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data4(id)], keepFor: keepFor);

  /// The state of `action()` ((tabs)/orders/$id/action.dart) keyed by `id`: `AsyncValue<T?>`, idle (`AsyncData(null)`) until it runs, then loading, the error or the result. An action never replaces the page with `error.dart` and is never retried.
  static final action = _action4_0;

  /// Runs `action()` once; after a success, the data it made stale (by default the data.dart of this folder and the sections above it, or what `invalidates` lists) is invalidated. Completes with its result, or throws what the action threw; the error is in the state as well.
  static final submit = (WidgetRef ref, {required int id, required String input}) => ref.runAction(action(id), input);

  /// Watches the state of `action()` and gives `call(input)` to run it, for `build`. A failed run is in `state`, not thrown.
  static final useAction = (WidgetRef ref, {required int id}) => ref.watchAction(action(id));
}

/// `/settings` → (tabs)/settings/page.dart
final class SettingsRoute extends TypedLocation {
  const SettingsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/settings');

  /// The SettingsRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static SettingsRoute of(BuildContext context) => routeOf<SettingsRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static SettingsRoute? maybeOf(BuildContext context) => maybeRouteOf<SettingsRoute>(context, AppRoutes.matchUrl);

  /// Starts loading this page's code ((tabs)/settings/page.dart is deferred); it reads no data, so the handle holds nothing. Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) {
    _lib5.preload();
    return ref.prefetchAll(const [], keepFor: keepFor);
  }
}

/// `/login` → login/page.dart
final class LoginRoute extends TypedLocation {
  const LoginRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/login');

  /// The LoginRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static LoginRoute of(BuildContext context) => routeOf<LoginRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static LoginRoute? maybeOf(BuildContext context) => maybeRouteOf<LoginRoute>(context, AppRoutes.matchUrl);
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({int id}) _params4(GoRouterState s) => (id: Segment.asInt(s, 'id'));

({int id}) _observe4(GoRouterState s) => (id: Segment.asInt(s, 'id'));

/// (tabs)/settings/page.dart, imported `deferred as`: loaded the first time the page is built, or ahead of time.
final _lib5 = DeferredLibrary(_i9.loadLibrary, '(tabs)/settings/page.dart', route: '/settings');

final _data4 = FutureProvider.autoDispose.family(
  (Ref ref, int id) => traceDataCall(ref, 'd4', id, () => _i5.data(ref, id: id), telemetry: const TelemetrySite('(tabs)/orders/\$id/data.dart', route: '/orders/:id')),
);

/// `action()` of (tabs)/orders/$id/action.dart: its state, and what it invalidates after a success.
final _action4_0 = actionFamily(
  (Ref ref, int id, String input) => _i6.action(ref, id: id, input: input),
  invalidates: (int id) => <ProviderListenable<AsyncValue<Object?>>>[_data4(id)],
  site: 'a4_0',
  telemetry: const TelemetrySite('(tabs)/orders/\$id/action.dart', route: '/orders/:id', name: 'action'),
);

/// Each data.dart's provider (the family, for one keyed by the URL) by its DevTools site, for a prefetch made before any page watched it. A function, so nothing is read until DevTools asks; only called under `kFespalierDevTools`.
Map<Object, String> _devToolsProviders() => {
      _data4: 'd4',
    };

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"telemetry","appDir":"lib/app","items":[{"type":"tabs","file":"(tabs)/layout.dart","folder":"(tabs)","markers":[],"branches":[{"index":0,"name":"(home)","items":[{"type":"route","pattern":"/","route":"HomeRoute","file":"(tabs)/(home)/page.dart","folder":"(tabs)/(home)","markers":["observe"],"params":[],"redirect":false,"children":[]}]},{"index":1,"name":"orders","items":[{"type":"route","pattern":"/orders","route":"OrdersRoute","file":"(tabs)/orders/page.dart","folder":"(tabs)/orders","markers":["observe"],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/orders/:id","route":"OrderRoute","file":"(tabs)/orders/\$id/page.dart","folder":"(tabs)/orders/\$id","markers":["data","action","observe"],"params":[{"name":"id","type":"int","in":"path"}],"redirect":false,"children":[]}]}]},{"index":2,"name":"settings","items":[{"type":"route","pattern":"/settings","route":"SettingsRoute","file":"(tabs)/settings/page.dart","folder":"(tabs)/settings","markers":["guard","observe","deferred"],"params":[],"redirect":false,"children":[]}]}]},{"type":"route","pattern":"/login","route":"LoginRoute","file":"login/page.dart","folder":"login","markers":["observe"],"params":[],"redirect":false,"children":[]}],"sites":{"a4_0":{"kind":"action","file":"(tabs)/orders/\$id/action.dart","name":"action","route":"OrderRoute"},"d4":{"kind":"data","file":"(tabs)/orders/\$id/data.dart","route":"OrderRoute","section":null,"traced":true},"g5@5":{"kind":"guard","file":"(tabs)/settings/guard.dart","route":"SettingsRoute","pattern":"/settings"}}}';
