//! `contracts.json` is what the Dart sealer reads: for each op, the 32-byte contract digest it
//! binds into a message and the `Cratestack-Contract` selector it may send. It is generated
//! from the schema here and never edited by hand; this test fails when the committed file is
//! stale. `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` rewrites it.

#![allow(clippy::expect_used, clippy::unwrap_used, reason = "tests may unwrap")]

use std::collections::BTreeMap;
use std::path::Path;

use cose_demo_server::{DEFAULT_AUDIENCE, cratestack_schema, hex, is_signed};
use cratestack::ContractSelector;
use cratestack::serde_json::{self, json};

fn render() -> String {
    let ops: BTreeMap<_, _> = cratestack_schema::OP_CONTRACTS
        .iter()
        .map(|(key, digest)| {
            (
                *key,
                json!({
                    "digest": hex(digest),
                    "selector": ContractSelector::of(digest).to_header_value(),
                    "signed": is_signed(key),
                }),
            )
        })
        .collect();
    let document = json!({
        "_comment": "Generated by server/tests/contracts.rs from schema.cstack; never edit by hand.",
        "binding_version": cratestack::cose::BINDING_VERSION,
        "audience": DEFAULT_AUDIENCE,
        "method": "POST",
        "path": "/rpc/{op}",
        "content_type": "application/cose; cose-type=\"cose-sign1\"",
        "payload_type": "application/cbor",
        "contract_header": "Cratestack-Contract",
        "ops": ops,
    });
    let mut text = serde_json::to_string_pretty(&document).expect("json");
    text.push('\n');
    text
}

#[test]
fn contracts_json_is_fresh() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("contracts.json");
    let fresh = render();
    if std::env::var_os("FSP_UPDATE_GOLDEN").is_some() {
        std::fs::write(&path, &fresh).expect("write contracts.json");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        committed == fresh,
        "examples/cose/server/contracts.json is stale; run `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` and commit it"
    );
}

#[test]
fn every_op_of_the_schema_has_a_digest_and_the_batch_route_too() {
    let keys: Vec<_> = cratestack_schema::OP_CONTRACTS
        .iter()
        .map(|(key, _)| *key)
        .collect();
    for expected in [
        "batch",
        "procedure.registerDevice",
        "procedure.listNotes",
        "procedure.addNote",
    ] {
        assert!(keys.contains(&expected), "{expected} in {keys:?}");
    }
}
