//! `contracts.json` and `../lib/src/contracts.g.dart` are what the Dart app reads: for each op,
//! the 32-byte contract digest it binds into a message and the `Cratestack-Contract` selector it
//! sends. Both are generated from the schema here and never edited by hand; these tests fail
//! when a committed file is stale. `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` rewrites
//! them.

#![allow(clippy::expect_used, clippy::unwrap_used, reason = "tests may unwrap")]

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

use cose_demo_server::{DEFAULT_AUDIENCE, cratestack_schema, hex, is_signed};
use cratestack::ContractSelector;
use cratestack::serde_json::{self, json};

fn render() -> String {
    let ops: BTreeMap<_, _> = cratestack_schema::OP_CONTRACTS
        .iter()
        .map(|(key, digest)| {
            (
                *key,
                json!({
                    "digest": hex(digest),
                    "selector": ContractSelector::of(digest).to_header_value(),
                    "signed": is_signed(key),
                }),
            )
        })
        .collect();
    let document = json!({
        "_comment": "Generated by server/tests/contracts.rs from schema.cstack; never edit by hand.",
        "binding_version": cratestack::cose::BINDING_VERSION,
        "audience": DEFAULT_AUDIENCE,
        "method": "POST",
        "path": "/rpc/{op}",
        "content_type": "application/cose; cose-type=\"cose-sign1\"",
        "payload_type": "application/cbor",
        "contract_header": "Cratestack-Contract",
        "ops": ops,
    });
    let mut text = serde_json::to_string_pretty(&document).expect("json");
    text.push('\n');
    text
}

const DART_HEAD: &str = r#"// GENERATED by examples/cose/server/tests/contracts.rs from schema.cstack; never edit by hand.
// Regenerate: `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` in examples/cose/server.

/// What the app needs to know of one op of the server's contract.
final class OpContract {
  /// An op.
  const OpContract({
    required this.digest,
    required this.selector,
    required this.signed,
  });

  /// The op's contract digest, 32 bytes as lowercase hex: bound into every message.
  final String digest;

  /// The `Cratestack-Contract` header value: the first 8 bytes of the digest, unpadded base64url.
  final String selector;

  /// Whether the op travels as a COSE_Sign1 message (false: the plain registration).
  final bool signed;
}

/// The content type of a sealed request and of a sealed response.
const String coseContentType = 'application/cose; cose-type="cose-sign1"';

/// The header that names the contract an op is called under.
const String contractHeader = 'Cratestack-Contract';
"#;

/// The same table as Dart constants: the app imports it, so no digest is copied by hand.
fn render_dart() -> String {
    let mut out = String::from(DART_HEAD);
    writeln!(
        out,
        "\n/// The audience the server binds into every message.\nconst String coseAudience = '{DEFAULT_AUDIENCE}';"
    )
    .unwrap();
    out.push_str(
        "\n/// Every op of the schema by its op id.\nconst Map<String, OpContract> coseOps = {\n",
    );
    for (key, digest) in cratestack_schema::OP_CONTRACTS {
        write!(
            out,
            "  '{key}': OpContract(\n    digest: '{}',\n    selector: '{}',\n    signed: {},\n  ),\n",
            hex(digest),
            ContractSelector::of(digest).to_header_value(),
            is_signed(key),
        )
        .unwrap();
    }
    out.push_str("};\n");
    out
}

#[test]
fn contracts_dart_is_fresh() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../lib/src/contracts.g.dart");
    let fresh = render_dart();
    if std::env::var_os("FSP_UPDATE_GOLDEN").is_some() {
        std::fs::write(&path, &fresh).expect("write contracts.g.dart");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        committed == fresh,
        "examples/cose/lib/src/contracts.g.dart is stale; run `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` in examples/cose/server and commit it"
    );
}

#[test]
fn contracts_json_is_fresh() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("contracts.json");
    let fresh = render();
    if std::env::var_os("FSP_UPDATE_GOLDEN").is_some() {
        std::fs::write(&path, &fresh).expect("write contracts.json");
        return;
    }
    let committed = std::fs::read_to_string(&path).unwrap_or_default();
    assert!(
        committed == fresh,
        "examples/cose/server/contracts.json is stale; run `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` and commit it"
    );
}

#[test]
fn every_op_of_the_schema_has_a_digest_and_the_batch_route_too() {
    let keys: Vec<_> = cratestack_schema::OP_CONTRACTS
        .iter()
        .map(|(key, _)| *key)
        .collect();
    for expected in [
        "batch",
        "procedure.registerDevice",
        "procedure.listNotes",
        "procedure.addNote",
    ] {
        assert!(keys.contains(&expected), "{expected} in {keys:?}");
    }
}
