// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import
//
// main() for the app under lib/app/ (since 0.8.1). lib/main.dart runs it:
// `Future<void> main() => AppMain.run();`

import 'package:fespalier/fespalier.dart';
import 'package:fespalier/startup.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/widgets.dart';

import 'app.g.dart';
import 'app/app.dart' as _i0;
import 'app/startup.dart' as _i1;

/// The app under lib/app/, from main() on: startup.dart, splash.dart and app.dart around
/// [AppRoutes.router].
abstract final class AppMain {
  /// What lib/main.dart calls: the binding,
  /// the code of the deferred routes (loaded before the first frame, off the web), then [root].
  static Future<void> run() => _main();

  static Future<void> _main() async {
    WidgetsFlutterBinding.ensureInitialized();
    if (!kIsWeb) await AppRoutes.loadDeferred();
    runApp(root());
  }

  /// The widget [run] gives `runApp`: startup() (splash.dart while it runs, and if it fails),
  /// then a `ProviderScope` with the overrides it returned around app.dart, which gets
  /// [router]'s router. [router] is called once, after startup().
  static Widget root({GoRouter Function() router = AppRoutes.router}) => StartupGate(
    overrides: _i1.startup,
    router: router,
    app: app,
  );

  /// app.dart's widget around [router]. Tests boot the app as it runs, theme and
  /// localizations included: `pumpRouter(tester, router, app: AppMain.app)`.
  static Widget app(GoRouter router) => _i0.App(router: router);
}
