// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /              HomeRoute      page.dart  (layout, transition)
//   /cart          CartRoute      cart/page.dart  (transition)
//   /checkout      CheckoutRoute  checkout/page.dart  (guard, transition)
//   /greet/:name   GreetRoute     greet/$name/page.dart  (transition)
//   /products      ProductsRoute  products/page.dart  (data, transition)
//   /products/:id  ProductRoute   products/$id/page.dart  (data, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/loading.dart' as _i1;
import 'app/error.dart' as _i2;
import 'app/transition.dart' as _i3;
import 'app/layout.dart' as _i4;
import 'app/not_found.dart' as _i5;
import 'app/cart/page.dart' as _i6;
import 'app/checkout/page.dart' as _i7;
import 'app/checkout/guard.dart' as _i8;
import 'app/greet/\$name/page.dart' as _i9;
import 'app/products/data.dart' as _i10;
import 'app/products/page.dart' as _i11;
import 'app/products/loading.dart' as _i12;
import 'app/products/\$id/data.dart' as _i13;
import 'app/products/\$id/page.dart' as _i14;
import 'app/products/\$id/error.dart' as _i15;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey =
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to [router] or [mount], else one of
  /// its own. Routes on the root navigator (`navigator.dart`, `present.dart`) name it
  /// as their `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    return GoRouter(
      initialLocation: initialLocation,
      observers: observers,
      restorationScopeId: restorationScopeId,
      navigatorKey: rootNavigatorKey,
      routes: routes,
      errorBuilder: (context, state) => notFound(state.uri),
    );
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    if (navigatorKey != null) _rootNavigatorKey = navigatorKey;
    return [
      ShellRoute(
        pageBuilder: (context, state, child) => _i3.transition(
          const ValueKey<String>('layout:/'),
          _i4.AppLayout(child: child),
        ),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            pageBuilder: (context, state) => _i3.transition(
              state.pageKey,
              _i0.HomePage(),
            ),
            routes: [
              GoRoute(
                path: 'cart',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  _i6.CartPage(),
                ),
              ),
              GoRoute(
                path: 'checkout',
                redirect: (context, state) => _i8.guard(ProviderScope.containerOf(context, listen: false)),
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  _i7.CheckoutPage(),
                ),
              ),
              GoRoute(
                path: 'products',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_i10.data),
                    refresh: (ref) => ref.invalidate(_i10.data),
                    data: (d) => _i11.ProductsPage(products: d),
                    loading: () => _i12.ProductsLoading(),
                    error: (e, st, retry) => _i2.RootError(error: e, retry: retry),
                    keepPrevious: true,
                  ),
                ),
                routes: [
                  GoRoute(
                    path: ':id',
                    pageBuilder: (context, state) => _i3.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params6(state),
                        (v) => DataView(
                          watch: (ref) => ref.watch(_data6(v.id)),
                          refresh: (ref) => ref.invalidate(_data6(v.id)),
                          data: (d) => _i14.ProductPage(product: d),
                          loading: () => _i12.ProductsLoading(),
                          error: (e, st, retry) => _i15.ProductError(id: v.id, error: e, retry: retry),
                          keepPrevious: true,
                        ),
                        () => notFound(state.uri),
                      ),
                    ),
                  ),
                ],
              ),
              GoRoute(
                path: 'greet/:name',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params4(state),
                    (v) => _i9.GreetPage(name: v.name),
                    () => notFound(state.uri),
                  ),
                ),
              ),
            ],
          ),
        ],
        restorationScopeId: 'layout:/',
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i5.NotFound(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), {}, [])),
    RouteMatcher(['cart'], (s) => UrlMatch(s.uri, const CartRoute(), {}, [])),
    RouteMatcher(['checkout'], (s) => UrlMatch(s.uri, const CheckoutRoute(), {}, [])),
    RouteMatcher(['products'], (s) => UrlMatch(s.uri, const ProductsRoute(), {}, [_i10.data])),
    RouteMatcher(['greet', ':name'], (s) {
      final p = _params4(s);
      return UrlMatch(s.uri, GreetRoute(name: p.name), {'name': p.name}, []);
    }),
    RouteMatcher(['products', ':id'], (s) {
      final p = _params6(s);
      return UrlMatch(s.uri, ProductRoute(id: p.id), {'id': p.id}, [_data6(p.id)]);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '',
      layouts: [''],
    ),
    RouteInfo(
      type: CartRoute,
      path: '/cart',
      folder: 'cart',
      layouts: [''],
    ),
    RouteInfo(
      type: CheckoutRoute,
      path: '/checkout',
      folder: 'checkout',
      layouts: [''],
    ),
    RouteInfo(
      type: GreetRoute,
      path: '/greet/:name',
      folder: 'greet/\$name',
      layouts: [''],
      segments: [RouteParam('name', 'String')],
    ),
    RouteInfo(
      type: ProductsRoute,
      path: '/products',
      folder: 'products',
      layouts: [''],
      dataKeys: [],
    ),
    RouteInfo(
      type: ProductRoute,
      path: '/products/:id',
      folder: 'products/\$id',
      layouts: [''],
      segments: [RouteParam('id', 'int')],
      dataKeys: ['id'],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/cart` → cart/page.dart
final class CartRoute extends TypedLocation {
  const CartRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/cart');
}

/// `/checkout` → checkout/page.dart
final class CheckoutRoute extends TypedLocation {
  const CheckoutRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/checkout');
}

/// `/greet/:name` → greet/$name/page.dart
final class GreetRoute extends TypedLocation {
  const GreetRoute({required this.name});

  final String name;

  @override
  String get location => joinLocation(AppRoutes.base, '/greet/${Uri.encodeComponent(name)}');
}

/// `/products` → products/page.dart
final class ProductsRoute extends TypedLocation {
  const ProductsRoute();

  /// products/data.dart as a Riverpod provider.
  static final data = _i10.data;

  @override
  String get location => joinLocation(AppRoutes.base, '/products');

  /// Watches products/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads products/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading products/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs products/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_i10.data], keepFor: keepFor);
}

/// `/products/:id` → products/$id/page.dart
final class ProductRoute extends TypedLocation {
  const ProductRoute({required this.id});

  final int id;

  /// products/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data6;

  @override
  String get location => joinLocation(AppRoutes.base, '/products/$id');

  /// Watches products/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int id}) => ref.watch(data(id));

  /// Reads products/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int id}) => ref.readData(data(id));

  /// Starts loading products/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs products/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data6(id)], keepFor: keepFor);
}

({String name}) _params4(GoRouterState s) => (name: Segment.asString(s, 'name'));

({int id}) _params6(GoRouterState s) => (id: Segment.asInt(s, 'id'));

final _data6 = FutureProvider.autoDispose.family(
  (Ref ref, int id) => _i13.data(ref, id: id),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);
