// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /              HomeRoute      page.dart  (layout, transition)
//   /cart          CartRoute      cart/page.dart  (transition)
//   /checkout      CheckoutRoute  checkout/page.dart  (guard, transition)
//   /greet/:name   GreetRoute     greet/$name/page.dart  (transition)
//   /products      ProductsRoute  products/page.dart  (data, transition)
//   /products/:id  ProductRoute   products/$id/page.dart  (data, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/loading.dart' as _i1;
import 'app/error.dart' as _i2;
import 'app/transition.dart' as _i3;
import 'app/layout.dart' as _i4;
import 'app/not_found.dart' as _i5;
import 'app/cart/page.dart' as _i6;
import 'app/checkout/page.dart' as _i7;
import 'app/checkout/guard.dart' as _i8;
import 'app/greet/\$name/page.dart' as _i9;
import 'app/products/data.dart' as _i10;
import 'app/products/page.dart' as _i11;
import 'app/products/loading.dart' as _i12;
import 'app/products/\$id/data.dart' as _i13;
import 'app/products/\$id/page.dart' as _i14;
import 'app/products/\$id/error.dart' as _i15;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      ShellRoute(
        builder: (context, state, child) => _i4.AppLayout(child: child),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            pageBuilder: (context, state) => _i3.transition(
              state.pageKey,
              _i0.HomePage(),
            ),
            routes: [
              GoRoute(
                path: 'cart',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  _i6.CartPage(),
                ),
              ),
              GoRoute(
                path: 'checkout',
                redirect: (context, state) => _i8.guard(ProviderScope.containerOf(context, listen: false)),
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  _i7.CheckoutPage(),
                ),
              ),
              GoRoute(
                path: 'greet/:name',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params4(state),
                    (v) => _i9.GreetPage(name: v.name),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'products',
                pageBuilder: (context, state) => _i3.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_i10.data),
                    refresh: (ref) => ref.invalidate(_i10.data),
                    data: (d) => _i11.ProductsPage(products: d),
                    loading: () => _i12.ProductsLoading(),
                    error: (e, st, retry) => _i2.RootError(error: e, retry: retry),
                  ),
                ),
                routes: [
                  GoRoute(
                    path: ':id',
                    pageBuilder: (context, state) => _i3.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params6(state),
                        (v) => DataView(
                          watch: (ref) => ref.watch(_data6(v.id)),
                          refresh: (ref) => ref.invalidate(_data6(v.id)),
                          data: (d) => _i14.ProductPage(product: d),
                          loading: () => _i12.ProductsLoading(),
                          error: (e, st, retry) => _i15.ProductError(id: v.id, error: e, retry: retry),
                        ),
                        () => notFound(state.uri),
                      ),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i5.NotFound(uri: uri);
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/cart` → cart/page.dart
final class CartRoute extends TypedLocation {
  const CartRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/cart');
}

/// `/checkout` → checkout/page.dart
final class CheckoutRoute extends TypedLocation {
  const CheckoutRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/checkout');
}

/// `/greet/:name` → greet/$name/page.dart
final class GreetRoute extends TypedLocation {
  const GreetRoute({required this.name});

  final String name;

  @override
  String get location => joinLocation(AppRoutes.base, '/greet/${Uri.encodeComponent(name)}');
}

/// `/products` → products/page.dart
final class ProductsRoute extends TypedLocation {
  const ProductsRoute();

  /// products/data.dart as a Riverpod provider.
  static final data = _i10.data;

  @override
  String get location => joinLocation(AppRoutes.base, '/products');

  /// Re-runs products/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

/// `/products/:id` → products/$id/page.dart
final class ProductRoute extends TypedLocation {
  const ProductRoute({required this.id});

  final int id;

  /// products/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data6;

  @override
  String get location => joinLocation(AppRoutes.base, '/products/$id');

  /// Re-runs products/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);
}

({String name}) _params4(GoRouterState s) => (name: Segment.asString(s, 'name'));

({int id}) _params6(GoRouterState s) => (id: Segment.asInt(s, 'id'));

final _data6 = FutureProvider.autoDispose.family(
  (Ref ref, int id) => _i13.data(ref, id: id),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);
