// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element, undefined_shown_name, unused_shown_name, duplicate_import
//
//   /                RootRoute      redirect.dart  (redirect)
//   /:lang           HomeRoute      $lang/page.dart  (layout)
//   /:lang/products  ProductsRoute  $lang/products/page.dart
//     fr  /:lang/produits

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/redirect.dart' as _i0;
import 'app/not_found.dart' as _i1;
import 'app/\$lang/page.dart' as _i2;
import 'app/\$lang/layout.dart' as _i3;
import 'app/\$lang/products/page.dart' as _i4;
import 'package:fespalier_tolgee/fespalier_tolgee.dart' show Lang;
import 'package:flutter/material.dart' show Lang;
import 'package:i18n/app.g.dart' show Lang;
import 'package:i18n/lang.dart' show Lang;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  ///
  /// [launch] (since 0.11.0) is where the app was opened from: it wins over
  /// the platform's initial route and marks the first navigation with its source. It is not
  /// used on the web, where the address bar is the launch.
  static GoRouter router({
    String initialLocation = '/',
    InboundLaunch? launch,
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    return launchRouter(launch, (launch) {
      final router = GoRouter(
        initialLocation: launch?.location ?? initialLocation,
        initialExtra: launch?.extra,
        overridePlatformDefaultLocation: launch != null,
        observers: observers,
        restorationScopeId: restorationScopeId,
        navigatorKey: rootNavigatorKey,
        routes: routes,
        errorBuilder: (context, state) => notFound(state.uri),
      );
      if (kFespalierDevTools) devToolsAttach(router);
      return router;
    });
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl);
    return [
      GoRoute(
        path: joinLocation(at, '/'),
        redirect: (context, state) => traceGuard(state, 'r0', refRedirect(context, (ref) => _i0.redirect(ref))),
      ),
      ShellRoute(
        pageBuilder: (context, state, child) => namedPage('/:lang', () => layoutPage(
          context,
          state,
          'layout:\$lang/',
          buildWithParams(
            () => _layout1(state),
            (v) => _i3.LangLayout(lang: v.lang, child: child),
            () => notFound(state.uri),
          ),
        )),
        routes: [
          GoRoute(
            path: joinLocation(at, '/:lang'),
            builder: (context, state) => buildWithParams(
              () => _params1(state),
              (v) => _i2.HomePage(lang: v.lang),
              () => notFound(state.uri),
            ),
            routes: [
              GoRoute(
                path: ':_l1(products|produits)',
                builder: (context, state) => buildWithParams(
                  () => _params2(state),
                  (v) => _i4.ProductsPage(lang: v.lang),
                  () => notFound(state.uri),
                ),
              ),
            ],
          ),
        ],
        restorationScopeId: 'layout:\$lang/',
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i1.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const RootRoute(), const {}, const [])),
    RouteMatcher([':lang'], (s) {
      final p = _params1(s);
      return UrlMatch(s.uri, HomeRoute(lang: p.lang), {'lang': p.lang}, const []);
    }),
    RouteMatcher([':lang', 'products|produits'], (s) {
      final p = _params2(s);
      return UrlMatch(s.uri, ProductsRoute(lang: p.lang), {'lang': p.lang}, const []);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: RootRoute,
      path: '/',
      folder: '',
      presentation: RoutePresentation.redirect,
    ),
    RouteInfo(
      type: HomeRoute,
      path: '/:lang',
      folder: '\$lang',
      layouts: ['\$lang'],
      segments: [RouteParam('lang', 'Lang')],
    ),
    RouteInfo(
      type: ProductsRoute,
      path: '/:lang/products',
      paths: {'fr': '/:lang/produits'},
      folder: '\$lang/products',
      layouts: ['\$lang'],
      segments: [RouteParam('lang', 'Lang')],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → redirect.dart
final class RootRoute extends TypedLocation {
  const RootRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The RootRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static RootRoute of(BuildContext context) => routeOf<RootRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static RootRoute? maybeOf(BuildContext context) => maybeRouteOf<RootRoute>(context, AppRoutes.matchUrl);
}

/// `/:lang` → $lang/page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute({required this.lang});

  final Lang lang;

  @override
  String get location => joinLocation(AppRoutes.base, '/${lang.name}');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) => routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) => maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  HomeRoute Function({Lang lang}) get copyWith => _copyWith;

  HomeRoute _copyWith({Object? lang = _keep}) =>
      HomeRoute(lang: _kept<Lang>(lang, this.lang));
}

/// `/:lang/products` → $lang/products/page.dart
final class ProductsRoute extends TypedLocation {
  const ProductsRoute({required this.lang});

  final Lang lang;

  @override
  String get location => joinLocation(AppRoutes.base, '/${lang.name}/products');

  /// The location with each localized segment spelled as `_locale` has it (`fr-CA` falls back to
  /// `fr`); a segment with no spelling for it keeps its canonical one. `location` is the canonical spelling.
  @override
  String locationFor(String? _locale) {
    return joinLocation(AppRoutes.base, '/${lang.name}/${localizedSegment(_locale, 'products', {'fr': 'produits'})}');
  }

  /// The ProductsRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static ProductsRoute of(BuildContext context) => routeOf<ProductsRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static ProductsRoute? maybeOf(BuildContext context) => maybeRouteOf<ProductsRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  ProductsRoute Function({Lang lang}) get copyWith => _copyWith;

  ProductsRoute _copyWith({Object? lang = _keep}) =>
      ProductsRoute(lang: _kept<Lang>(lang, this.lang));
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({Lang lang}) _params1(GoRouterState s) => (lang: Segment.asEnum(s, 'lang', Lang.values));

({Lang lang}) _params2(GoRouterState s) => (lang: Segment.asEnum(s, 'lang', Lang.values));

({Lang lang}) _layout1(GoRouterState s) => (lang: Segment.asEnum(s, 'lang', Lang.values));

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"i18n","appDir":"lib/app","items":[{"type":"route","pattern":"/","route":"RootRoute","file":"redirect.dart","folder":"","markers":["redirect"],"params":[],"redirect":true,"children":[]},{"type":"shell","file":"\$lang/layout.dart","folder":"\$lang","markers":[],"items":[{"type":"route","pattern":"/:lang","route":"HomeRoute","file":"\$lang/page.dart","folder":"\$lang","markers":[],"params":[{"name":"lang","type":"Lang","in":"path"}],"redirect":false,"children":[{"type":"route","pattern":"/:lang/products","route":"ProductsRoute","file":"\$lang/products/page.dart","folder":"\$lang/products","markers":[],"spellings":{"fr":"/:lang/produits"},"params":[{"name":"lang","type":"Lang","in":"path"}],"redirect":false,"children":[]}]}]}],"sites":{"r0":{"kind":"redirect","file":"redirect.dart","route":"RootRoute","pattern":"/"}}}';
