// GENERATED by examples/cose/server/tests/contracts.rs from schema.cstack; never edit by hand.
// Regenerate: `FSP_UPDATE_GOLDEN=1 cargo test --test contracts` in examples/cose/server.

/// What the app needs to know of one op of the server's contract.
final class OpContract {
  /// An op.
  const OpContract({
    required this.digest,
    required this.selector,
    required this.signed,
  });

  /// The op's contract digest, 32 bytes as lowercase hex: bound into every message.
  final String digest;

  /// The `Cratestack-Contract` header value: the first 8 bytes of the digest, unpadded base64url.
  final String selector;

  /// Whether the op travels as a COSE_Sign1 message (false: the plain registration).
  final bool signed;
}

/// The content type of a sealed request and of a sealed response.
const String coseContentType = 'application/cose; cose-type="cose-sign1"';

/// The header that names the contract an op is called under.
const String contractHeader = 'Cratestack-Contract';

/// The audience the server binds into every message.
const String coseAudience = 'fespalier-cose';

/// Every op of the schema by its op id.
const Map<String, OpContract> coseOps = {
  'batch': OpContract(
    digest: '2a64044c02a8b4a7ac7da5c5e9d1f71871856c1db7a36a43a560306aeb8eaf0d',
    selector: 'KmQETAKotKc',
    signed: true,
  ),
  'procedure.addNote': OpContract(
    digest: '7434bb3fb9deb2b20402a0af75031fb3a7befd96c3cb82e6793ea0c646754019',
    selector: 'dDS7P7nesrI',
    signed: true,
  ),
  'procedure.listNotes': OpContract(
    digest: '93e498073fcaaa652a776ef499a9d5fadb35423a7672d530f365304d27279682',
    selector: 'k-SYBz_KqmU',
    signed: true,
  ),
  'procedure.registerDevice': OpContract(
    digest: '32d7e5207fb167e6be74c0985abb63efc8a7020f7f6a04c3a834b644b228f75b',
    selector: 'MtflIH-xZ-Y',
    signed: false,
  ),
};
