// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /           HomeRoute   page.dart  (layout, transition)
//   /about      AboutRoute  about/page.dart  (transition)
//   /items/:id  ItemRoute   items/$id/page.dart  (data, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/transition.dart' as _i1;
import 'app/layout.dart' as _i2;
import 'app/not_found.dart' as _i3;
import 'app/about/page.dart' as _i4;
import 'app/items/\$id/data.dart' as _i5;
import 'app/items/\$id/page.dart' as _i6;
import 'app/items/\$id/loading.dart' as _i7;
import 'app/items/\$id/error.dart' as _i8;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey =
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to [router] or [mount], else one of
  /// its own. Routes on the root navigator (`navigator.dart`, `present.dart`) name it
  /// as their `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    return GoRouter(
      initialLocation: initialLocation,
      observers: observers,
      restorationScopeId: restorationScopeId,
      navigatorKey: rootNavigatorKey,
      routes: routes,
      errorBuilder: (context, state) => notFound(state.uri),
    );
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    if (navigatorKey != null) _rootNavigatorKey = navigatorKey;
    return [
      ShellRoute(
        pageBuilder: (context, state, child) => _i1.transition(
          const ValueKey<String>('layout:/'),
          _i2.AppLayout(child: child),
        ),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            pageBuilder: (context, state) =>
                _i1.transition(state.pageKey, _i0.HomePage()),
            routes: [
              GoRoute(
                path: 'about',
                pageBuilder: (context, state) =>
                    _i1.transition(state.pageKey, _i4.page()),
              ),
              GoRoute(
                path: 'items/:id',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params3(state),
                    (v) => DataView(
                      watch: (ref) => ref.watch(_data3(v.id)),
                      refresh: (ref) => ref.invalidate(_data3(v.id)),
                      data: (d) => _i6.ItemPage(item: d, qty: v.qty),
                      loading: () => _i7.ItemLoading(),
                      error: (e, st, retry) =>
                          _i8.ItemError(id: v.id, error: e, retry: retry),
                      keepPrevious: true,
                    ),
                    () => notFound(state.uri),
                  ),
                ),
              ),
            ],
          ),
        ],
        restorationScopeId: 'layout:/',
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i3.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), {}, [])),
    RouteMatcher(['about'], (s) => UrlMatch(s.uri, const AboutRoute(), {}, [])),
    RouteMatcher(['items', ':id'], (s) {
      final p = _params3(s);
      return UrlMatch(
        s.uri,
        ItemRoute(id: p.id, qty: p.qty),
        {'id': p.id, 'qty': p.qty},
        [_data3(p.id)],
      );
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) =>
      matchUrl(uri)?.data;

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(type: HomeRoute, path: '/', folder: '', layouts: ['']),
    RouteInfo(type: AboutRoute, path: '/about', folder: 'about', layouts: ['']),
    RouteInfo(
      type: ItemRoute,
      path: '/items/:id',
      folder: 'items/\$id',
      layouts: [''],
      segments: [RouteParam('id', 'int')],
      query: [RouteParam('qty', 'int?')],
      dataKeys: ['id'],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) =>
      routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) =>
      maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);
}

/// `/about` → about/page.dart
final class AboutRoute extends TypedLocation {
  const AboutRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/about');

  /// The AboutRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static AboutRoute of(BuildContext context) =>
      routeOf<AboutRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static AboutRoute? maybeOf(BuildContext context) =>
      maybeRouteOf<AboutRoute>(context, AppRoutes.matchUrl);
}

/// `/items/:id` → items/$id/page.dart
final class ItemRoute extends TypedLocation {
  const ItemRoute({required this.id, this.qty});

  final int id;
  final int? qty;

  /// items/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data3;

  @override
  String get location =>
      withQuery(joinLocation(AppRoutes.base, '/items/$id'), {'qty': qty});

  /// The ItemRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static ItemRoute of(BuildContext context) =>
      routeOf<ItemRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static ItemRoute? maybeOf(BuildContext context) =>
      maybeRouteOf<ItemRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  ItemRoute Function({int id, int? qty}) get copyWith => _copyWith;

  ItemRoute _copyWith({Object? id = _keep, Object? qty = _keep}) =>
      ItemRoute(id: _kept<int>(id, this.id), qty: _kept<int?>(qty, this.qty));

  /// Watches items/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int id}) =>
      ref.watch(data(id));

  /// Reads items/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int id}) =>
      ref.readData(data(id));

  /// Starts loading items/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) =>
      ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs items/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) =>
    identical(value, _keep) ? current : value as T;

({int id, int? qty}) _params3(GoRouterState s) =>
    (id: Segment.asInt(s, 'id'), qty: Query.asInt(s, 'qty'));

final _data3 = FutureProvider.autoDispose.family(
  (Ref ref, int id) => _i5.data(ref, id: id),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);
