// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import
//
// main() for the app under lib/app/ (since 0.8.1). lib/main.dart runs it:
// `Future<void> main() => AppMain.run();`

import 'package:fespalier/fespalier.dart';
import 'package:fespalier/startup.dart';
import 'package:flutter/widgets.dart';

import 'app.g.dart';
import 'app/app.dart' as _i0;

/// The app under lib/app/, from main() on: startup.dart, splash.dart and app.dart around
/// [AppRoutes.router].
abstract final class AppMain {
  static InboundLaunch? _launch;

  /// Where the app was opened from, asked of the adapters once before the router is built
  /// (since 0.11.0): `AppRoutes.router(launch: AppMain.launch)`. Null until [run] has asked,
  /// and on the web.
  static InboundLaunch? get launch => _launch;

  /// What lib/main.dart calls: everything runs inside the adapters' zones: the binding,
  /// then [root].
  static Future<void> run() => AppAdapters.zone(_main);

  static Future<void> _main() async {
    WidgetsFlutterBinding.ensureInitialized();
    if (AppAdapters.beforeRun() case final ready?) await ready;
    final launch = AppAdapters.launch();
    _launch = launch is Future<InboundLaunch?> ? await launch : launch;
    runApp(root());
  }

  /// The widget [run] gives `runApp`: startup() (splash.dart while it runs, and if it fails),
  /// then a `ProviderScope` with the overrides it returned around app.dart, which gets
  /// [router]'s router. [router] is called once, after startup().
  static Widget root({GoRouter Function() router = _router}) => AppAdapters.wrap(StartupGate(
    extraOverrides: _extraOverrides,
    observers: _providerObservers,
    attach: AppRoutes.attach,
    router: router,
    app: app,
  ));

  /// app.dart's widget around [router]. Tests boot the app as it runs, theme and
  /// localizations included: `pumpRouter(tester, router, app: AppMain.app)`.
  static Widget app(GoRouter router) => _i0.App(router: router);

  /// The router's observers: the adapters', then startup.dart's `routerObservers` (since 0.9.0).
  /// An app.dart `router()` passes them to `AppRoutes.router(observers: ...)`.
  static List<NavigatorObserver> routerObservers() => [...AppAdapters.routerObservers()];
}

GoRouter _router() => AppRoutes.router(launch: AppMain.launch, observers: AppMain.routerObservers());

List<Override> _extraOverrides() => [...AppAdapters.overrides()];

List<ProviderObserver> _providerObservers() => [...AppAdapters.providerObservers()];
