// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /            HomeRoute     page.dart
//   /account     AccountRoute  (members)/account/page.dart
//   /login       LoginRoute    login/page.dart
//   /orders/:id  OrderRoute    orders/$id/page.dart

import 'dart:async';

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';
import 'package:fespalier/startup.dart' show FespalierAdapters, Override;
import 'package:fespalier_push/fespalier_adapter.dart' as _a0;

import 'app/page.dart' as _i0;
import 'app/not_found.dart' as _i1;
import 'app/(members)/guard.dart' as _i2;
import 'app/(members)/account/page.dart' as _i3;
import 'app/login/page.dart' as _i4;
import 'app/orders/\$id/page.dart' as _i5;

/// The packages under `fespalier: adapters:` in pubspec.yaml, in that order (since 0.11.0). The
/// generated main() (lib/app.main.g.dart) calls these; with `main: manual`, your main() does.
abstract final class AppAdapters {
  static final _all = FespalierAdapters([_a0.adapter]);

  /// Runs [body] inside every adapter's zone, the first one's outermost.
  static Future<void> zone(Future<void> Function() body) => _all.zone(body);

  /// Each adapter's beforeRun(), in order; null when none has anything to wait for.
  static Future<void>? beforeRun() => _all.beforeRun();

  /// Where the app was opened from: the first adapter's answer (never asked on the web), since 0.11.0.
  static FutureOr<InboundLaunch?> launch() => _all.launch();

  /// The ProviderScope's overrides, before startup()'s own.
  static List<Override> overrides() => _all.overrides();

  /// The ProviderScope's observers.
  static List<ProviderObserver> providerObservers() => _all.providerObservers();

  /// The router's observers (new ones on each call).
  static List<NavigatorObserver> routerObservers() => _all.routerObservers();

  /// Wraps the root widget, the first adapter's outermost.
  static Widget wrap(Widget root) => _all.wrap(root);
}

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  ///
  /// [launch] (since 0.11.0) is where the app was opened from (`AppAdapters.launch()`): it wins over
  /// the platform's initial route and marks the first navigation with its source. It is not
  /// used on the web, where the address bar is the launch.
  static GoRouter router({
    String initialLocation = '/',
    InboundLaunch? launch,
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    return launchRouter(launch, (launch) {
      final router = GoRouter(
        initialLocation: launch?.location ?? initialLocation,
        initialExtra: launch?.extra,
        overridePlatformDefaultLocation: launch != null,
        observers: observers,
        restorationScopeId: restorationScopeId,
        onEnter: onEnter,
        navigatorKey: rootNavigatorKey,
        routes: routes,
        errorBuilder: (context, state) => notFound(state.uri),
      );
      attach(router);
      return router;
    }, links: true);
  }

  /// Lets DevTools, telemetry and the adapters follow [router]: [router] calls it, and an app that mounts the
  /// tree in a GoRouter of its own calls it once with that router.
  ///
  /// With [container] (since 0.11.0), each adapter's `attach` runs once per router. [router]
  /// calls it without one; the generated main() calls it again with the app's container once
  /// the ProviderScope exists, and an app that builds its own router or main() calls
  /// `AppRoutes.attach(router, container)` itself.
  static void attach(GoRouter router, [ProviderContainer? container]) {
    if (kFespalierDevTools) devToolsAttach(router);
    telemetryAttach(router, base: () => _base);
    if (container != null) AppAdapters._all.attach(router, container);
  }

  /// go_router's `onEnter` (since 0.11.0): each adapter's `onEnter`, in the pubspec's order. A
  /// platform link reaches them with `source: NavigationSource.link`. An app with a GoRouter of
  /// its own passes `onEnter: AppRoutes.onEnter`.
  ///
  /// Any `onEnter` makes go_router parse every navigation asynchronously and apply its
  /// redirect limit to all of them.
  static FutureOr<OnEnterResult> onEnter(
    BuildContext context,
    GoRouterState current,
    GoRouterState next,
    GoRouter router,
  ) => AppAdapters._all.onEnter(context, current, next, router);

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl);
    return [
      GoRoute(
        path: joinLocation(at, '/'),
        builder: (context, state) => const _i0.HomePage(),
        routes: [
          GoRoute(
            path: 'account',
            redirect: (context, state) => traceGuard(state, 'g1@2', refGuard(context, 'g1@2', (ref) => _i2.guard(ref, uri: state.uri)), telemetry: const TelemetrySite('(members)/guard.dart', route: '/account')),
            builder: (context, state) => const _i3.AccountPage(),
          ),
          GoRoute(
            path: 'login',
            builder: (context, state) => buildWithParams(
              () => _params3(state),
              (v) => _i4.LoginPage(from: v.from),
              () => notFound(state.uri),
            ),
          ),
          GoRoute(
            path: 'orders/:id',
            builder: (context, state) => buildWithParams(
              () => _params5(state),
              (v) => _i5.OrderPage(id: v.id),
              () => notFound(state.uri),
            ),
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i1.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), const {}, const [])),
    RouteMatcher(['account'], (s) => UrlMatch(s.uri, const AccountRoute(), const {}, const [])),
    RouteMatcher(['login'], (s) {
      final p = _params3(s);
      return UrlMatch(s.uri, LoginRoute(from: p.from), {'from': p.from}, const []);
    }),
    RouteMatcher(['orders', ':id'], (s) {
      final p = _params5(s);
      return UrlMatch(s.uri, OrderRoute(id: p.id), {'id': p.id}, const []);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '',
    ),
    RouteInfo(
      type: AccountRoute,
      path: '/account',
      folder: '(members)/account',
      groups: ['(members)'],
    ),
    RouteInfo(
      type: LoginRoute,
      path: '/login',
      folder: 'login',
      query: [RouteParam('from', 'String?')],
    ),
    RouteInfo(
      type: OrderRoute,
      path: '/orders/:id',
      folder: 'orders/\$id',
      segments: [RouteParam('id', 'int')],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) => routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) => maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);
}

/// `/account` → (members)/account/page.dart
final class AccountRoute extends TypedLocation {
  const AccountRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/account');

  /// The AccountRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static AccountRoute of(BuildContext context) => routeOf<AccountRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static AccountRoute? maybeOf(BuildContext context) => maybeRouteOf<AccountRoute>(context, AppRoutes.matchUrl);
}

/// `/login` → login/page.dart
final class LoginRoute extends TypedLocation {
  const LoginRoute({this.from});

  final String? from;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/login'), {'from': from});

  /// The LoginRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static LoginRoute of(BuildContext context) => routeOf<LoginRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static LoginRoute? maybeOf(BuildContext context) => maybeRouteOf<LoginRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  LoginRoute Function({String? from}) get copyWith => _copyWith;

  LoginRoute _copyWith({Object? from = _keep}) =>
      LoginRoute(from: _kept<String?>(from, this.from));
}

/// `/orders/:id` → orders/$id/page.dart
final class OrderRoute extends TypedLocation {
  const OrderRoute({required this.id});

  final int id;

  @override
  String get location => joinLocation(AppRoutes.base, '/orders/$id');

  /// The OrderRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrderRoute of(BuildContext context) => routeOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrderRoute? maybeOf(BuildContext context) => maybeRouteOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  OrderRoute Function({int id}) get copyWith => _copyWith;

  OrderRoute _copyWith({Object? id = _keep}) =>
      OrderRoute(id: _kept<int>(id, this.id));
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({String? from}) _params3(GoRouterState s) => (from: Query.asString(s, 'from'));

({int id}) _params5(GoRouterState s) => (id: Segment.asInt(s, 'id'));

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"plugins","appDir":"lib/app","items":[{"type":"route","pattern":"/","route":"HomeRoute","file":"page.dart","folder":"","markers":[],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/account","route":"AccountRoute","file":"(members)/account/page.dart","folder":"(members)/account","markers":["guard"],"params":[],"redirect":false,"children":[]},{"type":"route","pattern":"/login","route":"LoginRoute","file":"login/page.dart","folder":"login","markers":[],"params":[{"name":"from","type":"String?","in":"query"}],"redirect":false,"children":[]},{"type":"route","pattern":"/orders/:id","route":"OrderRoute","file":"orders/\$id/page.dart","folder":"orders/\$id","markers":[],"params":[{"name":"id","type":"int","in":"path"}],"redirect":false,"children":[]}]}],"sites":{"g1@2":{"kind":"guard","file":"(members)/guard.dart","route":"AccountRoute","pattern":"/account"}}}';
