// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /           RootRoute      redirect.dart  (redirect, layout)
//   /notes      NotesRoute     notes/page.dart  (data, action)
//   /notes/:id  NoteEditRoute  notes/$id/page.dart  (data, action)
//   /orders     OrdersRoute    orders/page.dart  (data, fresh, action)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/layout.dart' as _i0;
import 'app/redirect.dart' as _i1;
import 'app/notes/data.dart' as _i2;
import 'app/notes/action.dart' as _i3;
import 'app/notes/page.dart' as _i4;
import 'app/notes/\$id/data.dart' as _i5;
import 'app/notes/\$id/action.dart' as _i6;
import 'app/notes/\$id/page.dart' as _i7;
import 'app/orders/data.dart' as _i8;
import 'app/orders/action.dart' as _i9;
import 'app/orders/page.dart' as _i10;
import 'app/orders/error.dart' as _i11;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  ///
  /// [launch] (since 0.11.0) is where the app was opened from: it wins over
  /// the platform's initial route and marks the first navigation with its source. It is not
  /// used on the web, where the address bar is the launch.
  static GoRouter router({
    String initialLocation = '/',
    InboundLaunch? launch,
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    return launchRouter(launch, (launch) {
      final router = GoRouter(
        initialLocation: launch?.location ?? initialLocation,
        initialExtra: launch?.extra,
        overridePlatformDefaultLocation: launch != null,
        observers: observers,
        restorationScopeId: restorationScopeId,
        navigatorKey: rootNavigatorKey,
        routes: routes,
        errorBuilder: (context, state) => notFound(state.uri),
      );
      if (kFespalierDevTools) devToolsAttach(router);
      return router;
    });
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl, providers: _devToolsProviders);
    return [
      ShellRoute(
        pageBuilder: (context, state, child) => namedPage('/', () => layoutPage(
          context,
          state,
          'layout:/',
          _i0.RootLayout(child: child),
        )),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            redirect: (context, state) => traceGuard(state, 'r0', _i1.redirect()),
          ),
          GoRoute(
            path: joinLocation(at, '/notes'),
            builder: (context, state) => DataView(
              watch: (ref) => watchData(ref, 'd1', _data1),
              refresh: (ref) => ref.invalidate(_data1),
              data: (d) => _i4.NotesPage(d),
              loading: () => const DefaultLoading(),
              error: (e, st, retry) => DefaultError(error: e, retry: retry),
              keepPrevious: true,
            ),
            routes: [
              GoRoute(
                path: ':id',
                builder: (context, state) => buildWithParams(
                  () => _params2(state),
                  (v) => DataView(
                    watch: (ref) => watchData(ref, 'd2', _data2(v.id)),
                    refresh: (ref) => ref.invalidate(_data2(v.id)),
                    data: (d) => _i7.NoteEditPage(d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                    keepPrevious: true,
                  ),
                  () => notFound(state.uri),
                ),
              ),
            ],
          ),
          GoRoute(
            path: joinLocation(at, '/orders'),
            builder: (context, state) => DataView(
              watch: (ref) => watchData(ref, 'd3', _data3),
              refresh: (ref) => ref.invalidate(_data3),
              data: (d) => _i10.OrdersPage(d),
              loading: () => const DefaultLoading(),
              error: (e, st, retry) => _i11.OrdersError(error: e, retry: retry),
              keepPrevious: true,
              keepDataOnError: true,
            ),
          ),
        ],
        restorationScopeId: 'layout:/',
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const RootRoute(), const {}, const [])),
    RouteMatcher(['notes'], (s) => UrlMatch(s.uri, const NotesRoute(), const {}, [_data1])),
    RouteMatcher(['orders'], (s) => UrlMatch(s.uri, const OrdersRoute(), const {}, [_data3])),
    RouteMatcher(['notes', ':id'], (s) {
      final p = _params2(s);
      return UrlMatch(s.uri, NoteEditRoute(id: p.id), {'id': p.id}, [_data2(p.id)]);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: RootRoute,
      path: '/',
      folder: '',
      presentation: RoutePresentation.redirect,
      layouts: [''],
    ),
    RouteInfo(
      type: NotesRoute,
      path: '/notes',
      folder: 'notes',
      layouts: [''],
      dataKeys: [],
    ),
    RouteInfo(
      type: NoteEditRoute,
      path: '/notes/:id',
      folder: 'notes/\$id',
      layouts: [''],
      segments: [RouteParam('id', 'String')],
      dataKeys: ['id'],
    ),
    RouteInfo(
      type: OrdersRoute,
      path: '/orders',
      folder: 'orders',
      layouts: [''],
      dataKeys: [],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → redirect.dart
final class RootRoute extends TypedLocation {
  const RootRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The RootRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static RootRoute of(BuildContext context) => routeOf<RootRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static RootRoute? maybeOf(BuildContext context) => maybeRouteOf<RootRoute>(context, AppRoutes.matchUrl);
}

/// `/notes` → notes/page.dart
final class NotesRoute extends TypedLocation {
  const NotesRoute();

  /// notes/data.dart as a Riverpod provider.
  static final data = _data1;

  @override
  String get location => joinLocation(AppRoutes.base, '/notes');

  /// The NotesRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static NotesRoute of(BuildContext context) => routeOf<NotesRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static NotesRoute? maybeOf(BuildContext context) => maybeRouteOf<NotesRoute>(context, AppRoutes.matchUrl);

  /// Watches notes/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads notes/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading notes/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs notes/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data1], keepFor: keepFor);

  /// The state of `add()` (notes/action.dart): `AsyncValue<T?>`, idle (`AsyncData(null)`) until it runs, then loading, the error or the result. An action never replaces the page with `error.dart` and is never retried.
  static final addAction = _action1_0;

  /// Runs `add()` once; after a success, the data it made stale (by default the data.dart of this folder and the sections above it, or what `invalidates` lists) is invalidated. Completes with its result, or throws what the action threw; the error is in the state as well.
  static final add = (WidgetRef ref, {required String input}) => ref.runAction(addAction, input);

  /// Watches the state of `add()` and gives `call(input)` to run it, for `build`. A failed run is in `state`, not thrown.
  static final useAdd = (WidgetRef ref) => ref.watchAction(addAction);
}

/// `/notes/:id` → notes/$id/page.dart
final class NoteEditRoute extends TypedLocation {
  const NoteEditRoute({required this.id});

  final String id;

  /// notes/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data2;

  @override
  String get location => joinLocation(AppRoutes.base, '/notes/${Uri.encodeComponent(id)}');

  /// The NoteEditRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static NoteEditRoute of(BuildContext context) => routeOf<NoteEditRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static NoteEditRoute? maybeOf(BuildContext context) => maybeRouteOf<NoteEditRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  NoteEditRoute Function({String id}) get copyWith => _copyWith;

  NoteEditRoute _copyWith({Object? id = _keep}) =>
      NoteEditRoute(id: _kept<String>(id, this.id));

  /// Watches notes/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required String id}) => ref.watch(data(id));

  /// Reads notes/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required String id}) => ref.readData(data(id));

  /// Starts loading notes/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs notes/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data2(id)], keepFor: keepFor);

  /// The state of `edit()` (notes/$id/action.dart) keyed by `id`: `AsyncValue<T?>`, idle (`AsyncData(null)`) until it runs, then loading, the error or the result. An action never replaces the page with `error.dart` and is never retried.
  static final editAction = _action2_0;

  /// Runs `edit()` once; after a success, the data it made stale (by default the data.dart of this folder and the sections above it, or what `invalidates` lists) is invalidated. Completes with its result, or throws what the action threw; the error is in the state as well.
  static final edit = (WidgetRef ref, {required String id, required _i6.NoteChanges input}) => ref.runAction(editAction(id), input);

  /// Watches the state of `edit()` and gives `call(input)` to run it, for `build`. A failed run is in `state`, not thrown.
  static final useEdit = (WidgetRef ref, {required String id}) => ref.watchAction(editAction(id));
}

/// `/orders` → orders/page.dart
final class OrdersRoute extends TypedLocation {
  const OrdersRoute();

  /// orders/data.dart as a Riverpod provider.
  static final data = _data3;

  @override
  String get location => joinLocation(AppRoutes.base, '/orders');

  /// The OrdersRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrdersRoute of(BuildContext context) => routeOf<OrdersRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrdersRoute? maybeOf(BuildContext context) => maybeRouteOf<OrdersRoute>(context, AppRoutes.matchUrl);

  /// Watches orders/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads orders/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading orders/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs orders/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data3], keepFor: keepFor);

  /// The state of `cancel()` (orders/action.dart): `AsyncValue<T?>`, idle (`AsyncData(null)`) until it runs, then loading, the error or the result. An action never replaces the page with `error.dart` and is never retried.
  static final cancelAction = _action3_0;

  /// Runs `cancel()` once; after a success, the data it made stale (by default the data.dart of this folder and the sections above it, or what `invalidates` lists) is invalidated. Completes with its result, or throws what the action threw; the error is in the state as well.
  static final cancel = (WidgetRef ref, {required _i9.CancelInput input}) => ref.runAction(cancelAction, input);

  /// Watches the state of `cancel()` and gives `call(input)` to run it, for `build`. A failed run is in `state`, not thrown.
  static final useCancel = (WidgetRef ref) => ref.watchAction(cancelAction);
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({String id}) _params2(GoRouterState s) => (id: Segment.asString(s, 'id'));

final _data1 = FutureProvider.autoDispose(
  (Ref ref) => traceData(ref, 'd1', null, _i2.data(ref)),
);

final _data2 = FutureProvider.autoDispose.family(
  (Ref ref, String id) => traceData(ref, 'd2', id, _i5.data(ref, id: id)),
);

final _data3 = FutureProvider.autoDispose(
  (Ref ref) => freshData(ref, _i8.freshness, traceData(ref, 'd3', null, _i8.data(ref))),
);

/// `add()` of notes/action.dart: its state, and what it invalidates after a success.
final _action1_0 = actionProvider(
  (Ref ref, String input) => _i3.add(ref, input: input),
  invalidates: () => <ProviderListenable<AsyncValue<Object?>>>[_data1],
  site: 'a1_0',
);

/// `edit()` of notes/$id/action.dart: its state, and what it invalidates after a success.
final _action2_0 = actionFamily(
  (Ref ref, String id, _i6.NoteChanges input) => _i6.edit(ref, id: id, input: input),
  invalidates: (String id) => <ProviderListenable<AsyncValue<Object?>>>[_data2(id)],
  site: 'a2_0',
);

/// `cancel()` of orders/action.dart: its state, and what it invalidates after a success.
final _action3_0 = actionProvider(
  (Ref ref, _i9.CancelInput input) => _i9.cancel(ref, input: input),
  invalidates: () => <ProviderListenable<AsyncValue<Object?>>>[_data3],
  site: 'a3_0',
);

/// Each data.dart's provider (the family, for one keyed by the URL) by its DevTools site, for a prefetch made before any page watched it. A function, so nothing is read until DevTools asks; only called under `kFespalierDevTools`.
Map<Object, String> _devToolsProviders() => {
      _data1: 'd1',
      _data2: 'd2',
      _data3: 'd3',
    };

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"offline","appDir":"lib/app","items":[{"type":"shell","file":"layout.dart","folder":"","markers":[],"items":[{"type":"route","pattern":"/","route":"RootRoute","file":"redirect.dart","folder":"","markers":["redirect"],"params":[],"redirect":true,"children":[]},{"type":"route","pattern":"/notes","route":"NotesRoute","file":"notes/page.dart","folder":"notes","markers":["data","action"],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/notes/:id","route":"NoteEditRoute","file":"notes/\$id/page.dart","folder":"notes/\$id","markers":["data","action"],"params":[{"name":"id","type":"String","in":"path"}],"redirect":false,"children":[]}]},{"type":"route","pattern":"/orders","route":"OrdersRoute","file":"orders/page.dart","folder":"orders","markers":["data","fresh","action"],"params":[],"redirect":false,"children":[]}]}],"sites":{"a1_0":{"kind":"action","file":"notes/action.dart","name":"add","route":"NotesRoute"},"a2_0":{"kind":"action","file":"notes/\$id/action.dart","name":"edit","route":"NoteEditRoute"},"a3_0":{"kind":"action","file":"orders/action.dart","name":"cancel","route":"OrdersRoute"},"d1":{"kind":"data","file":"notes/data.dart","route":"NotesRoute","section":null,"traced":true},"d2":{"kind":"data","file":"notes/\$id/data.dart","route":"NoteEditRoute","section":null,"traced":true},"d3":{"kind":"data","file":"orders/data.dart","route":"OrdersRoute","section":null,"traced":true},"r0":{"kind":"redirect","file":"redirect.dart","route":"RootRoute","pattern":"/"}}}';
