apiVersion: 1
datasources:
  - name: OpenObserve (fespalier)
    uid: fespalier-openobserve
    type: prometheus
    access: proxy
    url: http://openobserve:5080/api/default/prometheus
    basicAuth: true
    basicAuthUser: ${FSP_O2_EMAIL}
    secureJsonData:
      basicAuthPassword: ${FSP_O2_PASSWORD}
    jsonData:
      httpMethod: GET
      timeInterval: 15s
    isDefault: true
    editable: false
