// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /              ProductsRoute  page.dart  (data)
//   /products/:id  ProductRoute   products/$id/page.dart  (data)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/data.dart' as _i0;
import 'app/page.dart' as _i1;
import 'app/not_found.dart' as _i2;
import 'app/products/\$id/data.dart' as _i3;
import 'app/products/\$id/page.dart' as _i4;
import 'app/products/\$id/loading.dart' as _i5;
import 'app/products/\$id/error.dart' as _i6;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  ///
  /// [launch] (since 0.11.0) is where the app was opened from: it wins over
  /// the platform's initial route and marks the first navigation with its source. It is not
  /// used on the web, where the address bar is the launch.
  static GoRouter router({
    String initialLocation = '/',
    InboundLaunch? launch,
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    return launchRouter(launch, (launch) {
      final router = GoRouter(
        initialLocation: launch?.location ?? initialLocation,
        initialExtra: launch?.extra,
        overridePlatformDefaultLocation: launch != null,
        observers: observers,
        restorationScopeId: restorationScopeId,
        navigatorKey: rootNavigatorKey,
        routes: routes,
        errorBuilder: (context, state) => notFound(state.uri),
      );
      if (kFespalierDevTools) devToolsAttach(router);
      return router;
    });
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl, providers: _devToolsProviders);
    return [
      GoRoute(
        path: joinLocation(at, '/'),
        builder: (context, state) => DataView(
          watch: (ref) => watchData(ref, 'd0', _data0),
          refresh: (ref) => ref.invalidateSelected(_data0),
          data: (d) => _i1.ProductsPage(products: d),
          loading: () => const DefaultLoading(),
          error: (e, st, retry) => DefaultError(error: e, retry: retry),
          keepPrevious: true,
        ),
        routes: [
          GoRoute(
            path: 'products/:id',
            builder: (context, state) => buildWithParams(
              () => _params2(state),
              (v) => DataView(
                watch: (ref) => watchData(ref, 'd2', _data2(v.id)),
                refresh: (ref) => ref.invalidateSelected(_data2(v.id)),
                data: (d) => _i4.ProductPage(product: d),
                loading: () => const _i5.ProductLoading(),
                error: (e, st, retry) => _i6.ProductError(retry: retry),
                keepPrevious: true,
              ),
              () => notFound(state.uri),
            ),
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i2.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const ProductsRoute(), const {}, [_data0])),
    RouteMatcher(['products', ':id'], (s) {
      final p = _params2(s);
      return UrlMatch(s.uri, ProductRoute(id: p.id), {'id': p.id}, [_data2(p.id)]);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: ProductsRoute,
      path: '/',
      folder: '',
      dataKeys: [],
    ),
    RouteInfo(
      type: ProductRoute,
      path: '/products/:id',
      folder: 'products/\$id',
      segments: [RouteParam('id', 'int')],
      dataKeys: ['id'],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class ProductsRoute extends TypedLocation {
  const ProductsRoute();

  /// data.dart as a Riverpod provider.
  static final data = _data0;

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The ProductsRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static ProductsRoute of(BuildContext context) => routeOf<ProductsRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static ProductsRoute? maybeOf(BuildContext context) => maybeRouteOf<ProductsRoute>(context, AppRoutes.matchUrl);

  /// Watches data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readSelected(data);

  /// Starts loading data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refreshSelected(data);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data0], keepFor: keepFor);
}

/// `/products/:id` → products/$id/page.dart
final class ProductRoute extends TypedLocation {
  const ProductRoute({required this.id});

  final int id;

  /// products/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data2;

  @override
  String get location => joinLocation(AppRoutes.base, '/products/$id');

  /// The ProductRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static ProductRoute of(BuildContext context) => routeOf<ProductRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static ProductRoute? maybeOf(BuildContext context) => maybeRouteOf<ProductRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  ProductRoute Function({int id}) get copyWith => _copyWith;

  ProductRoute _copyWith({Object? id = _keep}) =>
      ProductRoute(id: _kept<int>(id, this.id));

  /// Watches products/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int id}) => ref.watch(data(id));

  /// Reads products/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int id}) => ref.readSelected(data(id));

  /// Starts loading products/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs products/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refreshSelected(data(id));

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data2(id)], keepFor: keepFor);
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({int id}) _params2(GoRouterState s) => (id: Segment.asInt(s, 'id'));

/// data.dart selects the app's own provider: nothing wraps it.
final _data0 = _i0.data();

/// data.dart selects the app's own provider: nothing wraps it (a closure, so its type is inferred).
final _data2 = (int id) => _i3.data(id: id);

/// Each data.dart's provider (the family, for one keyed by the URL) by its DevTools site, for a prefetch made before any page watched it. A function, so nothing is read until DevTools asks; only called under `kFespalierDevTools`.
Map<Object, String> _devToolsProviders() => {
      _data0: 'd0',
    };

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"adopt","appDir":"lib/app","items":[{"type":"route","pattern":"/","route":"ProductsRoute","file":"page.dart","folder":"","markers":["data"],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/products/:id","route":"ProductRoute","file":"products/\$id/page.dart","folder":"products/\$id","markers":["data"],"params":[{"name":"id","type":"int","in":"path"}],"redirect":false,"children":[]}]}],"sites":{"d0":{"kind":"data","file":"data.dart","route":"ProductsRoute","section":null,"traced":false},"d2":{"kind":"data","file":"products/\$id/data.dart","route":"ProductRoute","section":null,"traced":false}}}';
