#!/usr/bin/env python3
"""Pins the SHA-256 of a release's `fsp` archives inside the Dart package.

    scripts/pin_checksums.py --version 0.3.0 --dist dist
    scripts/pin_checksums.py --reset

The first form reads the `fsp-<target>.tar.gz.sha256` / `.zip.sha256` files the release
workflow builds and writes packages/fespalier/lib/src/release_checksums.dart, which
`dart run fespalier` checks its download against. The version must be the one in
packages/fespalier/pubspec.yaml. `--reset` writes the empty file that development builds
carry (no pins; the launcher then falls back to the release's own `.sha256`); run it when you
bump the version, since `cli/tests/versions.rs` refuses pins for another version.
Standard library only.
"""

import argparse
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import packaging  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
PUBSPEC = ROOT / "packages/fespalier/pubspec.yaml"
OUT = ROOT / "packages/fespalier/lib/src/release_checksums.dart"

HEADER = """\
// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '%s';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{%s};
"""


def render(version: str, sums: dict) -> str:
    """The Dart file for `version` (empty: no pins) with `sums` mapping target -> SHA-256."""
    if version:
        packaging.check_version(version)
        if set(sums) != set(packaging.ALL_ARCHIVES):
            raise ValueError(f"expected checksums for {sorted(packaging.ALL_ARCHIVES)}, got {sorted(sums)}")
        body = "\n" + "".join(f"  '{t}':\n      '{packaging.check_sha(t, sums[t])}',\n" for t in sorted(sums))
    else:
        if sums:
            raise ValueError("checksums without a version")
        body = ""
    return HEADER % (version, body)


def pubspec_version(text: str) -> str:
    """The top-level `version:`, tolerating quotes and a trailing comment (release-please's
    `# x-release-please-version` annotation)."""
    m = re.search(r"^version:\s*[\"']?([^\s\"'#]+)", text, re.MULTILINE)
    if not m:
        raise ValueError("no `version:` in the pubspec")
    return m.group(1)


def archive_sums(dist: Path) -> dict:
    """target -> SHA-256 of the archives themselves (not of what a `.sha256` file claims)."""
    sums = {}
    for target, archive in packaging.ALL_ARCHIVES.items():
        path = dist / archive
        if not path.is_file():
            raise FileNotFoundError(f"missing {path}")
        sums[target] = hashlib.sha256(path.read_bytes()).hexdigest()
    return sums


def check(dart: str, version: str, sums: dict) -> None:
    """Raises ValueError unless `dart` pins exactly `version` and exactly `sums`."""
    pinned_version, pinned = parse(dart)
    if pinned_version != version:
        raise ValueError(f"the committed pins are for {pinned_version or 'nothing'}, not {version}")
    if set(pinned) != set(sums):
        raise ValueError(f"the committed pins cover {sorted(pinned)}, expected {sorted(sums)}")
    for target in sorted(sums):
        if pinned[target] != sums[target]:
            raise ValueError(
                f"{target}: the archive is {sums[target]} but the commit pins {pinned[target]}"
            )


def parse(dart: str):
    """(version, {target: sha}) of a generated file."""
    m = re.search(r"const pinnedVersion = '([^']*)';", dart)
    if not m:
        raise ValueError("no pinnedVersion in the file")
    sums = dict(re.findall(r"'([a-z0-9_]+(?:-[a-z0-9_]+)+)':\s*'([0-9a-f]{64})'", dart))
    return m.group(1), sums


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--version", help="release version without the v, e.g. 0.3.0")
    ap.add_argument("--dist", type=Path, default=Path("dist"), help="folder with the .sha256 files")
    ap.add_argument("--out", type=Path, default=OUT, help="the Dart file to write")
    ap.add_argument("--pubspec", type=Path, default=PUBSPEC, help="pubspec.yaml the version must match")
    ap.add_argument("--reset", action="store_true", help="write the empty file of an unreleased version")
    ap.add_argument("--archives", action="store_true", help="hash the archives in --dist instead of reading their .sha256 files")
    ap.add_argument("--check", action="store_true", help="verify the committed file against the archives in --dist; writes nothing")
    args = ap.parse_args(argv)
    try:
        if args.check:
            if not args.version:
                ap.error("--version is required with --check")
            check(args.out.read_text(), args.version, archive_sums(args.dist))
            print(f"{args.out} pins the {args.version} archives in {args.dist}")
            return 0
        if args.reset:
            text = render("", {})
        else:
            if not args.version:
                ap.error("--version is required (or --reset)")
            in_pubspec = pubspec_version(args.pubspec.read_text())
            if in_pubspec != args.version:
                raise ValueError(
                    f"{args.pubspec} is at {in_pubspec}, not {args.version}; "
                    "refusing to pin another version's binaries"
                )
            sums = archive_sums(args.dist) if args.archives else packaging.read_checksums(args.dist)
            text = render(args.version, sums)
    except (OSError, ValueError, KeyError) as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    print(f"wrote {args.out} ({'reset' if args.reset else 'pinned ' + args.version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
