// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '0.14.0';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{
  'aarch64-apple-darwin':
      '07adeba6392cfa022ecabbf0589c8492368d07d030eab7a4ac75a513813ef8f3',
  'aarch64-unknown-linux-gnu':
      '34634c110817fdb3500e17e7478a944c3422dfe2b9d1799fce18f8113904cdf0',
  'x86_64-apple-darwin':
      'd5c74c26711c371ca5ebc2b71a3603cbf6a792819e959f5bb4214efca5490f51',
  'x86_64-pc-windows-msvc':
      '48b0144d086252bcdbc10d53a385f0fb6a3cd7107eb4a5aa42ddb24faa1f767e',
  'x86_64-unknown-linux-gnu':
      '9cb6ef7f8ad8045743eef9b3dd3355348f761f22da2a2976372867296d18bf06',
};
