// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /            HomeRoute       page.dart  (transition)
//   /admin       AdminRoute      (signed-in)/admin/page.dart  (guard, transition)
//   /orders      OrdersRoute     (signed-in)/orders/page.dart  (data, transition)
//   /orders/:id  OrderRoute      (signed-in)/orders/$id/page.dart  (data, transition)
//   /forbidden   ForbiddenRoute  forbidden/page.dart  (transition)
//   /sign-in     SignInRoute     sign-in/page.dart  (action, guard, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/transition.dart' as _i1;
import 'app/not_found.dart' as _i2;
import 'app/(signed-in)/guard.dart' as _i3;
import 'app/(signed-in)/admin/page.dart' as _i4;
import 'app/(signed-in)/admin/guard.dart' as _i5;
import 'app/(signed-in)/orders/data.dart' as _i6;
import 'app/(signed-in)/orders/page.dart' as _i7;
import 'app/(signed-in)/orders/\$id/data.dart' as _i8;
import 'app/(signed-in)/orders/\$id/page.dart' as _i9;
import 'app/forbidden/page.dart' as _i10;
import 'app/sign-in/action.dart' as _i11;
import 'app/sign-in/page.dart' as _i12;
import 'app/sign-in/guard.dart' as _i13;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    final router = GoRouter(
      initialLocation: initialLocation,
      observers: observers,
      restorationScopeId: restorationScopeId,
      navigatorKey: rootNavigatorKey,
      routes: routes,
      errorBuilder: (context, state) => notFound(state.uri),
    );
    if (kFespalierDevTools) devToolsAttach(router);
    return router;
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl, providers: _devToolsProviders);
    return [
      GoRoute(
        path: joinLocation(at, '/'),
        pageBuilder: (context, state) => _i1.transition(
          state.pageKey,
          const _i0.HomePage(),
        ),
        routes: [
          GoRoute(
            path: 'admin',
            redirect: (context, state) => firstRedirect([
              () => traceGuard(state, 'g1@2', refGuard(context, 'g1@2', (ref) => _i3.guard(ref, uri: state.uri))),
              () => traceGuard(state, 'g2@2', refGuard(context, 'g2@2', (ref) => _i5.guard(ref, uri: state.uri))),
            ]),
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              const _i4.AdminPage(),
            ),
          ),
          GoRoute(
            path: 'orders',
            redirect: (context, state) => traceGuard(state, 'g1@3', refGuard(context, 'g1@3', (ref) => _i3.guard(ref, uri: state.uri))),
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              DataView(
                watch: (ref) => watchData(ref, 'd3', _data3),
                refresh: (ref) => ref.invalidate(_data3),
                data: (d) => _i7.OrdersPage(orders: d),
                loading: () => const DefaultLoading(),
                error: (e, st, retry) => DefaultError(error: e, retry: retry),
                keepPrevious: true,
              ),
            ),
            routes: [
              GoRoute(
                path: ':id',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params4(state),
                    (v) => DataView(
                      watch: (ref) => watchData(ref, 'd4', _data4(v.id)),
                      refresh: (ref) => ref.invalidate(_data4(v.id)),
                      data: (d) => _i9.OrderPage(order: d),
                      loading: () => const DefaultLoading(),
                      error: (e, st, retry) => DefaultError(error: e, retry: retry),
                      keepPrevious: true,
                    ),
                    () => notFound(state.uri),
                  ),
                ),
              ),
            ],
          ),
          GoRoute(
            path: 'forbidden',
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              const _i10.ForbiddenPage(),
            ),
          ),
          GoRoute(
            path: 'sign-in',
            redirect: (context, state) => traceGuard(state, 'g6@6', guardWithParams(
              () => _params6(state),
              (v) => refGuard(context, 'g6@6', (ref) => _i13.guard(ref, from: v.from)),
            )),
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              buildWithParams(
                () => _params6(state),
                (v) => _i12.SignInPage(from: v.from),
                () => notFound(state.uri),
              ),
            ),
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => _i2.NotFoundPage(uri: uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), const {}, const [])),
    RouteMatcher(['admin'], (s) => UrlMatch(s.uri, const AdminRoute(), const {}, const [])),
    RouteMatcher(['orders'], (s) => UrlMatch(s.uri, const OrdersRoute(), const {}, [_data3])),
    RouteMatcher(['forbidden'], (s) => UrlMatch(s.uri, const ForbiddenRoute(), const {}, const [])),
    RouteMatcher(['sign-in'], (s) {
      final p = _params6(s);
      return UrlMatch(s.uri, SignInRoute(from: p.from), {'from': p.from}, const []);
    }),
    RouteMatcher(['orders', ':id'], (s) {
      final p = _params4(s);
      return UrlMatch(s.uri, OrderRoute(id: p.id), {'id': p.id}, [_data4(p.id)]);
    }),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '',
    ),
    RouteInfo(
      type: AdminRoute,
      path: '/admin',
      folder: '(signed-in)/admin',
      groups: ['(signed-in)'],
    ),
    RouteInfo(
      type: OrdersRoute,
      path: '/orders',
      folder: '(signed-in)/orders',
      groups: ['(signed-in)'],
      dataKeys: [],
    ),
    RouteInfo(
      type: OrderRoute,
      path: '/orders/:id',
      folder: '(signed-in)/orders/\$id',
      groups: ['(signed-in)'],
      segments: [RouteParam('id', 'int')],
      dataKeys: ['id'],
    ),
    RouteInfo(
      type: ForbiddenRoute,
      path: '/forbidden',
      folder: 'forbidden',
    ),
    RouteInfo(
      type: SignInRoute,
      path: '/sign-in',
      folder: 'sign-in',
      query: [RouteParam('from', 'String?')],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) => routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) => maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);
}

/// `/admin` → (signed-in)/admin/page.dart
final class AdminRoute extends TypedLocation {
  const AdminRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/admin');

  /// The AdminRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static AdminRoute of(BuildContext context) => routeOf<AdminRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static AdminRoute? maybeOf(BuildContext context) => maybeRouteOf<AdminRoute>(context, AppRoutes.matchUrl);
}

/// `/orders` → (signed-in)/orders/page.dart
final class OrdersRoute extends TypedLocation {
  const OrdersRoute();

  /// (signed-in)/orders/data.dart as a Riverpod provider.
  static final data = _data3;

  @override
  String get location => joinLocation(AppRoutes.base, '/orders');

  /// The OrdersRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrdersRoute of(BuildContext context) => routeOf<OrdersRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrdersRoute? maybeOf(BuildContext context) => maybeRouteOf<OrdersRoute>(context, AppRoutes.matchUrl);

  /// Watches (signed-in)/orders/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads (signed-in)/orders/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading (signed-in)/orders/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs (signed-in)/orders/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data3], keepFor: keepFor);
}

/// `/orders/:id` → (signed-in)/orders/$id/page.dart
final class OrderRoute extends TypedLocation {
  const OrderRoute({required this.id});

  final int id;

  /// (signed-in)/orders/$id/data.dart as a Riverpod provider keyed by `id`.
  static final data = _data4;

  @override
  String get location => joinLocation(AppRoutes.base, '/orders/$id');

  /// The OrderRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OrderRoute of(BuildContext context) => routeOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OrderRoute? maybeOf(BuildContext context) => maybeRouteOf<OrderRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  OrderRoute Function({int id}) get copyWith => _copyWith;

  OrderRoute _copyWith({Object? id = _keep}) =>
      OrderRoute(id: _kept<int>(id, this.id));

  /// Watches (signed-in)/orders/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int id}) => ref.watch(data(id));

  /// Reads (signed-in)/orders/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int id}) => ref.readData(data(id));

  /// Starts loading (signed-in)/orders/$id/data.dart before navigating; kept alive until the handle is closed (or `keepFor` passes).
  PrefetchHandle prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(id), keepFor: keepFor);

  /// Re-runs (signed-in)/orders/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(id).future);

  /// Starts loading everything this page reads (the data of each section above it, then its own: `AppRoutes.dataAt(location)`), kept alive until the handle is closed (or `keepFor` passes). Never navigates, runs no guard.
  @override
  PrefetchHandle preload(WidgetRef ref, {Duration? keepFor}) => ref.prefetchAll([_data4(id)], keepFor: keepFor);
}

/// `/forbidden` → forbidden/page.dart
final class ForbiddenRoute extends TypedLocation {
  const ForbiddenRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/forbidden');

  /// The ForbiddenRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static ForbiddenRoute of(BuildContext context) => routeOf<ForbiddenRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static ForbiddenRoute? maybeOf(BuildContext context) => maybeRouteOf<ForbiddenRoute>(context, AppRoutes.matchUrl);
}

/// `/sign-in` → sign-in/page.dart
final class SignInRoute extends TypedLocation {
  const SignInRoute({this.from});

  final String? from;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/sign-in'), {'from': from});

  /// The SignInRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static SignInRoute of(BuildContext context) => routeOf<SignInRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static SignInRoute? maybeOf(BuildContext context) => maybeRouteOf<SignInRoute>(context, AppRoutes.matchUrl);

  /// A copy with the given segments and query parameters changed; one left out keeps its value, and
  /// `null` clears an optional one. (A getter of a function type, so that leaving a parameter out
  /// and passing `null` differ without a parameter's type widening: `copyWith(page: null)`.)
  SignInRoute Function({String? from}) get copyWith => _copyWith;

  SignInRoute _copyWith({Object? from = _keep}) =>
      SignInRoute(from: _kept<String?>(from, this.from));

  /// The state of `action()` (sign-in/action.dart): `AsyncValue<T?>`, idle (`AsyncData(null)`) until it runs, then loading, the error or the result. An action never replaces the page with `error.dart` and is never retried.
  static final action = _action6_0;

  /// Runs `action()` once; after a success, the data it made stale (by default the data.dart of this folder and the sections above it, or what `invalidates` lists) is invalidated. Completes with its result, or throws what the action threw; the error is in the state as well.
  static final submit = (WidgetRef ref, {required _i11.SignInFields input}) => ref.runAction(action, input);

  /// Watches the state of `action()` and gives `call(input)` to run it, for `build`. A failed run is in `state`, not thrown.
  static final useAction = (WidgetRef ref) => ref.watchAction(action);

  /// The form of `action()` (sign-in/action.dart), for `build` in a `HookConsumerWidget`: a typed field per field of its input, starting from `form()`; `onSubmit` checks the fields and `validate()`, then runs it, and is null while it runs. Since 0.8.1.
  static final useForm = (WidgetRef ref, {ActionFormValidation validation = ActionFormValidation.afterSubmit, bool resetOnSuccess = false, ActionFormMessages messages = const ActionFormMessages()}) => useActionForm(ref, action, data: null, initial: () => _i11.form(), fields: (ActionFormFields<_i11.SignInFields> f) => (username: f.text('username', (v) => v.username, FieldCodec.text), password: f.text('password', (v) => v.password, FieldCodec.text)), input: (f) => (username: f.username.value, password: f.password.value), validate: _i11.validate, validation: validation, resetOnSuccess: resetOnSuccess, messages: messages);
}

/// What a `copyWith` parameter is when it is left out: private, so no caller can pass it,
/// and the route's own value is kept. Its public type is the field's, so `null` is a value.
final class _Keep {
  const _Keep();
}

const _keep = _Keep();

T _kept<T>(Object? value, T current) => identical(value, _keep) ? current : value as T;

({int id}) _params4(GoRouterState s) => (id: Segment.asInt(s, 'id'));

({String? from}) _params6(GoRouterState s) => (from: Query.asString(s, 'from'));

final _data3 = FutureProvider.autoDispose(
  (Ref ref) => traceData(ref, 'd3', null, _i6.data(ref)),
);

final _data4 = FutureProvider.autoDispose.family(
  (Ref ref, int id) => traceData(ref, 'd4', id, _i8.data(ref, id: id)),
);

/// `action()` of sign-in/action.dart: its state, and what it invalidates after a success.
final _action6_0 = actionProvider(
  (Ref ref, _i11.SignInFields input) => _i11.action(ref, input: input),
  invalidates: () => const <ProviderListenable<AsyncValue<Object?>>>[],
  validate: _i11.validate,
  site: 'a6_0',
);

/// Each data.dart's provider (the family, for one keyed by the URL) by its DevTools site, for a prefetch made before any page watched it. A function, so nothing is read until DevTools asks; only called under `kFespalierDevTools`.
Map<Object, String> _devToolsProviders() => {
      _data3: 'd3',
      _data4: 'd4',
    };

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"auth","appDir":"lib/app","items":[{"type":"route","pattern":"/","route":"HomeRoute","file":"page.dart","folder":"","markers":[],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/admin","route":"AdminRoute","file":"(signed-in)/admin/page.dart","folder":"(signed-in)/admin","markers":["guard"],"params":[],"redirect":false,"children":[]},{"type":"route","pattern":"/orders","route":"OrdersRoute","file":"(signed-in)/orders/page.dart","folder":"(signed-in)/orders","markers":["data","guard"],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/orders/:id","route":"OrderRoute","file":"(signed-in)/orders/\$id/page.dart","folder":"(signed-in)/orders/\$id","markers":["data"],"params":[{"name":"id","type":"int","in":"path"}],"redirect":false,"children":[]}]},{"type":"route","pattern":"/forbidden","route":"ForbiddenRoute","file":"forbidden/page.dart","folder":"forbidden","markers":[],"params":[],"redirect":false,"children":[]},{"type":"route","pattern":"/sign-in","route":"SignInRoute","file":"sign-in/page.dart","folder":"sign-in","markers":["action","guard"],"params":[{"name":"from","type":"String?","in":"query"}],"redirect":false,"children":[]}]}],"sites":{"a6_0":{"kind":"action","file":"sign-in/action.dart","name":"action","route":"SignInRoute"},"d3":{"kind":"data","file":"(signed-in)/orders/data.dart","route":"OrdersRoute","section":null,"traced":true},"d4":{"kind":"data","file":"(signed-in)/orders/\$id/data.dart","route":"OrderRoute","section":null,"traced":true},"g1@2":{"kind":"guard","file":"(signed-in)/guard.dart","route":"AdminRoute","pattern":"/admin"},"g1@3":{"kind":"guard","file":"(signed-in)/guard.dart","route":"OrdersRoute","pattern":"/orders"},"g2@2":{"kind":"guard","file":"(signed-in)/admin/guard.dart","route":"AdminRoute","pattern":"/admin"},"g6@6":{"kind":"guard","file":"sign-in/guard.dart","route":"SignInRoute","pattern":"/sign-in"}}}';
