// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '0.5.0';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{
  'aarch64-apple-darwin':
      '45cba963c35d58ed027d3156aa79c7720032fe56d84ff46a691a34041082d8dc',
  'aarch64-unknown-linux-gnu':
      '4a5ec72b9b029eeacf85546aba765e0a12e05790651b31431bddbac5ad8b1ec4',
  'x86_64-apple-darwin':
      'a9aec9ccff4888959793cb8fb66ba3857785dee33aced71e17de1ebfd18234f8',
  'x86_64-pc-windows-msvc':
      'bbee14a9fb336672978ebbf9267837fddffa141cc1a07e5ec3fdef8854ba97ee',
  'x86_64-unknown-linux-gnu':
      '3b0c6bd2da170e86f7d0477b3ef613e778ac69481ec9db7d35946efdc4ee430e',
};
