// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '0.6.0';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{
  'aarch64-apple-darwin':
      '3961531442bf998e2fb4c0afd8e673915164c586a5ee48699979909a415a3905',
  'aarch64-unknown-linux-gnu':
      '6702ff7370a17a849c0116391feca723dfeca6ff067642311f5b33b172e893c5',
  'x86_64-apple-darwin':
      '54c7a2f6da4ae5016733dba3f7ee073514311710df7aca7d443bab50beba7b0d',
  'x86_64-pc-windows-msvc':
      'a9a317420bf6dc624209c5ea33c50f89985a5f8e060b84c22d4640d29325b45b',
  'x86_64-unknown-linux-gnu':
      '2ba6db53e7602558c81a6f5792ee01ba61be0d74fec7a4266934daca41520d5b',
};
