// GENERATED by scripts/pin_checksums.py. Do not edit by hand.
//
// The SHA-256 of every `fsp` release archive of this package's version, pinned in the
// package itself so `dart run fespalier` can tell a tampered release from a good one. The
// `release-pins` workflow builds the binaries on the release-please PR, and commits this file
// to that PR's branch; merging the PR tags that commit, so the tag carries its own pins.
// A package whose version has no pins here (a development build, or a release PR before its
// pin commit) falls back to the release's `.sha256` file: `pinnedVersion` is another version
// or empty.

/// The version [pinnedChecksums] belongs to, or `''` when nothing is pinned.
const pinnedVersion = '0.3.0';

/// Release target -> SHA-256 of its archive (`fsp-<target>.tar.gz` / `.zip`).
const pinnedChecksums = <String, String>{
  'aarch64-apple-darwin':
      'ee3b5a7ddc5834cfa961df0b4252d6619e622dd8be88125ef757063b123f6db6',
  'aarch64-unknown-linux-gnu':
      'b7191f346f17cbd7983870a40dda658d2deec4f571af4298bf7641974df1f211',
  'x86_64-apple-darwin':
      '96a4de3aafdde953f1de5b6f6b53dc09d1bdf5b177604e84ca28495323d1129e',
  'x86_64-pc-windows-msvc':
      '490293b5abc592256238f998355fa69a83f1486fb3a16e94cc853c1ff04472fd',
  'x86_64-unknown-linux-gnu':
      '14aecb4da3384613b0fc0b4aa080fad845b29417880f773bd23f810b994fb1f8',
};
