//! Writes `lib/app.g.dart`: one readable, committed file that federates the
//! tree into `AppRoutes.router()` / `AppRoutes.mount(at:)` plus typed routes.

use std::fmt::Write;

use crate::resolve::{App, ParamsType, Route, ROOT_PARAMS};
use crate::scan::{Kind, Seg};

pub fn emit(app: &App) -> String {
    let mut o = String::new();
    header(app, &mut o);
    imports(app, &mut o);
    app_routes(app, &mut o);
    typed_routes(app, &mut o);
    plumbing(app, &mut o);
    synth_params(app, &mut o);
    o
}

fn header(app: &App, o: &mut String) {
    o.push_str("// GENERATED by trellis from lib/app/. Do not edit; run `trellis gen`.\n");
    o.push_str("// ignore_for_file: type=lint, unused_import, unused_element\n//\n");
    let rows: Vec<(String, String, String)> = app
        .routes
        .iter()
        .filter(|r| r.page.is_some())
        .map(|r| {
            let mut tags = vec![];
            if r.data.is_some() {
                tags.push("data");
            }
            if r.guard.is_some() {
                tags.push("guard");
            }
            if r.layout.is_some() {
                tags.push("layout");
            }
            let file = if r.dir.is_empty() { Kind::Page.file().to_string() } else { format!("{}/page.dart", r.dir) };
            let tags = if tags.is_empty() { String::new() } else { format!("  ({})", tags.join(", ")) };
            (pattern(app, r), format!("{}Route", r.name.as_deref().unwrap_or("?")), format!("{file}{tags}"))
        })
        .collect();
    let w0 = rows.iter().map(|r| r.0.len()).max().unwrap_or(0);
    let w1 = rows.iter().map(|r| r.1.len()).max().unwrap_or(0);
    for (p, n, f) in rows {
        writeln!(o, "//   {p:w0$}  {n:w1$}  {f}").unwrap();
    }
    o.push('\n');
}

fn imports(app: &App, o: &mut String) {
    o.push_str("import 'package:flutter/widgets.dart';\n");
    o.push_str("import 'package:trellis/trellis.dart';\n\n");
    for (i, rel) in app.imports.iter().enumerate() {
        writeln!(o, "import 'app/{}' as _i{i};", rel.replace('$', "\\$")).unwrap();
    }
    o.push('\n');
}

fn app_routes(app: &App, o: &mut String) {
    let not_found = match &app.not_found {
        Some(s) => format!("{}(uri)", s.expr()),
        None => "DefaultNotFound(uri)".into(),
    };
    let tree = routes_of(app, 0, true, "").join(",\n");
    writeln!(
        o,
        r#"/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {{
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({{
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }}) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({{String at = '/'}}) {{
    _base = at;
    return [
{},
    ];
  }}

  static Widget notFound(Uri uri) => {not_found};
}}
"#,
        indent(&tree, 6)
    )
    .unwrap();
}

/// RouteBase expressions for a folder. Page-less folders fold their segment
/// into their children's paths; `layout.dart` wraps the result in a ShellRoute.
fn routes_of(app: &App, id: usize, top: bool, prefix: &str) -> Vec<String> {
    let r = &app.routes[id];
    let own = match &r.seg {
        None => String::new(),
        Some(Seg::Static(s)) => s.clone(),
        Some(Seg::Dynamic(n)) => format!(":{n}"),
    };
    let path = match (prefix.is_empty(), own.is_empty()) {
        (_, true) => prefix.trim_end_matches('/').to_string(),
        (true, false) => own,
        (false, false) => format!("{prefix}{own}"),
    };

    let mut out = if r.page.is_some() {
        let path_expr = if top { format!("joinLocation(at, '/{path}')") } else { format!("'{path}'") };
        let children: Vec<String> = r.children.iter().flat_map(|&c| routes_of(app, c, false, "")).collect();
        vec![go_route(app, id, &path_expr, &children)]
    } else {
        let next = if path.is_empty() { String::new() } else { format!("{path}/") };
        r.children.iter().flat_map(|&c| routes_of(app, c, top, &next)).collect()
    };

    if let Some(layout) = &r.layout {
        if !out.is_empty() {
            out = vec![format!(
                "ShellRoute(\n  builder: (context, state, child) => {}(child),\n  routes: [\n{},\n  ],\n)",
                layout.expr(),
                indent(&out.join(",\n"), 4)
            )];
        }
    }
    out
}

fn go_route(app: &App, id: usize, path_expr: &str, children: &[String]) -> String {
    let r = &app.routes[id];
    let page = r.page.as_ref().unwrap().expr();
    let mut s = format!("GoRoute(\n  path: {path_expr},\n");
    if let Some(g) = r.guard {
        write!(
            s,
            "  redirect: (context, state) => guardWithParams(\n    () => _params{id}(state),\n    (p) => _i{g}.guard(ProviderScope.containerOf(context, listen: false), p),\n  ),\n"
        )
        .unwrap();
    }
    let build = if r.data.is_some() {
        let loading = match &r.loading {
            Some(l) => format!("{}(p)", l.expr()),
            None => "const DefaultLoading()".into(),
        };
        let error = match &r.error {
            Some(e) => format!("{}(p, f)", e.expr()),
            None => "DefaultError(f)".into(),
        };
        format!(
            "(p) {{\n  final key = RouteKey(_loc{id}(p), p);\n  return DataView(\n    watch: (ref) => ref.watch(_data{id}(key)),\n    refresh: (ref) => ref.invalidate(_data{id}(key)),\n    data: (d) => {page}(d),\n    loading: () => {loading},\n    error: (f) => {error},\n  );\n}}"
        )
    } else {
        format!("(p) => {page}(p)")
    };
    write!(
        s,
        "  builder: (context, state) => buildWithParams(\n    () => _params{id}(state),\n{},\n    () => notFound(state.uri),\n  ),\n",
        indent(&build, 4)
    )
    .unwrap();
    if !children.is_empty() {
        write!(s, "  routes: [\n{},\n  ],\n", indent(&children.join(",\n"), 4)).unwrap();
    }
    s.push(')');
    s
}

fn typed_routes(app: &App, o: &mut String) {
    for (id, r) in app.routes.iter().enumerate() {
        let (Some(name), Some(_)) = (&r.name, &r.page) else { continue };
        let p = &r.params;
        let file = if r.dir.is_empty() { "page.dart".to_string() } else { format!("{}/page.dart", r.dir) };
        writeln!(o, "/// `{}` → {file}", pattern(app, r)).unwrap();
        writeln!(o, "final class {name}Route extends TypedLocation {{").unwrap();
        if p.fields.is_empty() {
            writeln!(o, "  const {name}Route();\n").unwrap();
        } else {
            let args: Vec<String> = p.fields.iter().map(|(n, _)| format!("required this.{n}")).collect();
            writeln!(o, "  const {name}Route({{{}}});\n", args.join(", ")).unwrap();
            for (n, t) in &p.fields {
                writeln!(o, "  final {t} {n};").unwrap();
            }
            o.push('\n');
        }
        writeln!(o, "  {} get params => {};\n", p.expr, p.construct(|n, _| n.to_string())).unwrap();
        writeln!(o, "  @override\n  String get location => joinLocation(AppRoutes.base, _loc{id}(params));").unwrap();
        if let Some(d) = &r.data {
            let what = if d.stream { "Restarts" } else { "Re-runs" };
            writeln!(
                o,
                "\n  /// {what} {}/data.dart; completes with the fresh value.\n  Future<void> refresh(WidgetRef ref) {{\n    final p = params;\n    return ref.refresh(_data{id}(RouteKey(_loc{id}(p), p)).future);\n  }}",
                if r.dir.is_empty() { "." } else { &r.dir }
            )
            .unwrap();
        }
        o.push_str("}\n\n");
    }
}

fn plumbing(app: &App, o: &mut String) {
    for (id, r) in app.routes.iter().enumerate() {
        if r.page.is_none() {
            continue;
        }
        let p = &r.params;
        writeln!(o, "{} _params{id}(GoRouterState s) => {};", p.expr, parse_expr(p)).unwrap();
        writeln!(o, "String _loc{id}({} p) => '{}';", p.expr, location_template(app, r)).unwrap();
        if let Some(d) = &r.data {
            let provider = if d.stream { "StreamProvider" } else { "FutureProvider" };
            writeln!(
                o,
                "final _data{id} = {provider}.autoDispose.family(\n  (Ref ref, RouteKey<{}> key) => _i{}.data(ref, key.params),\n);",
                p.expr, d.import
            )
            .unwrap();
        }
        o.push('\n');
    }
}

fn synth_params(app: &App, o: &mut String) {
    for s in &app.synth {
        let mut args: Vec<String> = s.parent_fields.iter().map(|(n, _)| format!("required super.{n}")).collect();
        args.push(format!("required this.{}", s.field));
        let konst = if s.parent_expr == ROOT_PARAMS { "const " } else { "" };
        writeln!(
            o,
            "/// Generated for `${}`. Add a params.dart next to it to change the type.\nclass {} extends {} {{\n  {konst}{}({{{}}});\n\n  final String {};\n}}\n",
            s.field,
            s.name,
            s.parent_expr,
            s.name,
            args.join(", "),
            s.field
        )
        .unwrap();
    }
}

fn parse_expr(p: &ParamsType) -> String {
    p.construct(|n, t| {
        let reader = match t {
            "int" => "asInt",
            "double" => "asDouble",
            "bool" => "asBool",
            _ => "asString",
        };
        format!("Segment.{reader}(s, '{n}')")
    })
}

fn segments(app: &App, r: &Route) -> Vec<Seg> {
    // Walk from the root to `r` using dir prefixes.
    let mut segs = vec![];
    let mut dir = String::new();
    for part in r.dir.split('/').filter(|s| !s.is_empty()) {
        dir = if dir.is_empty() { part.to_string() } else { format!("{dir}/{part}") };
        if let Some(n) = app.routes.iter().find(|x| x.dir == dir) {
            if let Some(s) = &n.seg {
                segs.push(s.clone());
            }
        }
    }
    segs
}

fn pattern(app: &App, r: &Route) -> String {
    let parts: Vec<String> = segments(app, r)
        .into_iter()
        .map(|s| match s {
            Seg::Static(s) => s,
            Seg::Dynamic(n) => format!(":{n}"),
        })
        .collect();
    format!("/{}", parts.join("/"))
}

fn location_template(app: &App, r: &Route) -> String {
    let parts: Vec<String> = segments(app, r)
        .into_iter()
        .map(|s| match s {
            Seg::Static(s) => s,
            Seg::Dynamic(n) => format!("${{Uri.encodeComponent(p.{n}.toString())}}"),
        })
        .collect();
    format!("/{}", parts.join("/"))
}

fn indent(s: &str, n: usize) -> String {
    let pad = " ".repeat(n);
    s.lines()
        .map(|l| if l.is_empty() { String::new() } else { format!("{pad}{l}") })
        .collect::<Vec<_>>()
        .join("\n")
}
