//! The minijinja environment for everything fespalier writes: `app.g.dart`
//! and the files `fsp new` and `fsp init` scaffold. Templates live in `cli/templates/`.

use std::sync::OnceLock;

use minijinja::Environment;
use serde::Serialize;

const TEMPLATES: [(&str, &str); 61] = [
    ("app.g.dart", include_str!("../templates/app.g.dart.jinja")),
    (
        "main.g.dart",
        include_str!("../templates/main.g.dart.jinja"),
    ),
    (
        "manifest.dart",
        include_str!("../templates/manifest.dart.jinja"),
    ),
    (
        "manifest_body.dart",
        include_str!("../templates/manifest_body.dart.jinja"),
    ),
    (
        "new/_macros.dart",
        include_str!("../templates/new/_macros.dart.jinja"),
    ),
    (
        "new/page.dart",
        include_str!("../templates/new/page.dart.jinja"),
    ),
    (
        "new/data.dart",
        include_str!("../templates/new/data.dart.jinja"),
    ),
    (
        "new/action.dart",
        include_str!("../templates/new/action.dart.jinja"),
    ),
    (
        "new/loading.dart",
        include_str!("../templates/new/loading.dart.jinja"),
    ),
    (
        "new/error.dart",
        include_str!("../templates/new/error.dart.jinja"),
    ),
    (
        "new/layout.dart",
        include_str!("../templates/new/layout.dart.jinja"),
    ),
    (
        "new/not_found.dart",
        include_str!("../templates/new/not_found.dart.jinja"),
    ),
    (
        "new/guard.dart",
        include_str!("../templates/new/guard.dart.jinja"),
    ),
    (
        "new/transition.dart",
        include_str!("../templates/new/transition.dart.jinja"),
    ),
    (
        "new/nav.dart",
        include_str!("../templates/new/nav.dart.jinja"),
    ),
    (
        "new/observe.dart",
        include_str!("../templates/new/observe.dart.jinja"),
    ),
    (
        "new/leave.dart",
        include_str!("../templates/new/leave.dart.jinja"),
    ),
    (
        "init/layout.dart",
        include_str!("../templates/init/layout.dart.jinja"),
    ),
    (
        "init/page.dart",
        include_str!("../templates/init/page.dart.jinja"),
    ),
    (
        "init/not_found.dart",
        include_str!("../templates/init/not_found.dart.jinja"),
    ),
    (
        "init/app.dart",
        include_str!("../templates/init/app.dart.jinja"),
    ),
    (
        "init/transition.dart",
        include_str!("../templates/init/transition.dart.jinja"),
    ),
    (
        "init/pubspec_tasks.yaml",
        include_str!("../templates/init/pubspec_tasks.yaml.jinja"),
    ),
    (
        "create/pubspec.yaml",
        include_str!("../templates/create/pubspec.yaml.jinja"),
    ),
    (
        "create/main.dart",
        include_str!("../templates/create/main.dart.jinja"),
    ),
    (
        "create/home.dart",
        include_str!("../templates/create/home.dart.jinja"),
    ),
    (
        "create/about.dart",
        include_str!("../templates/create/about.dart.jinja"),
    ),
    (
        "create/storage_test.dart",
        include_str!("../templates/create/storage_test.dart.jinja"),
    ),
    (
        "create/connectivity_test.dart",
        include_str!("../templates/create/connectivity_test.dart.jinja"),
    ),
    (
        "create/devtools_options.yaml",
        include_str!("../templates/create/devtools_options.yaml.jinja"),
    ),
    (
        "create/devtools_test.dart",
        include_str!("../templates/create/devtools_test.dart.jinja"),
    ),
    (
        "create/flags.dart",
        include_str!("../templates/create/flags.dart.jinja"),
    ),
    (
        "create/labs_guard.dart",
        include_str!("../templates/create/labs_guard.dart.jinja"),
    ),
    (
        "create/labs_page.dart",
        include_str!("../templates/create/labs_page.dart.jinja"),
    ),
    (
        "create/flags_test.dart",
        include_str!("../templates/create/flags_test.dart.jinja"),
    ),
    (
        "create/contact_action.dart",
        include_str!("../templates/create/contact_action.dart.jinja"),
    ),
    (
        "create/contact_page.dart",
        include_str!("../templates/create/contact_page.dart.jinja"),
    ),
    (
        "create/forms_test.dart",
        include_str!("../templates/create/forms_test.dart.jinja"),
    ),
    (
        "create/tabs_layout.dart",
        include_str!("../templates/create/tabs_layout.dart.jinja"),
    ),
    (
        "create/tabs_home_nav.dart",
        include_str!("../templates/create/tabs_home_nav.dart.jinja"),
    ),
    (
        "create/tabs_home_page.dart",
        include_str!("../templates/create/tabs_home_page.dart.jinja"),
    ),
    (
        "create/tabs_about_nav.dart",
        include_str!("../templates/create/tabs_about_nav.dart.jinja"),
    ),
    (
        "create/tabs_about_page.dart",
        include_str!("../templates/create/tabs_about_page.dart.jinja"),
    ),
    (
        "create/adaptive_test.dart",
        include_str!("../templates/create/adaptive_test.dart.jinja"),
    ),
    (
        "create/otel_test.dart",
        include_str!("../templates/create/otel_test.dart.jinja"),
    ),
    (
        "create/sentry_test.dart",
        include_str!("../templates/create/sentry_test.dart.jinja"),
    ),
    (
        "create/auth_setup.dart",
        include_str!("../templates/create/auth_setup.dart.jinja"),
    ),
    (
        "create/auth_guard.dart",
        include_str!("../templates/create/auth_guard.dart.jinja"),
    ),
    (
        "create/account_page.dart",
        include_str!("../templates/create/account_page.dart.jinja"),
    ),
    (
        "create/sign_in_action.dart",
        include_str!("../templates/create/sign_in_action.dart.jinja"),
    ),
    (
        "create/sign_in_guard.dart",
        include_str!("../templates/create/sign_in_guard.dart.jinja"),
    ),
    (
        "create/sign_in_page.dart",
        include_str!("../templates/create/sign_in_page.dart.jinja"),
    ),
    (
        "create/auth_test.dart",
        include_str!("../templates/create/auth_test.dart.jinja"),
    ),
    (
        "create/i18n_app.dart",
        include_str!("../templates/create/i18n_app.dart.jinja"),
    ),
    (
        "create/i18n_en.arb",
        include_str!("../templates/create/i18n_en.arb.jinja"),
    ),
    (
        "create/i18n_fr.arb",
        include_str!("../templates/create/i18n_fr.arb.jinja"),
    ),
    (
        "create/translations_page.dart",
        include_str!("../templates/create/translations_page.dart.jinja"),
    ),
    (
        "create/i18n_test.dart",
        include_str!("../templates/create/i18n_test.dart.jinja"),
    ),
    (
        "create/images.dart",
        include_str!("../templates/create/images.dart.jinja"),
    ),
    (
        "create/photo_page.dart",
        include_str!("../templates/create/photo_page.dart.jinja"),
    ),
    (
        "create/image_test.dart",
        include_str!("../templates/create/image_test.dart.jinja"),
    ),
];

fn env() -> &'static Environment<'static> {
    static ENV: OnceLock<Environment<'static>> = OnceLock::new();
    ENV.get_or_init(|| {
        let mut env = Environment::new();
        env.set_trim_blocks(true);
        env.set_lstrip_blocks(true);
        env.set_keep_trailing_newline(true);
        env.set_undefined_behavior(minijinja::UndefinedBehavior::Strict);
        for (name, src) in TEMPLATES {
            env.add_template(name, src)
                .unwrap_or_else(|e| panic!("template {name}: {e:#}"));
        }
        env
    })
}

pub fn render(name: &str, cx: impl Serialize) -> String {
    env()
        .get_template(name)
        .and_then(|t| t.render(cx))
        .unwrap_or_else(|e| panic!("rendering {name}: {e:#}"))
}
