// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /              HomeRoute         (tabs)/(home)/page.dart
//   /profile       ProfileRoute      (tabs)/profile/page.dart
//   /profile/edit  EditProfileRoute  (tabs)/profile/edit/page.dart
//   /search        SearchRoute       (tabs)/search/page.dart
//   /settings      SettingsRoute     settings/page.dart

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/(tabs)/layout.dart' as _i0;
import 'app/(tabs)/(home)/page.dart' as _i1;
import 'app/(tabs)/profile/page.dart' as _i2;
import 'app/(tabs)/profile/edit/page.dart' as _i3;
import 'app/(tabs)/search/page.dart' as _i4;
import 'app/settings/page.dart' as _i5;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      StatefulShellRoute.indexedStack(
        builder: (context, state, navigationShell) => _i0.TabsLayout(navigationShell: navigationShell),
        branches: [
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/'),
                builder: (context, state) => _i1.HomePage(),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/search'),
                builder: (context, state) => _i4.SearchPage(),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/profile'),
                builder: (context, state) => _i2.ProfilePage(),
                routes: [
                  GoRoute(
                    path: 'edit',
                    builder: (context, state) => _i3.EditProfilePage(),
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
      GoRoute(
        path: joinLocation(at, '/settings'),
        builder: (context, state) => _i5.SettingsPage(),
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);
}

/// `/` → (tabs)/(home)/page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/profile` → (tabs)/profile/page.dart
final class ProfileRoute extends TypedLocation {
  const ProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile');
}

/// `/profile/edit` → (tabs)/profile/edit/page.dart
final class EditProfileRoute extends TypedLocation {
  const EditProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile/edit');
}

/// `/search` → (tabs)/search/page.dart
final class SearchRoute extends TypedLocation {
  const SearchRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/search');
}

/// `/settings` → settings/page.dart
final class SettingsRoute extends TypedLocation {
  const SettingsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/settings');
}
