// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import

import 'package:fespalier/fespalier.dart';
import 'app.g.dart';

import 'app/(tabs)/search/meta.dart' as _i0;
import 'app/settings/meta.dart' as _i1;

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '(tabs)/(home)',
      groups: ['(tabs)', '(home)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 0, '(home)')],
    ),
    RouteInfo(
      type: AuthorsRoute,
      path: '/library/authors',
      folder: '(tabs)/library/authors',
      groups: ['(tabs)'],
      layouts: ['(tabs)', '(tabs)/library'],
      tabs: [RouteTab('(tabs)', 3, 'library'), RouteTab('(tabs)/library', 1, 'authors')],
    ),
    RouteInfo(
      type: BooksRoute,
      path: '/library/books',
      folder: '(tabs)/library/books',
      groups: ['(tabs)'],
      layouts: ['(tabs)', '(tabs)/library'],
      tabs: [RouteTab('(tabs)', 3, 'library'), RouteTab('(tabs)/library', 0, 'books')],
    ),
    RouteInfo(
      type: ProfileRoute,
      path: '/profile',
      folder: '(tabs)/profile',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 2, 'profile')],
    ),
    RouteInfo(
      type: EditProfileRoute,
      path: '/profile/edit',
      folder: '(tabs)/profile/edit',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 2, 'profile')],
    ),
    RouteInfo(
      type: SearchRoute,
      path: '/search',
      folder: '(tabs)/search',
      groups: ['(tabs)'],
      layouts: ['(tabs)'],
      tabs: [RouteTab('(tabs)', 1, 'search')],
      meta: _i0.meta,
    ),
    RouteInfo(
      type: SettingsRoute,
      path: '/settings',
      folder: 'settings',
      meta: _i1.meta,
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));
}
