// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /                 HomeRoute         (tabs)/(home)/page.dart  (transition)
//   /library/authors  AuthorsRoute      (tabs)/library/authors/page.dart  (transition)
//   /library/books    BooksRoute        (tabs)/library/books/page.dart  (transition)
//   /profile          ProfileRoute      (tabs)/profile/page.dart  (transition)
//   /profile/edit     EditProfileRoute  (tabs)/profile/edit/page.dart  (transition)
//   /search           SearchRoute       (tabs)/search/page.dart  (transition)
//   /settings         SettingsRoute     settings/page.dart  (transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/transition.dart' as _i0;
import 'app/(tabs)/layout.dart' as _i1;
import 'app/(tabs)/(home)/page.dart' as _i2;
import 'app/(tabs)/library/layout.dart' as _i3;
import 'app/(tabs)/library/authors/page.dart' as _i4;
import 'app/(tabs)/library/books/page.dart' as _i5;
import 'app/(tabs)/profile/page.dart' as _i6;
import 'app/(tabs)/profile/edit/page.dart' as _i7;
import 'app/(tabs)/search/page.dart' as _i8;
import 'app/settings/page.dart' as _i9;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      StatefulShellRoute.indexedStack(
        builder: (context, state, navigationShell) => _i1.TabsLayout(navigationShell: navigationShell),
        branches: [
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/'),
                pageBuilder: (context, state) => _i0.transition(
                  state.pageKey,
                  _i2.HomePage(),
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            preload: true,
            routes: [
              GoRoute(
                path: joinLocation(at, '/search'),
                pageBuilder: (context, state) => _i0.transition(
                  state.pageKey,
                  _i8.SearchPage(),
                ),
              ),
            ],
          ),
          StatefulShellBranch(
            routes: [
              GoRoute(
                path: joinLocation(at, '/profile'),
                pageBuilder: (context, state) => _i0.transition(
                  state.pageKey,
                  _i6.ProfilePage(),
                ),
                routes: [
                  GoRoute(
                    path: 'edit',
                    pageBuilder: (context, state) => _i0.transition(
                      state.pageKey,
                      _i7.EditProfilePage(),
                    ),
                  ),
                ],
              ),
            ],
          ),
          StatefulShellBranch(
            initialLocation: joinLocation(at, '/library/authors'),
            routes: [
              StatefulShellRoute.indexedStack(
                builder: (context, state, navigationShell) => _i3.LibraryLayout(navigationShell: navigationShell),
                branches: [
                  StatefulShellBranch(
                    preload: true,
                    routes: [
                      GoRoute(
                        path: joinLocation(at, '/library/books'),
                        pageBuilder: (context, state) => _i0.transition(
                          state.pageKey,
                          _i5.BooksPage(),
                        ),
                      ),
                    ],
                  ),
                  StatefulShellBranch(
                    routes: [
                      GoRoute(
                        path: joinLocation(at, '/library/authors'),
                        pageBuilder: (context, state) => _i0.transition(
                          state.pageKey,
                          _i4.AuthorsPage(),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
      GoRoute(
        path: joinLocation(at, '/settings'),
        pageBuilder: (context, state) => _i0.transition(
          state.pageKey,
          _i9.SettingsPage(),
        ),
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);
}

/// `/` → (tabs)/(home)/page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/library/authors` → (tabs)/library/authors/page.dart
final class AuthorsRoute extends TypedLocation {
  const AuthorsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/library/authors');
}

/// `/library/books` → (tabs)/library/books/page.dart
final class BooksRoute extends TypedLocation {
  const BooksRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/library/books');
}

/// `/profile` → (tabs)/profile/page.dart
final class ProfileRoute extends TypedLocation {
  const ProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile');
}

/// `/profile/edit` → (tabs)/profile/edit/page.dart
final class EditProfileRoute extends TypedLocation {
  const EditProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile/edit');
}

/// `/search` → (tabs)/search/page.dart
final class SearchRoute extends TypedLocation {
  const SearchRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/search');
}

/// `/settings` → settings/page.dart
final class SettingsRoute extends TypedLocation {
  const SettingsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/settings');
}
