// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /            HomeRoute       page.dart
//   /offline     OfflineRoute    offline/page.dart
//   /pick-place  PickPlaceRoute  pick-place/page.dart

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/offline/page.dart' as _i1;
import 'app/pick-place/page.dart' as _i2;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';
  static GlobalKey<NavigatorState> _rootNavigatorKey = _newRootNavigatorKey();

  static GlobalKey<NavigatorState> _newRootNavigatorKey() =>
      GlobalKey<NavigatorState>(debugLabel: 'root');

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// The root navigator's key: the one given to the last [router] or [mount] call, else a
  /// fresh one made by it (a call without a key never keeps an earlier call's). Routes on
  /// the root navigator (`navigator.dart`, `present.dart`) name it as their
  /// `parentNavigatorKey`; the app can use it to reach the root navigator.
  static GlobalKey<NavigatorState> get rootNavigatorKey => _rootNavigatorKey;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`. [navigatorKey]
  /// is the root navigator's key, when the app has one to supply.
  ///
  /// [launch] (since 0.11.0) is where the app was opened from: it wins over
  /// the platform's initial route and marks the first navigation with its source. It is not
  /// used on the web, where the address bar is the launch.
  static GoRouter router({
    String initialLocation = '/',
    InboundLaunch? launch,
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    final routes = mount(navigatorKey: navigatorKey);
    // pubspec `push_updates_url`: set on every call, so it is the same in each test and each app.
    GoRouter.optionURLReflectsImperativeAPIs = false;
    return launchRouter(launch, (launch) {
      final router = GoRouter(
        initialLocation: launch?.location ?? initialLocation,
        initialExtra: launch?.extra,
        overridePlatformDefaultLocation: launch != null,
        observers: observers,
        restorationScopeId: restorationScopeId,
        navigatorKey: rootNavigatorKey,
        routes: routes,
        errorBuilder: (context, state) => notFound(state.uri),
      );
      if (kFespalierDevTools) devToolsAttach(router);
      return router;
    });
  }

  /// The routes alone, to embed in an existing GoRouter under [at]. Give it that
  /// GoRouter's own `navigatorKey` as [navigatorKey]: routes on the root navigator
  /// name it as their `parentNavigatorKey`, which must be an ancestor navigator's.
  ///
  /// [at] and the key are remembered ([base], [rootNavigatorKey]) until the next call, so a
  /// test restores the defaults with a bare `AppRoutes.mount()`.
  static List<RouteBase> mount({
    String at = '/',
    GlobalKey<NavigatorState>? navigatorKey,
  }) {
    _base = at;
    _rootNavigatorKey = navigatorKey ?? _newRootNavigatorKey();
    if (kFespalierDevTools) devToolsRegister(tree: _devToolsTree, matchUrl: matchUrl);
    return [
      GoRoute(
        path: joinLocation(at, '/'),
        builder: (context, state) => const _i0.HomePage(),
        routes: [
          GoRoute(
            path: 'offline',
            builder: (context, state) => const _i1.OfflinePage(),
          ),
          GoRoute(
            path: 'pick-place',
            builder: (context, state) => const _i2.PickPlacePage(),
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);

  /// Every route as [matchUrl] tries it, most specific first.
  static final List<RouteMatcher> _matchers = [
    RouteMatcher([], (s) => UrlMatch(s.uri, const HomeRoute(), const {}, const [])),
    RouteMatcher(['offline'], (s) => UrlMatch(s.uri, const OfflineRoute(), const {}, const [])),
    RouteMatcher(['pick-place'], (s) => UrlMatch(s.uri, const PickPlaceRoute(), const {}, const [])),
  ];

  /// [uri] matched to its route: the typed route, the parameters parsed from the URL and
  /// the providers of its data. Null when no route fits, or a segment doesn't parse (the
  /// not-found rule). The mount point is taken off; no guard runs and no widget is built.
  /// The route manifest adds `match`, which also names the route's info.
  static UrlMatch? matchUrl(Uri uri) => matchRoutes(uri, base, _matchers);

  /// The providers of the data of the route at [uri], outermost first: the `data.dart` of
  /// each section above it, then its own. They are the ones the page watches (`dataAt(uri)`
  /// of `/products/42` is `[ProductRoute.data(42)]`), so warming them, with
  /// `ref.prefetchAll(AppRoutes.dataAt(uri) ?? [])`, warms the page. Empty for a route
  /// without data; null when no route fits or a segment doesn't parse.
  static List<ProviderListenable<AsyncValue<Object?>>>? dataAt(Uri uri) => matchUrl(uri)?.data;

  /// Starts loading everything the page at [uri] reads, `ref.prefetchAll(dataAt(uri) ?? [])`: one
  /// handle keeps it all alive until it is closed (or `keepFor` passes). A location that matches no
  /// route, or a route without data, has nothing to warm and gets a closed handle. It never
  /// navigates and runs no guard.
  static PrefetchHandle preload(WidgetRef ref, Uri uri, {Duration? keepFor}) => ref.prefetchAll(dataAt(uri) ?? const [], keepFor: keepFor);

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;

  /// [uri] matched to its route, with the [RouteInfo], the parsed parameters and the
  /// providers of its data: [AppManifest.match].
  static RouteMatch? match(Uri uri) => AppManifest.match(uri);
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '',
    ),
    RouteInfo(
      type: OfflineRoute,
      path: '/offline',
      folder: 'offline',
    ),
    RouteInfo(
      type: PickPlaceRoute,
      path: '/pick-place',
      folder: 'pick-place',
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));

  /// [uri] matched to its route: the [RouteInfo], the parameters parsed from the URL and the
  /// providers of its data (each section's, then the route's own), the same ones the page
  /// watches. Null when no route fits or a segment doesn't parse (the not-found rule). The
  /// mount point is taken off; no guard runs and no widget is built.
  static RouteMatch? match(Uri uri) {
    final m = AppRoutes.matchUrl(uri);
    return m == null ? null : RouteMatch(byType[m.type]!, m);
  }
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');

  /// The HomeRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static HomeRoute of(BuildContext context) => routeOf<HomeRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static HomeRoute? maybeOf(BuildContext context) => maybeRouteOf<HomeRoute>(context, AppRoutes.matchUrl);
}

/// `/offline` → offline/page.dart
final class OfflineRoute extends TypedLocation {
  const OfflineRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/offline');

  /// The OfflineRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static OfflineRoute of(BuildContext context) => routeOf<OfflineRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static OfflineRoute? maybeOf(BuildContext context) => maybeRouteOf<OfflineRoute>(context, AppRoutes.matchUrl);
}

/// `/pick-place` → pick-place/page.dart
final class PickPlaceRoute extends TypedLocation {
  const PickPlaceRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/pick-place');

  /// The PickPlaceRoute the route around [context] is at, parsed from its location by [AppRoutes.matchUrl].
  /// Throws a [StateError] when that is another route.
  static PickPlaceRoute of(BuildContext context) => routeOf<PickPlaceRoute>(context, AppRoutes.matchUrl);

  /// Like [of], or null when the route around [context] is another one.
  static PickPlaceRoute? maybeOf(BuildContext context) => maybeRouteOf<PickPlaceRoute>(context, AppRoutes.matchUrl);
}

/// The route tree as JSON (`fsp routes --graph json`), for the DevTools extension: a function, so
/// a hot reload hands it the new one. It is only read under `kFespalierDevTools`, which a release
/// build has false, so the string is not in one.
String _devToolsTree() => '{"protocol":1,"package":"maps","appDir":"lib/app","items":[{"type":"route","pattern":"/","route":"HomeRoute","file":"page.dart","folder":"","markers":[],"params":[],"redirect":false,"children":[{"type":"route","pattern":"/offline","route":"OfflineRoute","file":"offline/page.dart","folder":"offline","markers":[],"params":[],"redirect":false,"children":[]},{"type":"route","pattern":"/pick-place","route":"PickPlaceRoute","file":"pick-place/page.dart","folder":"pick-place","markers":[],"params":[],"redirect":false,"children":[]}]}],"sites":{}}';
