// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /                       HomeRoute          page.dart  (layout, transition)
//   /:slug                  SlugRoute          $slug/page.dart  (transition)
//   /profile                ProfileRoute       (account)/profile/page.dart  (transition)
//   /settings               SettingsRoute      (account)/settings/page.dart  (transition)
//   /admin                  AdminRoute         (members)/admin/page.dart  (guard, transition)
//   /inbox                  InboxRoute         (members)/inbox/page.dart  (transition)
//   /counter                CounterRoute       counter/page.dart  (data, transition)
//   /login                  LoginRoute         login/page.dart  (transition)
//   /old-search             OldSearchRoute     old-search/redirect.dart  (redirect)
//   /old-shops/:shop        OldShopsShopRoute  old-shops/$shop/redirect.dart  (redirect)
//   /search                 SearchRoute        search/page.dart  (data, transition)
//   /shops/:shop            ShopRoute          shops/$shop/page.dart  (guard, layout, transition)
//   /shops/:shop/items/:id  ItemRoute          shops/$shop/items/$id/page.dart  (data, transition)
//   /ticks                  TicksRoute         ticks/page.dart  (data, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/transition.dart' as _i1;
import 'app/layout.dart' as _i2;
import 'app/\$slug/page.dart' as _i3;
import 'app/(account)/transition.dart' as _i4;
import 'app/(account)/layout.dart' as _i5;
import 'app/(account)/profile/page.dart' as _i6;
import 'app/(account)/settings/page.dart' as _i7;
import 'app/(members)/guard.dart' as _i8;
import 'app/(members)/admin/page.dart' as _i9;
import 'app/(members)/admin/guard.dart' as _i10;
import 'app/(members)/inbox/page.dart' as _i11;
import 'app/counter/data.dart' as _i12;
import 'app/counter/page.dart' as _i13;
import 'app/login/page.dart' as _i14;
import 'app/old-search/redirect.dart' as _i15;
import 'app/old-shops/\$shop/redirect.dart' as _i16;
import 'app/search/data.dart' as _i17;
import 'app/search/page.dart' as _i18;
import 'app/shops/\$shop/page.dart' as _i19;
import 'app/shops/\$shop/layout.dart' as _i20;
import 'app/shops/\$shop/guard.dart' as _i21;
import 'app/shops/\$shop/items/\$id/data.dart' as _i22;
import 'app/shops/\$shop/items/\$id/page.dart' as _i23;
import 'app/shops/\$shop/items/\$id/error.dart' as _i24;
import 'app/ticks/data.dart' as _i25;
import 'app/ticks/page.dart' as _i26;
import 'app/ticks/transition.dart' as _i27;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      ShellRoute(
        builder: (context, state, child) => buildWithParams(
          () => _layout0(state),
          (v) => _i2.RootLayout(child: child, banner: v.banner),
          () => notFound(state.uri),
        ),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              _i0.HomePage(),
            ),
            routes: [
              ShellRoute(
                builder: (context, state, child) => _i5.AccountLayout(child: child),
                routes: [
                  GoRoute(
                    path: 'profile',
                    pageBuilder: (context, state) => _i4.transition(
                      state.pageKey,
                      _i6.ProfilePage(),
                    ),
                  ),
                  GoRoute(
                    path: 'settings',
                    pageBuilder: (context, state) => _i4.transition(
                      state.pageKey,
                      _i7.SettingsPage(),
                    ),
                  ),
                ],
              ),
              GoRoute(
                path: 'admin',
                redirect: (context, state) => firstRedirect([
                  () => _i8.guard(ProviderScope.containerOf(context, listen: false), uri: state.uri),
                  () => _i10.guard(ProviderScope.containerOf(context, listen: false)),
                ]),
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  _i9.AdminPage(),
                ),
              ),
              GoRoute(
                path: 'inbox',
                redirect: (context, state) => _i8.guard(ProviderScope.containerOf(context, listen: false), uri: state.uri),
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params7(state),
                    (v) => _i11.InboxPage(folder: v.folder),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'counter',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_i12.data),
                    refresh: (ref) => ref.invalidate(_i12.data),
                    data: (d) => _i13.CounterPage(count: d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                  ),
                ),
              ),
              GoRoute(
                path: 'login',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params9(state),
                    (v) => _i14.LoginPage(from: v.from),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'old-search',
                redirect: (context, state) => guardWithParams(
                  () => _params10(state),
                  (v) => _i15.redirect(q: v.q),
                ),
              ),
              GoRoute(
                path: 'search',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params13(state),
                    (v) => DataView(
                      watch: (ref) => ref.watch(_data13((q: v.q, page: v.page))),
                      refresh: (ref) => ref.invalidate(_data13((q: v.q, page: v.page))),
                      data: (d) => _i18.SearchPage(results: d, q: v.q, page: v.page, tags: v.tags),
                      loading: () => const DefaultLoading(),
                      error: (e, st, retry) => DefaultError(error: e, retry: retry),
                    ),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'ticks',
                pageBuilder: (context, state) => _i27.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_data18),
                    refresh: (ref) => ref.invalidate(_data18),
                    data: (d) => _i26.TicksPage(data: d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                  ),
                ),
              ),
              GoRoute(
                path: ':slug',
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params1(state),
                    (v) => _i3.SlugPage(slug: v.slug),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'old-shops/:shop',
                redirect: (context, state) => guardWithParams(
                  () => _params12(state),
                  (v) => _i16.redirect(shop: v.shop),
                ),
              ),
              ShellRoute(
                builder: (context, state, child) => buildWithParams(
                  () => _layout15(state),
                  (v) => _i20.ShopLayout(shop: v.shop, child: child),
                  () => notFound(state.uri),
                ),
                routes: [
                  GoRoute(
                    path: 'shops/:shop',
                    redirect: (context, state) => guardWithParams(
                      () => _params15(state),
                      (v) => _i21.guard(ProviderScope.containerOf(context, listen: false), shop: v.shop),
                    ),
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params15(state),
                        (v) => _i19.ShopPage(shop: v.shop),
                        () => notFound(state.uri),
                      ),
                    ),
                    routes: [
                      GoRoute(
                        path: 'items/:id',
                        pageBuilder: (context, state) => _i1.transition(
                          state.pageKey,
                          buildWithParams(
                            () => _params17(state),
                            (v) => DataView(
                              watch: (ref) => ref.watch(_data17((shop: v.shop, id: v.id))),
                              refresh: (ref) => ref.invalidate(_data17((shop: v.shop, id: v.id))),
                              data: (d) => _i23.ItemPage(d),
                              loading: () => const DefaultLoading(),
                              error: (e, st, retry) => _i24.ItemError(e, retry),
                            ),
                            () => notFound(state.uri),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
            ],
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/:slug` → $slug/page.dart
final class SlugRoute extends TypedLocation {
  const SlugRoute({required this.slug});

  final String slug;

  @override
  String get location => joinLocation(AppRoutes.base, '/${Uri.encodeComponent(slug)}');
}

/// `/profile` → (account)/profile/page.dart
final class ProfileRoute extends TypedLocation {
  const ProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile');
}

/// `/settings` → (account)/settings/page.dart
final class SettingsRoute extends TypedLocation {
  const SettingsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/settings');
}

/// `/admin` → (members)/admin/page.dart
final class AdminRoute extends TypedLocation {
  const AdminRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/admin');
}

/// `/inbox` → (members)/inbox/page.dart
final class InboxRoute extends TypedLocation {
  const InboxRoute({this.folder});

  final String? folder;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/inbox'), {'folder': folder});
}

/// `/counter` → counter/page.dart
final class CounterRoute extends TypedLocation {
  const CounterRoute();

  /// counter/data.dart as a Riverpod provider.
  static final data = _i12.data;

  @override
  String get location => joinLocation(AppRoutes.base, '/counter');

  /// Re-runs counter/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

/// `/login` → login/page.dart
final class LoginRoute extends TypedLocation {
  const LoginRoute({this.from});

  final String? from;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/login'), {'from': from});
}

/// `/old-search` → old-search/redirect.dart
final class OldSearchRoute extends TypedLocation {
  const OldSearchRoute({this.q});

  final String? q;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/old-search'), {'q': q});
}

/// `/old-shops/:shop` → old-shops/$shop/redirect.dart
final class OldShopsShopRoute extends TypedLocation {
  const OldShopsShopRoute({required this.shop});

  final String shop;

  @override
  String get location => joinLocation(AppRoutes.base, '/old-shops/${Uri.encodeComponent(shop)}');
}

/// `/search` → search/page.dart
final class SearchRoute extends TypedLocation {
  const SearchRoute({this.q, this.page, this.tags = const []});

  final String? q;
  final int? page;
  final List<String> tags;

  /// search/data.dart as a Riverpod provider keyed by `(q, page)`.
  static final data = _data13;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/search'), {'q': q, 'page': page, 'tags': tags});

  /// Re-runs search/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data((q: q, page: page)).future);
}

/// `/shops/:shop` → shops/$shop/page.dart
final class ShopRoute extends TypedLocation {
  const ShopRoute({required this.shop});

  final String shop;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}');
}

/// `/shops/:shop/items/:id` → shops/$shop/items/$id/page.dart
final class ItemRoute extends TypedLocation {
  const ItemRoute({required this.shop, required this.id});

  final String shop;
  final int id;

  /// shops/$shop/items/$id/data.dart as a Riverpod provider keyed by `(shop, id)`.
  static final data = _data17;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}/items/$id');

  /// Re-runs shops/$shop/items/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data((shop: shop, id: id)).future);
}

/// `/ticks` → ticks/page.dart
final class TicksRoute extends TypedLocation {
  const TicksRoute();

  /// ticks/data.dart as a Riverpod provider.
  static final data = _data18;

  @override
  String get location => joinLocation(AppRoutes.base, '/ticks');

  /// Restarts ticks/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

({String slug}) _params1(GoRouterState s) => (slug: Segment.asString(s, 'slug'));

({String? folder}) _params7(GoRouterState s) => (folder: Query.asString(s, 'folder'));

({String? from}) _params9(GoRouterState s) => (from: Query.asString(s, 'from'));

({String? q}) _params10(GoRouterState s) => (q: Query.asString(s, 'q'));

({String shop}) _params12(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({String? q, int? page, List<String> tags}) _params13(GoRouterState s) => (q: Query.asString(s, 'q'), page: Query.asInt(s, 'page'), tags: Query.asStringList(s, 'tags'));

({String shop}) _params15(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({String shop, int id}) _params17(GoRouterState s) => (shop: Segment.asString(s, 'shop'), id: Segment.asInt(s, 'id'));

({String? banner}) _layout0(GoRouterState s) => (banner: Query.asString(s, 'banner'));

({String shop}) _layout15(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

final _data13 = FutureProvider.autoDispose.family(
  (Ref ref, ({String? q, int? page}) k) => _i17.data(ref, q: k.q, page: k.page),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);

final _data17 = FutureProvider.autoDispose.family(
  (Ref ref, ({String shop, int id}) k) => _i22.data(ref, shop: k.shop, id: k.id),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);

final _data18 = StreamProvider.autoDispose(
  (Ref ref) => _i25.data(ref),
  // No automatic retry: error.dart and its Retry button are the retry UX.
  retry: (retryCount, error) => null,
);
