// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element, undefined_shown_name, unused_shown_name, duplicate_import
//
//   /                               HomeRoute           page.dart  (layout, transition)
//   /:slug                          SlugRoute           $slug/page.dart  (transition)
//   /profile                        ProfileRoute        (account)/profile/page.dart  (transition)
//   /settings                       SettingsRoute       (account)/settings/page.dart  (transition)
//   /admin                          AdminRoute          (members)/admin/page.dart  (guard, transition)
//   /inbox                          InboxRoute          (members)/inbox/page.dart  (transition)
//   /catalog                        CatalogRoute        catalog/page.dart  (data, transition)
//   /catalog/:productId             ProductDetailRoute  catalog/$productId/page.dart  (data, transition)
//   /catalog/:productId/reviews     ReviewsRoute        catalog/$productId/reviews/page.dart  (data, transition)
//   /counter                        CounterRoute        counter/page.dart  (data, transition)
//   /docs                           DocsIndexRoute      docs/page.dart  (transition)
//   /docs/*rest                     DocsRoute           docs/$$rest/page.dart  (transition)
//   /docs/new                       NewDocRoute         docs/new/page.dart  (transition)
//   /files/*path?                   FilesRoute          files/$$$path/page.dart  (transition)
//   /login                          LoginRoute          login/page.dart  (transition)
//   /notes/:id                      NoteRoute           notes/$id/page.dart  (transition)
//   /old-search                     OldSearchRoute      old-search/redirect.dart  (redirect)
//   /old-shops/:shop                OldShopsShopRoute   old-shops/$shop/redirect.dart  (redirect)
//   /photos                         PhotosRoute         photos/page.dart  (transition)
//   /photos/:id                     PhotoRoute          photos/$id/page.dart  (transition)
//   /photos/sort                    SortRoute           photos/sort/page.dart  (transition)
//   /photos/upload                  UploadRoute         photos/upload/page.dart  (transition)
//   /search                         SearchRoute         search/page.dart  (data, transition)
//   /shops/:shop                    ShopRoute           shops/$shop/page.dart  (guard, layout, transition)
//   /shops/:shop/items/:id          ItemRoute           shops/$shop/items/$id/page.dart  (data, transition)
//   /teams/:teamId/members          MembersRoute        teams/$teamId/members/page.dart  (transition)
//   /teams/:teamId/members/:member  MemberRoute         teams/$teamId/members/$member/page.dart  (data, transition)
//   /teams/:teamId/settings         TeamSettingsRoute   teams/$teamId/settings/page.dart  (transition)
//   /ticks                          TicksRoute          ticks/page.dart  (data, transition)
//   /wiki/*article                  WikiRoute           wiki/$$article/page.dart  (data, transition)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/transition.dart' as _i1;
import 'app/layout.dart' as _i2;
import 'app/\$slug/page.dart' as _i3;
import 'app/(account)/transition.dart' as _i4;
import 'app/(account)/layout.dart' as _i5;
import 'app/(account)/profile/page.dart' as _i6;
import 'app/(account)/settings/page.dart' as _i7;
import 'app/(members)/guard.dart' as _i8;
import 'app/(members)/admin/page.dart' as _i9;
import 'app/(members)/admin/guard.dart' as _i10;
import 'app/(members)/inbox/page.dart' as _i11;
import 'app/catalog/data.dart' as _i12;
import 'app/catalog/page.dart' as _i13;
import 'app/catalog/\$productId/data.dart' as _i14;
import 'app/catalog/\$productId/page.dart' as _i15;
import 'app/catalog/\$productId/loading.dart' as _i16;
import 'app/catalog/\$productId/error.dart' as _i17;
import 'app/catalog/\$productId/reviews/data.dart' as _i18;
import 'app/catalog/\$productId/reviews/page.dart' as _i19;
import 'app/counter/data.dart' as _i20;
import 'app/counter/page.dart' as _i21;
import 'app/docs/page.dart' as _i22;
import 'app/docs/\$\$rest/page.dart' as _i23;
import 'app/docs/new/page.dart' as _i24;
import 'app/files/\$\$\$path/page.dart' as _i25;
import 'app/login/page.dart' as _i26;
import 'app/notes/\$id/page.dart' as _i27;
import 'app/old-search/redirect.dart' as _i28;
import 'app/old-shops/\$shop/redirect.dart' as _i29;
import 'app/photos/page.dart' as _i30;
import 'app/photos/\$id/page.dart' as _i31;
import 'app/photos/\$id/transition.dart' as _i32;
import 'app/photos/sort/page.dart' as _i33;
import 'app/photos/sort/transition.dart' as _i34;
import 'app/photos/upload/page.dart' as _i35;
import 'app/photos/upload/transition.dart' as _i36;
import 'app/search/data.dart' as _i37;
import 'app/search/page.dart' as _i38;
import 'app/shops/\$shop/page.dart' as _i39;
import 'app/shops/\$shop/layout.dart' as _i40;
import 'app/shops/\$shop/guard.dart' as _i41;
import 'app/shops/\$shop/items/\$id/data.dart' as _i42;
import 'app/shops/\$shop/items/\$id/page.dart' as _i43;
import 'app/shops/\$shop/items/\$id/error.dart' as _i44;
import 'app/teams/\$teamId/data.dart' as _i45;
import 'app/teams/\$teamId/loading.dart' as _i46;
import 'app/teams/\$teamId/error.dart' as _i47;
import 'app/teams/\$teamId/layout.dart' as _i48;
import 'app/teams/\$teamId/not_found.dart' as _i49;
import 'app/teams/\$teamId/members/page.dart' as _i50;
import 'app/teams/\$teamId/members/not_found.dart' as _i51;
import 'app/teams/\$teamId/members/\$member/data.dart' as _i52;
import 'app/teams/\$teamId/members/\$member/page.dart' as _i53;
import 'app/teams/\$teamId/settings/page.dart' as _i54;
import 'app/ticks/data.dart' as _i55;
import 'app/ticks/page.dart' as _i56;
import 'app/ticks/transition.dart' as _i57;
import 'app/wiki/\$\$article/data.dart' as _i58;
import 'app/wiki/\$\$article/page.dart' as _i59;
import 'app/meta.dart' as _i60;
import 'app/docs/\$\$rest/meta.dart' as _i61;
import 'app/files/\$\$\$path/meta.dart' as _i62;
import 'app/login/meta.dart' as _i63;
import 'app/old-search/meta.dart' as _i64;
import 'app/photos/meta.dart' as _i65;
import 'app/photos/\$id/meta.dart' as _i66;
import 'package:features/models/note.dart' show Note;
import 'package:flutter/material.dart' show Note;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
    String? restorationScopeId,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        restorationScopeId: restorationScopeId,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      ShellRoute(
        pageBuilder: (context, state, child) => layoutPage(
          context,
          state,
          'layout:/',
          buildWithParams(
            () => _layout0(state),
            (v) => _i2.RootLayout(child: child, banner: v.banner),
            () => notFound(state.uri),
          ),
        ),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            caseSensitive: false,
            pageBuilder: (context, state) => _i1.transition(
              state.pageKey,
              _i0.HomePage(),
            ),
            routes: [
              ShellRoute(
                pageBuilder: (context, state, child) => layoutPage(
                  context,
                  state,
                  'layout:(account)/',
                  _i5.AccountLayout(child: child),
                ),
                routes: [
                  GoRoute(
                    path: 'profile',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i4.transition(
                      state.pageKey,
                      _i6.ProfilePage(),
                    ),
                  ),
                  GoRoute(
                    path: 'settings',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i4.transition(
                      state.pageKey,
                      _i7.SettingsPage(),
                    ),
                  ),
                ],
                restorationScopeId: 'layout:(account)/',
              ),
              GoRoute(
                path: 'admin',
                caseSensitive: false,
                redirect: (context, state) => firstRedirect([
                  () => _i8.guard(ProviderScope.containerOf(context, listen: false), uri: state.uri),
                  () => _i10.guard(ProviderScope.containerOf(context, listen: false)),
                ]),
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  _i9.AdminPage(),
                ),
              ),
              GoRoute(
                path: 'inbox',
                caseSensitive: false,
                redirect: (context, state) => _i8.guard(ProviderScope.containerOf(context, listen: false), uri: state.uri),
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params7(state),
                    (v) => _i11.InboxPage(folder: v.folder),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'catalog',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_data8),
                    refresh: (ref) => ref.invalidateSelected(_data8),
                    data: (d) => _i13.CatalogPage(featured: d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                    keepPrevious: true,
                  ),
                ),
                routes: [
                  GoRoute(
                    path: ':productId',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params9(state),
                        (v) => DataView(
                          watch: (ref) => ref.watch(_data9(v.productId)),
                          refresh: (ref) => ref.invalidateSelected(_data9(v.productId)),
                          data: (d) => _i15.ProductDetailPage(product: d),
                          loading: () => _i16.ProductLoading(),
                          error: (e, st, retry) => _i17.ProductError(error: e, retry: retry),
                          keepPrevious: true,
                        ),
                        () => notFound(state.uri),
                      ),
                    ),
                    routes: [
                      GoRoute(
                        path: 'reviews',
                        caseSensitive: false,
                        pageBuilder: (context, state) => _i1.transition(
                          state.pageKey,
                          buildWithParams(
                            () => _params10(state),
                            (v) => DataView(
                              watch: (ref) => ref.watch(_data10((productId: v.productId, page: v.page))),
                              refresh: (ref) => ref.invalidateSelected(_data10((productId: v.productId, page: v.page))),
                              data: (d) => _i19.ReviewsPage(reviews: d),
                              loading: () => _i16.ProductLoading(),
                              error: (e, st, retry) => _i17.ProductError(error: e, retry: retry),
                              keepPrevious: true,
                            ),
                            () => notFound(state.uri),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              GoRoute(
                path: 'counter',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_i20.data),
                    refresh: (ref) => ref.invalidate(_i20.data),
                    data: (d) => _i21.CounterPage(count: d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                    keepPrevious: true,
                  ),
                ),
              ),
              GoRoute(
                path: 'docs',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  _i22.DocsIndexPage(),
                ),
                routes: [
                  GoRoute(
                    path: 'new',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      _i24.NewDocPage(),
                    ),
                  ),
                  GoRoute(
                    path: ':rest(.+)',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params13(state),
                        (v) => _i23.DocsPage(rest: v.rest),
                        () => notFound(state.uri),
                      ),
                    ),
                  ),
                ],
              ),
              GoRoute(
                path: 'files',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params16(state),
                    (v) => _i25.FilesPage(path: v.path),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'login',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params17(state),
                    (v) => _i26.LoginPage(from: v.from),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'old-search',
                caseSensitive: false,
                redirect: (context, state) => guardWithParams(
                  () => _params20(state),
                  (v) => _i28.redirect(q: v.q),
                ),
              ),
              GoRoute(
                path: 'photos',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  _i30.PhotosPage(),
                ),
                routes: [
                  GoRoute(
                    path: 'sort',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i34.transition(
                      state.pageKey,
                      _i33.SortPage(),
                    ),
                  ),
                  GoRoute(
                    path: 'upload',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i36.transition(
                      state.pageKey,
                      _i35.UploadPage(),
                    ),
                  ),
                  GoRoute(
                    path: ':id',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i32.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params24(state),
                        (v) => _i31.PhotoPage(id: v.id),
                        () => notFound(state.uri),
                      ),
                    ),
                  ),
                ],
              ),
              GoRoute(
                path: 'search',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params27(state),
                    (v) => DataView(
                      watch: (ref) => ref.watch(_data27((q: v.q, page: v.page, tags: QueryList(v.tags)))),
                      refresh: (ref) => ref.invalidate(_data27((q: v.q, page: v.page, tags: QueryList(v.tags)))),
                      data: (d) => _i38.SearchPage(results: d, q: v.q, page: v.page, tags: v.tags),
                      loading: () => const DefaultLoading(),
                      error: (e, st, retry) => DefaultError(error: e, retry: retry),
                      keepPrevious: true,
                    ),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'ticks',
                caseSensitive: false,
                pageBuilder: (context, state) => _i57.transition(
                  state.pageKey,
                  DataView(
                    watch: (ref) => ref.watch(_data37),
                    refresh: (ref) => ref.invalidate(_data37),
                    data: (d) => _i56.TicksPage(data: d),
                    loading: () => const DefaultLoading(),
                    error: (e, st, retry) => DefaultError(error: e, retry: retry),
                    keepPrevious: true,
                  ),
                ),
              ),
              GoRoute(
                path: ':slug',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params1(state),
                    (v) => _i3.SlugPage(slug: v.slug),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'notes/:id',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params19(state),
                    (v) => _i27.NotePage(id: v.id, extra: extraOf(state)),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'old-shops/:shop',
                caseSensitive: false,
                redirect: (context, state) => guardWithParams(
                  () => _params22(state),
                  (v) => _i29.redirect(shop: v.shop),
                ),
              ),
              ShellRoute(
                pageBuilder: (context, state, child) => layoutPage(
                  context,
                  state,
                  'layout:shops/\$shop/',
                  buildWithParams(
                    () => _layout29(state),
                    (v) => _i40.ShopLayout(shop: v.shop, child: child),
                    () => notFound(state.uri),
                  ),
                ),
                routes: [
                  GoRoute(
                    path: 'shops/:shop',
                    caseSensitive: false,
                    redirect: (context, state) => guardWithParams(
                      () => _params29(state),
                      (v) => _i41.guard(ProviderScope.containerOf(context, listen: false), shop: v.shop),
                    ),
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params29(state),
                        (v) => _i39.ShopPage(shop: v.shop),
                        () => notFound(state.uri),
                      ),
                    ),
                    routes: [
                      GoRoute(
                        path: 'items/:id',
                        caseSensitive: false,
                        pageBuilder: (context, state) => _i1.transition(
                          state.pageKey,
                          buildWithParams(
                            () => _params31(state),
                            (v) => DataView(
                              watch: (ref) => ref.watch(_data31((shop: v.shop, id: v.id))),
                              refresh: (ref) => ref.invalidate(_data31((shop: v.shop, id: v.id))),
                              data: (d) => _i43.ItemPage(d),
                              loading: () => const DefaultLoading(),
                              error: (e, st, retry) => _i44.ItemError(e, retry),
                              keepPrevious: true,
                            ),
                            () => notFound(state.uri),
                          ),
                        ),
                      ),
                    ],
                  ),
                ],
                restorationScopeId: 'layout:shops/\$shop/',
              ),
              ShellRoute(
                pageBuilder: (context, state, child) => layoutPage(
                  context,
                  state,
                  'layout:teams/\$teamId/',
                  buildWithParams(
                    () => _layout33(state),
                    (v) => DataView(
                      watch: (ref) => ref.watch(_data33(v.teamId)),
                      refresh: (ref) => ref.invalidate(_data33(v.teamId)),
                      data: (d) => _i48.TeamLayout(team: d, child: child),
                      loading: () => _i46.TeamLoading(),
                      error: (e, st, retry) => _i47.TeamError(error: e, retry: retry),
                      keepPrevious: true,
                    ),
                    () => _i49.TeamNotFound(uri: state.uri),
                  ),
                ),
                routes: [
                  GoRoute(
                    path: 'teams/:teamId/members',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params34(state),
                        (v) => SectionView(
                          watch: (ref) => ref.watch(_data33(v.teamId)),
                          data: (s33) => _i50.MembersPage(s33),
                        ),
                        () => _i51.MembersNotFound(uri: state.uri),
                      ),
                    ),
                    routes: [
                      GoRoute(
                        path: ':member',
                        caseSensitive: false,
                        pageBuilder: (context, state) => _i1.transition(
                          state.pageKey,
                          buildWithParams(
                            () => _params35(state),
                            (v) => DataView(
                              watch: (ref) => ref.watch(_data35(v.member)),
                              refresh: (ref) => ref.invalidate(_data35(v.member)),
                              data: (d) => SectionView(
                                watch: (ref) => ref.watch(_data33(v.teamId)),
                                data: (s33) => _i53.MemberPage(label: d, team: s33),
                              ),
                              loading: () => _i46.TeamLoading(),
                              error: (e, st, retry) => _i47.TeamError(error: e, retry: retry),
                              keepPrevious: true,
                            ),
                            () => _i51.MembersNotFound(uri: state.uri),
                          ),
                        ),
                      ),
                    ],
                  ),
                  GoRoute(
                    path: 'teams/:teamId/settings',
                    caseSensitive: false,
                    pageBuilder: (context, state) => _i1.transition(
                      state.pageKey,
                      buildWithParams(
                        () => _params36(state),
                        (v) => SectionView(
                          watch: (ref) => ref.watch(_data33(v.teamId)),
                          data: (s33) => _i54.TeamSettingsPage(data: s33),
                        ),
                        () => _i49.TeamNotFound(uri: state.uri),
                      ),
                    ),
                  ),
                ],
                restorationScopeId: 'layout:teams/\$teamId/',
              ),
              GoRoute(
                path: 'files/:path(.+)',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params16(state),
                    (v) => _i25.FilesPage(path: v.path),
                    () => notFound(state.uri),
                  ),
                ),
              ),
              GoRoute(
                path: 'wiki/:article(.+)',
                caseSensitive: false,
                pageBuilder: (context, state) => _i1.transition(
                  state.pageKey,
                  buildWithParams(
                    () => _params39(state),
                    (v) => DataView(
                      watch: (ref) => ref.watch(_data39(restKey(v.article))),
                      refresh: (ref) => ref.invalidate(_data39(restKey(v.article))),
                      data: (d) => _i59.WikiPage(article: v.article, data: d),
                      loading: () => const DefaultLoading(),
                      error: (e, st, retry) => DefaultError(error: e, retry: retry),
                      keepPrevious: true,
                    ),
                    () => notFound(state.uri),
                  ),
                ),
              ),
            ],
          ),
        ],
        restorationScopeId: 'layout:/',
      ),
    ];
  }

  /// The not_found.dart nearest to [uri]: the deepest folder whose path it is under.
  static Widget notFound(Uri uri) => nearestNotFound(
        uri,
        base,
        [
          (['teams', ':teamId', 'members'], (uri) => _i51.MembersNotFound(uri: uri)),
          (['teams', ':teamId'], (uri) => _i49.TeamNotFound(uri: uri)),
        ],
        (uri) => DefaultNotFound(uri),
        caseSensitive: false,
      );

  /// Every route with its path, folder, groups, layouts and meta: [AppManifest.all].
  static List<RouteInfo<Object?>> get all => AppManifest.all;

  /// Each route by its typed-route class: [AppManifest.byType].
  static Map<Type, RouteInfo<Object?>> get byType => AppManifest.byType;

  /// Each route by its path template: [AppManifest.byPath].
  static Map<String, RouteInfo<Object?>> get byPath => AppManifest.byPath;
}

/// What `fsp gen` knows about every route: its typed route, path template,
/// folder, groups, layouts, parameters and `meta.dart`.
abstract final class AppManifest {
  /// Every route, in the order of the table at the top of the file.
  static const List<RouteInfo<Object?>> all = [
    RouteInfo(
      type: HomeRoute,
      path: '/',
      folder: '',
      layouts: [''],
      meta: _i60.meta,
    ),
    RouteInfo(
      type: SlugRoute,
      path: '/:slug',
      folder: '\$slug',
      layouts: [''],
      segments: [RouteParam('slug', 'String')],
    ),
    RouteInfo(
      type: ProfileRoute,
      path: '/profile',
      folder: '(account)/profile',
      groups: ['(account)'],
      layouts: ['', '(account)'],
    ),
    RouteInfo(
      type: SettingsRoute,
      path: '/settings',
      folder: '(account)/settings',
      groups: ['(account)'],
      layouts: ['', '(account)'],
    ),
    RouteInfo(
      type: AdminRoute,
      path: '/admin',
      folder: '(members)/admin',
      groups: ['(members)'],
      layouts: [''],
    ),
    RouteInfo(
      type: InboxRoute,
      path: '/inbox',
      folder: '(members)/inbox',
      groups: ['(members)'],
      layouts: [''],
      query: [RouteParam('folder', 'String?')],
    ),
    RouteInfo(
      type: CatalogRoute,
      path: '/catalog',
      folder: 'catalog',
      layouts: [''],
      dataKeys: [],
    ),
    RouteInfo(
      type: ProductDetailRoute,
      path: '/catalog/:productId',
      folder: 'catalog/\$productId',
      layouts: [''],
      segments: [RouteParam('productId', 'String')],
      dataKeys: ['productId'],
    ),
    RouteInfo(
      type: ReviewsRoute,
      path: '/catalog/:productId/reviews',
      folder: 'catalog/\$productId/reviews',
      layouts: [''],
      segments: [RouteParam('productId', 'String')],
      query: [RouteParam('page', 'int?')],
      dataKeys: ['productId', 'page'],
    ),
    RouteInfo(
      type: CounterRoute,
      path: '/counter',
      folder: 'counter',
      layouts: [''],
      dataKeys: [],
    ),
    RouteInfo(
      type: DocsIndexRoute,
      path: '/docs',
      folder: 'docs',
      layouts: [''],
    ),
    RouteInfo(
      type: DocsRoute,
      path: '/docs/*rest',
      folder: 'docs/\$\$rest',
      layouts: [''],
      segments: [RouteParam('rest', 'List<String>', catchAll: true)],
      meta: _i61.meta,
    ),
    RouteInfo(
      type: NewDocRoute,
      path: '/docs/new',
      folder: 'docs/new',
      layouts: [''],
    ),
    RouteInfo(
      type: FilesRoute,
      path: '/files/*path?',
      folder: 'files/\$\$\$path',
      layouts: [''],
      segments: [RouteParam('path', 'List<String>', catchAll: true)],
      meta: _i62.meta,
    ),
    RouteInfo(
      type: LoginRoute,
      path: '/login',
      folder: 'login',
      layouts: [''],
      query: [RouteParam('from', 'String?')],
      meta: _i63.meta,
    ),
    RouteInfo(
      type: NoteRoute,
      path: '/notes/:id',
      folder: 'notes/\$id',
      layouts: [''],
      segments: [RouteParam('id', 'int')],
    ),
    RouteInfo(
      type: OldSearchRoute,
      path: '/old-search',
      folder: 'old-search',
      presentation: RoutePresentation.redirect,
      layouts: [''],
      query: [RouteParam('q', 'String?')],
      meta: _i64.meta,
    ),
    RouteInfo(
      type: OldShopsShopRoute,
      path: '/old-shops/:shop',
      folder: 'old-shops/\$shop',
      presentation: RoutePresentation.redirect,
      layouts: [''],
      segments: [RouteParam('shop', 'String')],
    ),
    RouteInfo(
      type: PhotosRoute,
      path: '/photos',
      folder: 'photos',
      layouts: [''],
      meta: _i65.meta,
    ),
    RouteInfo(
      type: PhotoRoute,
      path: '/photos/:id',
      folder: 'photos/\$id',
      layouts: [''],
      segments: [RouteParam('id', 'int')],
      meta: _i66.meta,
    ),
    RouteInfo(
      type: SortRoute,
      path: '/photos/sort',
      folder: 'photos/sort',
      layouts: [''],
    ),
    RouteInfo(
      type: UploadRoute,
      path: '/photos/upload',
      folder: 'photos/upload',
      layouts: [''],
    ),
    RouteInfo(
      type: SearchRoute,
      path: '/search',
      folder: 'search',
      layouts: [''],
      query: [RouteParam('q', 'String?'), RouteParam('page', 'int?'), RouteParam('tags', 'List<String>')],
      dataKeys: ['q', 'page', 'tags'],
    ),
    RouteInfo(
      type: ShopRoute,
      path: '/shops/:shop',
      folder: 'shops/\$shop',
      layouts: ['', 'shops/\$shop'],
      segments: [RouteParam('shop', 'String')],
    ),
    RouteInfo(
      type: ItemRoute,
      path: '/shops/:shop/items/:id',
      folder: 'shops/\$shop/items/\$id',
      layouts: ['', 'shops/\$shop'],
      segments: [RouteParam('shop', 'String'), RouteParam('id', 'int')],
      dataKeys: ['shop', 'id'],
    ),
    RouteInfo(
      type: MembersRoute,
      path: '/teams/:teamId/members',
      folder: 'teams/\$teamId/members',
      layouts: ['', 'teams/\$teamId'],
      segments: [RouteParam('teamId', 'String')],
    ),
    RouteInfo(
      type: MemberRoute,
      path: '/teams/:teamId/members/:member',
      folder: 'teams/\$teamId/members/\$member',
      layouts: ['', 'teams/\$teamId'],
      segments: [RouteParam('teamId', 'String'), RouteParam('member', 'int')],
      dataKeys: ['member'],
    ),
    RouteInfo(
      type: TeamSettingsRoute,
      path: '/teams/:teamId/settings',
      folder: 'teams/\$teamId/settings',
      layouts: ['', 'teams/\$teamId'],
      segments: [RouteParam('teamId', 'String')],
    ),
    RouteInfo(
      type: TicksRoute,
      path: '/ticks',
      folder: 'ticks',
      layouts: [''],
      dataKeys: [],
    ),
    RouteInfo(
      type: WikiRoute,
      path: '/wiki/*article',
      folder: 'wiki/\$\$article',
      layouts: [''],
      segments: [RouteParam('article', 'List<String>', catchAll: true)],
      dataKeys: ['article'],
    ),
  ];

  /// Each route by its typed-route class: `AppManifest.byType[ProductRoute]`.
  static final Map<Type, RouteInfo<Object?>> byType = Map.unmodifiable({
    for (final r in all) r.type: r,
  });

  /// Each route by its path template: `AppManifest.byPath['/products/:id']`.
  static final Map<String, RouteInfo<Object?>> byPath = Map.unmodifiable({
    for (final r in all) r.path: r,
  });

  /// The route [state] is at, or null when it is not one of these (a not-found
  /// page, say). Handy in a layout: `AppManifest.of(GoRouterState.of(context))`.
  static RouteInfo<Object?>? of(GoRouterState state) =>
      lookupRoute(byPath, routeTemplate(state, AppRoutes.base));
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/:slug` → $slug/page.dart
final class SlugRoute extends TypedLocation {
  const SlugRoute({required this.slug});

  final String slug;

  @override
  String get location => joinLocation(AppRoutes.base, '/${Uri.encodeComponent(slug)}');
}

/// `/profile` → (account)/profile/page.dart
final class ProfileRoute extends TypedLocation {
  const ProfileRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/profile');
}

/// `/settings` → (account)/settings/page.dart
final class SettingsRoute extends TypedLocation {
  const SettingsRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/settings');
}

/// `/admin` → (members)/admin/page.dart
final class AdminRoute extends TypedLocation {
  const AdminRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/admin');
}

/// `/inbox` → (members)/inbox/page.dart
final class InboxRoute extends TypedLocation {
  const InboxRoute({this.folder});

  final String? folder;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/inbox'), {'folder': folder});
}

/// `/catalog` → catalog/page.dart
final class CatalogRoute extends TypedLocation {
  const CatalogRoute();

  /// catalog/data.dart as a Riverpod provider.
  static final data = _data8;

  @override
  String get location => joinLocation(AppRoutes.base, '/catalog');

  /// Watches catalog/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads catalog/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readSelected(data);

  /// Starts loading catalog/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs catalog/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refreshSelected(data);
}

/// `/catalog/:productId` → catalog/$productId/page.dart
final class ProductDetailRoute extends TypedLocation {
  const ProductDetailRoute({required this.productId});

  final String productId;

  /// catalog/$productId/data.dart as a Riverpod provider keyed by `productId`.
  static final data = _data9;

  @override
  String get location => joinLocation(AppRoutes.base, '/catalog/${Uri.encodeComponent(productId)}');

  /// Watches catalog/$productId/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required String productId}) => ref.watch(data(productId));

  /// Reads catalog/$productId/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required String productId}) => ref.readSelected(data(productId));

  /// Starts loading catalog/$productId/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(productId), keepFor: keepFor);

  /// Re-runs catalog/$productId/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refreshSelected(data(productId));
}

/// `/catalog/:productId/reviews` → catalog/$productId/reviews/page.dart
final class ReviewsRoute extends TypedLocation {
  const ReviewsRoute({required this.productId, this.page});

  final String productId;
  final int? page;

  /// catalog/$productId/reviews/data.dart as a Riverpod provider keyed by `(productId, page)`.
  static final data = _data10;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/catalog/${Uri.encodeComponent(productId)}/reviews'), {'page': page});

  /// Watches catalog/$productId/reviews/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required String productId, int? page}) => ref.watch(data((productId: productId, page: page)));

  /// Reads catalog/$productId/reviews/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required String productId, int? page}) => ref.readSelected(data((productId: productId, page: page)));

  /// Starts loading catalog/$productId/reviews/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data((productId: productId, page: page)), keepFor: keepFor);

  /// Re-runs catalog/$productId/reviews/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refreshSelected(data((productId: productId, page: page)));
}

/// `/counter` → counter/page.dart
final class CounterRoute extends TypedLocation {
  const CounterRoute();

  /// counter/data.dart as a Riverpod provider.
  static final data = _i20.data;

  @override
  String get location => joinLocation(AppRoutes.base, '/counter');

  /// Watches counter/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads counter/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading counter/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Re-runs counter/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

/// `/docs` → docs/page.dart
final class DocsIndexRoute extends TypedLocation {
  const DocsIndexRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/docs');
}

/// `/docs/*rest` → docs/$$rest/page.dart
final class DocsRoute extends TypedLocation {
  const DocsRoute({required this.rest});

  final List<String> rest;

  @override
  String get location {
    assert(rest.isNotEmpty, 'DocsRoute needs at least one part in `rest`; the path without it isn\'t this route');
    return joinLocation(AppRoutes.base, '/docs${restPath(rest)}');
  }
}

/// `/docs/new` → docs/new/page.dart
final class NewDocRoute extends TypedLocation {
  const NewDocRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/docs/new');
}

/// `/files/*path?` → files/$$$path/page.dart
final class FilesRoute extends TypedLocation {
  const FilesRoute({this.path = const []});

  final List<String> path;

  @override
  String get location => joinLocation(AppRoutes.base, '/files${restPath(path)}');
}

/// `/login` → login/page.dart
final class LoginRoute extends TypedLocation {
  const LoginRoute({this.from});

  final String? from;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/login'), {'from': from});
}

/// `/notes/:id` → notes/$id/page.dart
final class NoteRoute extends TypedLocation {
  const NoteRoute({required this.id});

  final int id;

  @override
  String get location => joinLocation(AppRoutes.base, '/notes/$id');

  /// Navigates here with an `extra`: an object that isn't in the URL, so a deep link or a reload leaves it null.
  @override
  void go(BuildContext context, {Note? extra}) => context.go(location, extra: extra);

  @override
  Future<T?> push<T extends Object?>(BuildContext context, {Note? extra}) =>
      context.push<T>(location, extra: extra);

  @override
  void replace(BuildContext context, {Note? extra}) => context.replace(location, extra: extra);
}

/// `/old-search` → old-search/redirect.dart
final class OldSearchRoute extends TypedLocation {
  const OldSearchRoute({this.q});

  final String? q;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/old-search'), {'q': q});
}

/// `/old-shops/:shop` → old-shops/$shop/redirect.dart
final class OldShopsShopRoute extends TypedLocation {
  const OldShopsShopRoute({required this.shop});

  final String shop;

  @override
  String get location => joinLocation(AppRoutes.base, '/old-shops/${Uri.encodeComponent(shop)}');
}

/// `/photos` → photos/page.dart
final class PhotosRoute extends TypedLocation {
  const PhotosRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/photos');
}

/// `/photos/:id` → photos/$id/page.dart
final class PhotoRoute extends TypedLocation {
  const PhotoRoute({required this.id});

  final int id;

  @override
  String get location => joinLocation(AppRoutes.base, '/photos/$id');
}

/// `/photos/sort` → photos/sort/page.dart
final class SortRoute extends TypedLocation {
  const SortRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/photos/sort');
}

/// `/photos/upload` → photos/upload/page.dart
final class UploadRoute extends TypedLocation {
  const UploadRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/photos/upload');
}

/// `/search` → search/page.dart
final class SearchRoute extends TypedLocation {
  const SearchRoute({this.q, this.page, this.tags = const []});

  final String? q;
  final int? page;
  final List<String> tags;

  /// search/data.dart as a Riverpod provider keyed by `(q, page, tags)`.
  static final data = _data27;

  @override
  String get location => withQuery(joinLocation(AppRoutes.base, '/search'), {'q': q, 'page': page, 'tags': tags});

  /// Watches search/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {String? q, int? page, List<String> tags = const []}) => ref.watch(data((q: q, page: page, tags: QueryList(tags))));

  /// Reads search/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {String? q, int? page, List<String> tags = const []}) => ref.readData(data((q: q, page: page, tags: QueryList(tags))));

  /// Starts loading search/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data((q: q, page: page, tags: QueryList(tags))), keepFor: keepFor);

  /// Re-runs search/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data((q: q, page: page, tags: QueryList(tags))).future);
}

/// `/shops/:shop` → shops/$shop/page.dart
final class ShopRoute extends TypedLocation {
  const ShopRoute({required this.shop});

  final String shop;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}');
}

/// `/shops/:shop/items/:id` → shops/$shop/items/$id/page.dart
final class ItemRoute extends TypedLocation {
  const ItemRoute({required this.shop, required this.id});

  final String shop;
  final int id;

  /// shops/$shop/items/$id/data.dart as a Riverpod provider keyed by `(shop, id)`.
  static final data = _data31;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}/items/$id');

  /// Watches shops/$shop/items/$id/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required String shop, required int id}) => ref.watch(data((shop: shop, id: id)));

  /// Reads shops/$shop/items/$id/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required String shop, required int id}) => ref.readData(data((shop: shop, id: id)));

  /// Starts loading shops/$shop/items/$id/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data((shop: shop, id: id)), keepFor: keepFor);

  /// Re-runs shops/$shop/items/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data((shop: shop, id: id)).future);
}

/// `/teams/:teamId/members` → teams/$teamId/members/page.dart
final class MembersRoute extends TypedLocation {
  const MembersRoute({required this.teamId});

  final String teamId;

  @override
  String get location => joinLocation(AppRoutes.base, '/teams/${Uri.encodeComponent(teamId)}/members');
}

/// `/teams/:teamId/members/:member` → teams/$teamId/members/$member/page.dart
final class MemberRoute extends TypedLocation {
  const MemberRoute({required this.teamId, required this.member});

  final String teamId;
  final int member;

  /// teams/$teamId/members/$member/data.dart as a Riverpod provider keyed by `member`.
  static final data = _data35;

  @override
  String get location => joinLocation(AppRoutes.base, '/teams/${Uri.encodeComponent(teamId)}/members/$member');

  /// Watches teams/$teamId/members/$member/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required int member}) => ref.watch(data(member));

  /// Reads teams/$teamId/members/$member/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required int member}) => ref.readData(data(member));

  /// Starts loading teams/$teamId/members/$member/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(member), keepFor: keepFor);

  /// Re-runs teams/$teamId/members/$member/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(member).future);
}

/// `/teams/:teamId/settings` → teams/$teamId/settings/page.dart
final class TeamSettingsRoute extends TypedLocation {
  const TeamSettingsRoute({required this.teamId});

  final String teamId;

  @override
  String get location => joinLocation(AppRoutes.base, '/teams/${Uri.encodeComponent(teamId)}/settings');
}

/// `/ticks` → ticks/page.dart
final class TicksRoute extends TypedLocation {
  const TicksRoute();

  /// ticks/data.dart as a Riverpod provider.
  static final data = _data37;

  @override
  String get location => joinLocation(AppRoutes.base, '/ticks');

  /// Watches ticks/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref) => ref.watch(data);

  /// Reads ticks/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref) => ref.readData(data);

  /// Starts loading ticks/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data, keepFor: keepFor);

  /// Restarts ticks/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

/// `/wiki/*article` → wiki/$$article/page.dart
final class WikiRoute extends TypedLocation {
  const WikiRoute({required this.article});

  final List<String> article;

  /// wiki/$$article/data.dart as a Riverpod provider keyed by `article`.
  static final data = _data39;

  @override
  String get location {
    assert(article.isNotEmpty, 'WikiRoute needs at least one part in `article`; the path without it isn\'t this route');
    return joinLocation(AppRoutes.base, '/wiki${restPath(article)}');
  }

  /// Watches wiki/$$article/data.dart: an `AsyncValue`, typed by inference (static, so it can name the keys).
  static final watch = (WidgetRef ref, {required List<String> article}) => ref.watch(data(restKey(article)));

  /// Reads wiki/$$article/data.dart once, keeping it alive until it completes.
  static final read = (WidgetRef ref, {required List<String> article}) => ref.readData(data(restKey(article)));

  /// Starts loading wiki/$$article/data.dart before navigating; kept for `keepFor` (default 30 s).
  void prefetch(WidgetRef ref, {Duration? keepFor}) => ref.prefetchData(data(restKey(article)), keepFor: keepFor);

  /// Re-runs wiki/$$article/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data(restKey(article)).future);
}

({String slug}) _params1(GoRouterState s) => (slug: Segment.asString(s, 'slug'));

({String? folder}) _params7(GoRouterState s) => (folder: Query.asString(s, 'folder'));

({String productId}) _params9(GoRouterState s) => (productId: Segment.asString(s, 'productId'));

({String productId, int? page}) _params10(GoRouterState s) => (productId: Segment.asString(s, 'productId'), page: Query.asInt(s, 'page'));

({List<String> rest}) _params13(GoRouterState s) => (rest: Segment.asRest(s, 'rest'));

({List<String> path}) _params16(GoRouterState s) => (path: Segment.asRest(s, 'path'));

({String? from}) _params17(GoRouterState s) => (from: Query.asString(s, 'from'));

({int id}) _params19(GoRouterState s) => (id: Segment.asInt(s, 'id'));

({String? q}) _params20(GoRouterState s) => (q: Query.asString(s, 'q'));

({String shop}) _params22(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({int id}) _params24(GoRouterState s) => (id: Segment.asInt(s, 'id'));

({String? q, int? page, List<String> tags}) _params27(GoRouterState s) => (q: Query.asString(s, 'q'), page: Query.asInt(s, 'page'), tags: Query.asStringList(s, 'tags'));

({String shop}) _params29(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({String shop, int id}) _params31(GoRouterState s) => (shop: Segment.asString(s, 'shop'), id: Segment.asInt(s, 'id'));

({String teamId}) _params34(GoRouterState s) => (teamId: Segment.asString(s, 'teamId'));

({String teamId, int member}) _params35(GoRouterState s) => (teamId: Segment.asString(s, 'teamId'), member: Segment.asInt(s, 'member'));

({String teamId}) _params36(GoRouterState s) => (teamId: Segment.asString(s, 'teamId'));

({List<String> article}) _params39(GoRouterState s) => (article: Segment.asRest(s, 'article'));

({String? banner}) _layout0(GoRouterState s) => (banner: Query.asString(s, 'banner'));

({String shop}) _layout29(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({String teamId}) _layout33(GoRouterState s) => (teamId: Segment.asString(s, 'teamId'));

/// data.dart selects the app's own provider: nothing wraps it.
final _data8 = _i12.data();

/// data.dart selects the app's own provider: nothing wraps it (a closure, so its type is inferred).
final _data9 = (String productId) => _i14.data(productId: productId);

/// data.dart selects the app's own provider: nothing wraps it (a closure, so its type is inferred).
final _data10 = (({String productId, int? page}) k) => _i18.data(productId: k.productId, page: k.page);

final _data27 = FutureProvider.autoDispose.family(
  (Ref ref, ({String? q, int? page, QueryList<String> tags}) k) => _i37.data(ref, q: k.q, page: k.page, tags: k.tags),
);

final _data31 = FutureProvider.autoDispose.family(
  (Ref ref, ({String shop, int id}) k) => _i42.data(ref, shop: k.shop, id: k.id),
);

final _data33 = FutureProvider.autoDispose.family(
  (Ref ref, String teamId) => _i45.data(ref, teamId: teamId),
);

final _data35 = FutureProvider.autoDispose.family(
  (Ref ref, int member) => _i52.data(ref, member: member),
);

final _data37 = StreamProvider.autoDispose(
  (Ref ref) => _i55.data(ref),
);

final _data39 = FutureProvider.autoDispose.family(
  (Ref ref, String article) => _i58.data(ref, article: restParts(article)),
);
