// GENERATED by fespalier from lib/app/. Do not edit; run `fsp gen`.
// ignore_for_file: type=lint, unused_import, unused_element
//
//   /                       HomeRoute     page.dart  (layout)
//   /counter                CounterRoute  counter/page.dart  (data)
//   /shops/:shop            ShopRoute     shops/$shop/page.dart  (guard, layout)
//   /shops/:shop/items/:id  ItemRoute     shops/$shop/items/$id/page.dart  (data)
//   /ticks                  TicksRoute    ticks/page.dart  (data)

import 'package:fespalier/fespalier.dart';
import 'package:flutter/widgets.dart';

import 'app/page.dart' as _i0;
import 'app/layout.dart' as _i1;
import 'app/counter/data.dart' as _i2;
import 'app/counter/page.dart' as _i3;
import 'app/shops/\$shop/page.dart' as _i4;
import 'app/shops/\$shop/layout.dart' as _i5;
import 'app/shops/\$shop/guard.dart' as _i6;
import 'app/shops/\$shop/items/\$id/data.dart' as _i7;
import 'app/shops/\$shop/items/\$id/page.dart' as _i8;
import 'app/shops/\$shop/items/\$id/error.dart' as _i9;
import 'app/ticks/data.dart' as _i10;
import 'app/ticks/page.dart' as _i11;

/// The file tree under lib/app/, ready to mount.
abstract final class AppRoutes {
  static String _base = '/';

  /// Where the tree is mounted: '/' standalone, or the `at` given to [mount].
  static String get base => _base;

  /// A standalone router for `MaterialApp.router(routerConfig: ...)`.
  static GoRouter router({
    String initialLocation = '/',
    List<NavigatorObserver>? observers,
  }) =>
      GoRouter(
        initialLocation: initialLocation,
        observers: observers,
        routes: mount(),
        errorBuilder: (context, state) => notFound(state.uri),
      );

  /// The routes alone, to embed in an existing GoRouter under [at].
  static List<RouteBase> mount({String at = '/'}) {
    _base = at;
    return [
      ShellRoute(
        builder: (context, state, child) => _i1.RootLayout(child: child),
        routes: [
          GoRoute(
            path: joinLocation(at, '/'),
            builder: (context, state) => _i0.HomePage(),
            routes: [
              GoRoute(
                path: 'counter',
                builder: (context, state) => DataView(
                  watch: (ref) => ref.watch(_i2.data),
                  refresh: (ref) => ref.invalidate(_i2.data),
                  data: (d) => _i3.CounterPage(count: d),
                  loading: () => const DefaultLoading(),
                  error: (e, st, retry) => DefaultError(error: e, retry: retry),
                ),
              ),
              ShellRoute(
                builder: (context, state, child) => buildWithSegments(
                  () => _seg3(state),
                  (v) => _i5.ShopLayout(shop: v.shop, child: child),
                  () => notFound(state.uri),
                ),
                routes: [
                  GoRoute(
                    path: 'shops/:shop',
                    redirect: (context, state) => guardWithSegments(
                      () => _seg3(state),
                      (v) => _i6.guard(ProviderScope.containerOf(context, listen: false), shop: v.shop),
                    ),
                    builder: (context, state) => buildWithSegments(
                      () => _seg3(state),
                      (v) => _i4.ShopPage(shop: v.shop),
                      () => notFound(state.uri),
                    ),
                    routes: [
                      GoRoute(
                        path: 'items/:id',
                        builder: (context, state) => buildWithSegments(
                          () => _seg5(state),
                          (v) => DataView(
                            watch: (ref) => ref.watch(_data5((shop: v.shop, id: v.id))),
                            refresh: (ref) => ref.invalidate(_data5((shop: v.shop, id: v.id))),
                            data: (d) => _i8.ItemPage(d),
                            loading: () => const DefaultLoading(),
                            error: (e, st, retry) => _i9.ItemError(e, retry),
                          ),
                          () => notFound(state.uri),
                        ),
                      ),
                    ],
                  ),
                ],
              ),
              GoRoute(
                path: 'ticks',
                builder: (context, state) => DataView(
                  watch: (ref) => ref.watch(_data6),
                  refresh: (ref) => ref.invalidate(_data6),
                  data: (d) => _i11.TicksPage(data: d),
                  loading: () => const DefaultLoading(),
                  error: (e, st, retry) => DefaultError(error: e, retry: retry),
                ),
              ),
            ],
          ),
        ],
      ),
    ];
  }

  static Widget notFound(Uri uri) => DefaultNotFound(uri);
}

/// `/` → page.dart
final class HomeRoute extends TypedLocation {
  const HomeRoute();

  @override
  String get location => joinLocation(AppRoutes.base, '/');
}

/// `/counter` → counter/page.dart
final class CounterRoute extends TypedLocation {
  const CounterRoute();

  /// counter/data.dart as a Riverpod provider.
  static final data = _i2.data;

  @override
  String get location => joinLocation(AppRoutes.base, '/counter');

  /// Re-runs counter/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

/// `/shops/:shop` → shops/$shop/page.dart
final class ShopRoute extends TypedLocation {
  const ShopRoute({required this.shop});

  final String shop;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}');
}

/// `/shops/:shop/items/:id` → shops/$shop/items/$id/page.dart
final class ItemRoute extends TypedLocation {
  const ItemRoute({required this.shop, required this.id});

  final String shop;
  final int id;

  /// shops/$shop/items/$id/data.dart as a Riverpod provider keyed by `(shop, id)`.
  static final data = _data5;

  @override
  String get location => joinLocation(AppRoutes.base, '/shops/${Uri.encodeComponent(shop)}/items/$id');

  /// Re-runs shops/$shop/items/$id/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data((shop: shop, id: id)).future);
}

/// `/ticks` → ticks/page.dart
final class TicksRoute extends TypedLocation {
  const TicksRoute();

  /// ticks/data.dart as a Riverpod provider.
  static final data = _data6;

  @override
  String get location => joinLocation(AppRoutes.base, '/ticks');

  /// Restarts ticks/data.dart; completes with the fresh value.
  Future<void> refresh(WidgetRef ref) => ref.refresh(data.future);
}

({String shop}) _seg3(GoRouterState s) => (shop: Segment.asString(s, 'shop'));

({String shop, int id}) _seg5(GoRouterState s) => (shop: Segment.asString(s, 'shop'), id: Segment.asInt(s, 'id'));

final _data5 = FutureProvider.autoDispose.family(
  (Ref ref, ({String shop, int id}) k) => _i7.data(ref, shop: k.shop, id: k.id),
);

final _data6 = StreamProvider.autoDispose(
  (Ref ref) => _i10.data(ref),
);
